"use client";

import { useMemo, useState } from "react";
import type { FinanceAccount, FinanceSnapshot } from "@/core/contracts/Finance";
import { formatMoney, getFinanceAttention, getUpcomingRecurringItems } from "@/services/finance/domain";
import { getUnifiedAccountTotals, getUnifiedCategoryTotals, getUnifiedMonthTotals, mergeFinanceAccounts, mergeFinanceTransactions, type ConnectedFinanceAccount, type ConnectedFinanceTransaction, type UnifiedFinanceAccount } from "@/services/finance/merged";

const card = "relative overflow-hidden rounded-[1.35rem] border border-cyan-200/15 bg-[linear-gradient(145deg,rgba(12,20,53,.92),rgba(3,7,24,.92))] p-5 shadow-[0_0_34px_rgba(40,71,190,.08)] transition duration-300 hover:border-cyan-200/30 hover:shadow-[0_0_42px_rgba(91,61,255,.14)]";
const label = "text-[10px] font-semibold uppercase tracking-[0.24em] text-cyan-100/50";
const muted = "text-white/42";
type Period = "7D" | "30D" | "90D" | "1Y" | "ALL";

export default function FinanceOverview({ data, accounts, balances, connectedAccounts, connectedTransactions, connectedLoading, onSelectConnectedAccount }: { data: FinanceSnapshot; accounts: FinanceAccount[]; balances: Map<string, number>; connectedAccounts: ConnectedFinanceAccount[]; connectedTransactions: ConnectedFinanceTransaction[]; connectedLoading: boolean; onSelectConnectedAccount?: (account: UnifiedFinanceAccount) => void }) {
  const hidden = data.hideBalances; const [now] = useState(() => new Date()); const [period, setPeriod] = useState<Period>("30D"); const [showNetWorthDetail, setShowNetWorthDetail] = useState(false);
  const unifiedAccounts = useMemo(() => mergeFinanceAccounts(accounts, connectedAccounts, balances), [accounts, connectedAccounts, balances]);
  const unified = useMemo(() => mergeFinanceTransactions(data.transactions, connectedTransactions, data.categories), [data.transactions, connectedTransactions, data.categories]);
  const accountTotals = getUnifiedAccountTotals(unifiedAccounts); const month = getUnifiedMonthTotals(unified, now); const prior = getUnifiedMonthTotals(unified, new Date(now.getFullYear(), now.getMonth() - 1, 15)); const categories = getUnifiedCategoryTotals(unified, now);
  const upcoming = getUpcomingRecurringItems(data.recurringItems, now, 30).slice(0, 4); const attention = getFinanceAttention(data, balances, now).slice(0, 4); const chart = buildChart(unified, period, now);
  const assetAccounts = unifiedAccounts.filter((account) => account.type !== "credit" && account.currentBalanceMinor > 0 && (account.source === "manual" || account.isLive)); const assetTotal = assetAccounts.reduce((sum, account) => sum + account.currentBalanceMinor, 0); const topCategories = [...categories.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5);
  const budgetRows = data.budgets.filter((budget) => budget.active).map((budget) => ({ budget, spent: categories.get(budget.categoryId) ?? 0, name: data.categories.find((category) => category.id === budget.categoryId)?.name ?? "Category" })).slice(0, 5); const categoryName = (id: string) => data.categories.find((category) => category.id === id)?.name ?? "Other"; const afterBills = accountTotals.availableCashMinor + upcoming.reduce((sum, item) => sum + (item.direction === "income" || (item.direction === "transfer" && item.transferEffect === "in") ? item.amountMinor : -item.amountMinor), 0);

  return <section aria-labelledby="finance-overview-heading" className="space-y-5">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className={label}>Mission control · personal capital</p><h2 id="finance-overview-heading" className="mt-1 text-2xl font-semibold tracking-[0.08em] text-white/90">FINANCIAL OVERVIEW</h2></div><p className="text-[11px] uppercase tracking-[0.16em] text-white/30">{now.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })} · {unified.length} records</p></div>
    <section className="relative overflow-hidden rounded-[1.6rem] border border-violet-200/25 bg-[radial-gradient(circle_at_83%_45%,rgba(83,48,206,.24),transparent_32%),linear-gradient(120deg,rgba(7,13,42,.98),rgba(5,7,25,.94))] p-6 shadow-[0_0_70px_rgba(69,43,214,.15)] sm:p-8" aria-label="Finance hero"><div className="pointer-events-none absolute -right-16 -top-16 h-64 w-64 rounded-full border border-violet-200/15 opacity-70 shadow-[0_0_60px_rgba(70,67,255,.17)] sm:h-80 sm:w-80"><div className="absolute inset-7 rounded-full border border-cyan-200/15"/><div className="absolute inset-16 rounded-full border border-violet-200/20"/><div className="absolute left-1/2 top-1/2 h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full bg-cyan-200 shadow-[0_0_25px_8px_rgba(88,219,255,.32)]"/></div><div className="relative max-w-2xl"><p className={label}>Net worth · current position</p><p className="mt-3 break-words text-[clamp(2.8rem,8vw,5.7rem)] font-light leading-none tracking-[-0.06em] text-white">{formatMoney(accountTotals.netWorthMinor, hidden)}</p><div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-xs uppercase tracking-[0.16em]"><span className="text-emerald-200/75">Assets {formatMoney(accountTotals.assetsMinor, hidden)}</span><span className="text-rose-200/70">Debt {formatMoney(accountTotals.liabilitiesMinor, hidden)}</span><span className="text-white/35">No fabricated performance change</span></div></div></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Available cash" value={formatMoney(accountTotals.availableCashMinor, hidden)} detail="Checking · savings · cash"/><Metric label="Checking" value={formatMoney(sumType(unifiedAccounts, "checking"), hidden)} detail="Current balance"/><Metric label="Savings" value={formatMoney(sumType(unifiedAccounts, "savings"), hidden)} detail="Current balance"/><Metric label="Credit / debt" value={formatMoney(accountTotals.liabilitiesMinor, hidden)} detail="Liabilities" tone="debt"/><Metric label="Net this month" value={formatMoney(month.netMinor, hidden)} detail={`${formatMoney(month.incomeMinor, hidden)} in · ${formatMoney(month.expenseMinor, hidden)} out`} tone={month.netMinor >= 0 ? "positive" : "negative"}/></div>
    <div className="grid gap-5 xl:grid-cols-[1.38fr_.82fr]"><section className={card} aria-labelledby="finance-chart-heading"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className={label}>Live record series</p><h3 id="finance-chart-heading" className="mt-1 text-lg font-medium tracking-[0.06em] text-white/88">CASH FLOW</h3><p className={`mt-1 text-xs ${muted}`}>Daily net movement from available records.</p></div><div className="flex flex-wrap gap-1" role="group" aria-label="Chart period">{(["7D", "30D", "90D", "1Y", "ALL"] as Period[]).map((value) => <button type="button" key={value} disabled={!chart.enabledPeriods.includes(value)} onClick={() => setPeriod(value)} className={`rounded-lg border px-2.5 py-1.5 text-[10px] font-semibold tracking-[0.16em] transition focus:outline-none focus:ring-2 focus:ring-cyan-200/50 disabled:cursor-not-allowed disabled:opacity-25 ${period === value ? "border-violet-200/60 bg-violet-400/15 text-violet-100" : "border-white/10 text-white/45 hover:border-cyan-200/30 hover:text-white/75"}`}>{value}</button>)}</div></div><div className="mt-5">{chart.points.length > 1 ? <Chart points={chart.points} hidden={hidden}/> : <div className="flex h-48 items-center justify-center rounded-xl border border-dashed border-white/10 text-sm text-white/38">Add more dated activity to reveal a cash-flow trajectory.</div>}</div><div className="mt-3 flex justify-between text-[10px] uppercase tracking-[0.15em] text-white/28"><span>{chart.startLabel}</span><span>{chart.endLabel}</span></div></section><AllocationCard accounts={assetAccounts} total={assetTotal} hidden={hidden}/></div>
    <div className="grid gap-5 xl:grid-cols-2"><AccountsCard accounts={unifiedAccounts} hidden={hidden} loading={connectedLoading} onSelect={onSelectConnectedAccount}/><UpcomingCard items={upcoming} afterBills={afterBills} hidden={hidden}/></div>
    <div className="grid gap-5 xl:grid-cols-2"><SpendingCard categories={topCategories} total={month.expenseMinor} prior={prior.expenseMinor} categoryName={categoryName} hidden={hidden}/><BudgetCard rows={budgetRows} hidden={hidden}/></div>
    <div className="grid gap-5 xl:grid-cols-2"><section className={card} aria-labelledby="finance-attention-heading"><div className="flex items-center justify-between gap-3"><div><p className={label}>Telemetry</p><h3 id="finance-attention-heading" className="mt-1 text-lg font-medium tracking-[0.06em] text-white/88">NEEDS ATTENTION</h3></div><span className="rounded-full border border-violet-200/25 px-2 py-1 text-[10px] text-violet-100/70">{attention.length} SIGNALS</span></div><div className="mt-4 space-y-2">{attention.map((item) => <div key={item.id} className="flex gap-3 rounded-xl border border-white/8 bg-black/20 p-3"><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${item.tone === "critical" ? "bg-rose-300 shadow-[0_0_12px_rgba(251,113,133,.8)]" : item.tone === "attention" ? "bg-amber-200 shadow-[0_0_12px_rgba(253,224,71,.6)]" : "bg-cyan-200 shadow-[0_0_12px_rgba(103,232,249,.7)]"}`} aria-hidden="true"/><div><p className="text-sm text-white/75">{item.title}</p><p className={`mt-1 text-xs ${muted}`}>{item.detail}</p></div></div>)}{!attention.length ? <p className="rounded-xl border border-dashed border-white/10 p-4 text-sm text-white/40">All available Finance signals are stable.</p> : null}</div></section><section className={card} aria-labelledby="finance-category-heading"><p className={label}>Current cycle</p><h3 id="finance-category-heading" className="mt-1 text-lg font-medium tracking-[0.06em] text-white/88">SPENDING CATEGORIES</h3><div className="mt-4 space-y-3">{topCategories.map(([categoryId, amount]) => <div key={categoryId}><div className="flex justify-between gap-3 text-sm"><span className="text-white/65">{categoryName(categoryId)}</span><span className="text-white/78">{formatMoney(amount, hidden)}</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-gradient-to-r from-violet-400 to-cyan-300" style={{ width: `${Math.min(100, month.expenseMinor ? amount / month.expenseMinor * 100 : 0)}%` }}/></div></div>)}{!topCategories.length ? <p className="text-sm text-white/40">Recorded expenses will appear here.</p> : null}</div></section></div>
    {showNetWorthDetail ? <section className={`${card} border-violet-200/25`} aria-label="Net worth detail"><div className="flex items-center justify-between gap-3"><div><p className={label}>Balance composition</p><h3 className="mt-1 text-lg font-medium text-white/88">NET WORTH DETAIL</h3></div><button type="button" onClick={() => setShowNetWorthDetail(false)} className="text-xs text-cyan-100/70 underline focus:outline-none focus:ring-2 focus:ring-cyan-200/50">Close</button></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><p className="text-xs uppercase tracking-[0.16em] text-emerald-200/65">Assets · {formatMoney(accountTotals.assetsMinor, hidden)}</p>{assetAccounts.map((account) => <div key={account.id} className="mt-2 flex justify-between gap-3 text-sm"><span className="text-white/58">{account.name}</span><span className="text-white/78">{formatMoney(account.currentBalanceMinor, hidden)}</span></div>)}</div><div><p className="text-xs uppercase tracking-[0.16em] text-rose-200/65">Liabilities · {formatMoney(accountTotals.liabilitiesMinor, hidden)}</p>{unifiedAccounts.filter((account) => account.type === "credit" && (account.source === "manual" || account.isLive)).map((account) => <div key={account.id} className="mt-2 flex justify-between gap-3 text-sm"><span className="text-white/58">{account.name}</span><span className="text-white/78">{formatMoney(Math.abs(account.currentBalanceMinor), hidden)}</span></div>)}</div></div></section> : <button type="button" onClick={() => setShowNetWorthDetail(true)} className="w-fit text-xs uppercase tracking-[0.16em] text-cyan-100/55 underline decoration-cyan-100/25 underline-offset-4 hover:text-cyan-100 focus:outline-none focus:ring-2 focus:ring-cyan-200/50">View net worth composition</button>}
  </section>;
}

function Metric({ label: metricLabel, value, detail, tone }: { label: string; value: string; detail: string; tone?: "positive" | "negative" | "debt" }) { return <article className="rounded-xl border border-white/10 bg-black/20 p-4"><p className={label}>{metricLabel}</p><p className={`mt-2 text-xl font-light tracking-tight ${tone === "positive" ? "text-emerald-200/85" : tone === "negative" || tone === "debt" ? "text-rose-200/80" : "text-white/88"}`}>{value}</p><p className={`mt-1 text-[11px] ${muted}`}>{detail}</p></article>; }

function AllocationCard({ accounts, total, hidden }: { accounts: UnifiedFinanceAccount[]; total: number; hidden: boolean }) { const colors = ["#7c5cff", "#277cff", "#22d3ee", "#64748b"]; const slices = accounts.slice(0, 4).reduce<Array<{ account: UnifiedFinanceAccount; percent: number; slice: string }>>((result, account, index) => { const percent = total ? account.currentBalanceMinor / total * 100 : 0; const running = result.reduce((sum, item) => sum + item.percent, 0); result.push({ account, percent, slice: `${colors[index]} ${running}% ${running + percent}%` }); return result; }, []); const gradient = slices.length ? `conic-gradient(${slices.map((item) => item.slice).join(",")})` : "conic-gradient(#172554 0 100%)"; return <section className={card} aria-labelledby="finance-allocation-heading"><p className={label}>Assets only · liabilities excluded</p><h3 id="finance-allocation-heading" className="mt-1 text-lg font-medium tracking-[0.06em] text-white/88">CASH ALLOCATION</h3><div className="mt-5 flex flex-col items-center gap-5 sm:flex-row sm:items-center"><div className="relative grid h-40 w-40 shrink-0 place-items-center rounded-full" style={{ background: gradient }}><div className="grid h-24 w-24 place-items-center rounded-full border border-white/10 bg-[#070b24] text-center"><span className="text-[9px] uppercase tracking-[0.14em] text-white/35">Assets</span><span className="text-sm text-white/80">{formatMoney(total, hidden)}</span></div></div><div className="min-w-0 flex-1 space-y-3">{slices.map(({ account, percent }, index) => <div key={account.id} className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-sm" style={{ backgroundColor: colors[index] }}/><span className="min-w-0 flex-1 truncate text-xs uppercase tracking-[0.1em] text-white/55">{account.name}</span><span className="text-xs text-white/75">{percent.toFixed(0)}%</span></div>)}{!slices.length ? <p className="text-sm text-white/40">Asset accounts will appear here.</p> : null}</div></div></section>; }

function AccountsCard({ accounts, hidden, loading, onSelect }: { accounts: UnifiedFinanceAccount[]; hidden: boolean; loading: boolean; onSelect?: (account: UnifiedFinanceAccount) => void }) { return <section id="finance-accounts" className={card} aria-labelledby="finance-accounts-heading"><div className="flex items-center justify-between gap-3"><div><p className={label}>Connected surfaces</p><h3 id="finance-accounts-heading" className="mt-1 text-lg font-medium tracking-[0.06em] text-white/88">ACCOUNTS</h3></div>{loading ? <span className="text-[10px] uppercase tracking-[0.16em] text-white/35">Syncing</span> : null}</div><div className="mt-4 divide-y divide-white/8">{accounts.slice(0, 6).map((account) => { const row = <div className="flex items-center gap-3 py-3"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full border text-xs ${account.type === "credit" ? "border-rose-200/25 text-rose-200/75" : "border-cyan-200/25 text-cyan-200/75"}`}>{account.type === "credit" ? "−" : "＋"}</span><div className="min-w-0 flex-1"><p className="truncate text-sm text-white/75">{account.name}</p><p className="truncate text-[10px] uppercase tracking-[0.12em] text-white/35">{account.institution ?? (account.source === "manual" ? "Manual account" : "Connected account")}{account.maskedIdentifier ? ` · ••••${account.maskedIdentifier}` : ""} · {account.source}</p></div><div className="text-right"><p className={`text-sm ${account.type === "credit" ? "text-rose-200/80" : "text-white/82"}`}>{account.type === "credit" ? `${formatMoney(Math.abs(account.currentBalanceMinor), hidden)} owed` : formatMoney(account.currentBalanceMinor, hidden)}</p><p className="text-[10px] text-white/30">{account.source === "connected" ? account.isLive ? "Connected" : "Reconnect" : "Local"}</p></div></div>; return account.source === "connected" ? <button type="button" key={account.id} onClick={() => onSelect?.(account)} className="block w-full text-left transition hover:bg-white/[.03] focus:outline-none focus:ring-2 focus:ring-inset focus:ring-cyan-200/40">{row}</button> : <div key={account.id}>{row}</div>; })}{!accounts.length ? <p className="py-5 text-sm text-white/40">Add an account or connect an institution to begin.</p> : null}</div></section>; }

function UpcomingCard({ items, afterBills, hidden }: { items: ReturnType<typeof getUpcomingRecurringItems>; afterBills: number; hidden: boolean }) { return <section className={card} aria-labelledby="finance-upcoming-heading"><div className="flex items-center justify-between gap-3"><div><p className={label}>Known recurring activity</p><h3 id="finance-upcoming-heading" className="mt-1 text-lg font-medium tracking-[0.06em] text-white/88">UPCOMING MONEY</h3></div><span className="text-[10px] uppercase tracking-[0.12em] text-white/35">After bills {formatMoney(afterBills, hidden)}</span></div><div className="mt-4 space-y-2">{items.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-white/8 bg-black/20 p-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full border border-violet-200/25 text-violet-100/75">{item.direction === "income" ? "↑" : "↓"}</span><div className="min-w-0 flex-1"><p className="truncate text-sm text-white/72">{item.name}</p><p className="mt-1 text-[10px] uppercase tracking-[0.12em] text-white/35">{item.nextExpectedDate} · {item.direction === "income" ? "Expected income" : "Expected bill"}</p></div><span className={`shrink-0 text-sm ${item.direction === "income" ? "text-cyan-200/85" : "text-violet-200/80"}`}>{item.direction === "income" ? "+" : "−"}{formatMoney(item.amountMinor, hidden)}</span></div>)}{!items.length ? <p className="py-5 text-sm text-white/40">No known recurring items in the next 30 days.</p> : null}</div></section>; }

function SpendingCard({ categories, total, prior, categoryName, hidden }: { categories: Array<[string, number]>; total: number; prior: number; categoryName: (id: string) => string; hidden: boolean }) { const change = prior ? (total - prior) / prior * 100 : null; return <section className={card} aria-labelledby="finance-spending-heading"><div className="flex items-start justify-between gap-3"><div><p className={label}>Current cycle</p><h3 id="finance-spending-heading" className="mt-1 text-lg font-medium tracking-[0.06em] text-white/88">SPENDING</h3></div><div className="text-right"><p className="text-xl font-light text-white/85">{formatMoney(total, hidden)}</p><p className={`text-[10px] uppercase tracking-[0.12em] ${change === null ? muted : change > 0 ? "text-rose-200/70" : "text-emerald-200/70"}`}>{change === null ? "No prior baseline" : `${change > 0 ? "↑" : "↓"} ${Math.abs(change).toFixed(0)}% vs prior month`}</p></div></div><div className="mt-5 space-y-3">{categories.map(([id, amount]) => <div key={id}><div className="flex justify-between gap-3 text-sm"><span className="text-white/62">{categoryName(id)}</span><span className="text-white/75">{formatMoney(amount, hidden)}</span></div><div className="mt-1 h-1.5 rounded-full bg-white/8"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-300" style={{ width: `${Math.min(100, total ? amount / total * 100 : 0)}%` }}/></div></div>)}{!categories.length ? <p className="text-sm text-white/40">Spending categories will appear as activity arrives.</p> : null}</div></section>; }

function BudgetCard({ rows, hidden }: { rows: Array<{ budget: { id: string; monthlyLimitMinor: number }; spent: number; name: string }>; hidden: boolean }) { return <section className={card} aria-labelledby="finance-budget-heading"><p className={label}>Guardrails</p><h3 id="finance-budget-heading" className="mt-1 text-lg font-medium tracking-[0.06em] text-white/88">BUDGET STATUS</h3><div className="mt-5 space-y-4">{rows.map(({ budget, spent, name }) => { const ratio = budget.monthlyLimitMinor ? spent / budget.monthlyLimitMinor : 0; const status = ratio >= 1 ? "Over budget" : ratio >= .85 ? "Getting close" : "On track"; return <div key={budget.id}><div className="flex justify-between gap-3 text-sm"><span className="text-white/65">{name}</span><span className="text-white/75">{formatMoney(spent, hidden)} / {formatMoney(budget.monthlyLimitMinor, hidden)}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/8" role="progressbar" aria-label={`${name} budget`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100, ratio * 100)}><div className={`h-full rounded-full bg-gradient-to-r ${ratio >= 1 ? "from-rose-400 to-fuchsia-300" : ratio >= .85 ? "from-amber-300 to-violet-300" : "from-cyan-300 to-blue-400"}`} style={{ width: `${Math.min(100, ratio * 100)}%` }}/></div><p className="mt-1 text-[10px] uppercase tracking-[0.14em] text-white/35">{status} · {Math.round(ratio * 100)}%</p></div>; })}{!rows.length ? <p className="text-sm text-white/40">Create a budget to activate Finance guardrails.</p> : null}</div></section>; }

function Chart({ points, hidden }: { points: ChartPoint[]; hidden: boolean }) { const width = 720; const height = 220; const values = points.map((point) => point.value); const min = Math.min(...values, 0); const max = Math.max(...values, 1); const range = max - min || 1; const coords = points.map((point, index) => ({ ...point, x: index / Math.max(1, points.length - 1) * width, y: height - 20 - (point.value - min) / range * (height - 40) })); const line = coords.map((point, index) => `${index ? "L" : "M"}${point.x.toFixed(1)} ${point.y.toFixed(1)}`).join(" "); const area = `${line} L ${width} ${height} L 0 ${height} Z`; return <svg viewBox={`0 0 ${width} ${height}`} className="h-48 w-full overflow-visible" role="img" aria-label="Cash flow chart"><defs><linearGradient id="finance-area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#7c5cff" stopOpacity=".34"/><stop offset="1" stopColor="#22d3ee" stopOpacity="0"/></linearGradient><linearGradient id="finance-line" x1="0" x2="1"><stop stopColor="#22d3ee"/><stop offset=".55" stopColor="#7c5cff"/><stop offset="1" stopColor="#e879f9"/></linearGradient></defs>{[.25, .5, .75].map((ratio) => <line key={ratio} x1="0" x2={width} y1={height * ratio} y2={height * ratio} stroke="rgba(125,160,255,.12)" strokeDasharray="2 8"/>)}<path d={area} fill="url(#finance-area)"/><path d={line} fill="none" stroke="url(#finance-line)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>{coords.map((point) => <circle key={point.date} cx={point.x} cy={point.y} r="3.5" fill="#08102f" stroke="#a5f3fc" strokeWidth="1.5"><title>{point.date}: {formatMoney(point.value, hidden)}</title></circle>)}</svg>; }

type ChartPoint = { date: string; value: number };
function buildChart(transactions: ReturnType<typeof mergeFinanceTransactions>, period: Period, now: Date) { const days = period === "7D" ? 7 : period === "30D" ? 30 : period === "90D" ? 90 : period === "1Y" ? 365 : 0; const dates = transactions.map((item) => item.date).filter(Boolean).sort(); const earliest = dates[0]; const start = days ? new Date(now.getFullYear(), now.getMonth(), now.getDate() - days + 1) : earliest ? new Date(`${earliest}T12:00:00`) : now; const end = new Date(now.getFullYear(), now.getMonth(), now.getDate()); const filtered = transactions.filter((item) => { const time = new Date(`${item.date}T12:00:00`).getTime(); return time >= start.getTime() && time <= end.getTime() && item.direction !== "transfer"; }); const byDate = new Map<string, number>(); filtered.forEach((item) => { const delta = item.direction === "income" ? item.amountMinor : -item.amountMinor; byDate.set(item.date, (byDate.get(item.date) ?? 0) + delta); }); const points = [...byDate.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([date, value]) => ({ date, value })); const enabledPeriods: Period[] = ["ALL"]; if (dates.length) { const span = now.getTime() - new Date(`${earliest}T12:00:00`).getTime(); if (span >= 0) enabledPeriods.push("1Y"); if (span >= 90 * 86400000) enabledPeriods.push("90D"); if (span >= 30 * 86400000) enabledPeriods.push("30D"); if (span >= 7 * 86400000) enabledPeriods.push("7D"); } return { points, enabledPeriods, startLabel: points[0]?.date ?? "Awaiting records", endLabel: points.at(-1)?.date ?? "No series yet" }; }
function sumType(accounts: UnifiedFinanceAccount[], type: UnifiedFinanceAccount["type"]) { return accounts.filter((account) => account.type === type && (account.source === "manual" || account.isLive)).reduce((sum, account) => sum + account.currentBalanceMinor, 0); }
