"use client";

import type { SportsEvent } from "@/core/contracts/Sports";
import type { FootballLiveData } from "@/core/contracts/sports/Football";
import type { CollegeFootballLiveData } from "@/services/sports/providers/college-football-detail";
import { resolveSportsTeamIdentity } from "@/services/sports/identity";
import { createFootballPresentation } from "./footballPresentation";
import KioskFootballContextCards from "./KioskFootballContextCards";

type FootballView = ReturnType<typeof createFootballPresentation>;

export default function KioskFootballView({ event, live }: { event: SportsEvent; live?: FootballLiveData | CollegeFootballLiveData }) {
  const view = createFootballPresentation(event, live);
  const tone = view.attention === "flag" ? "border-amber-200/60 bg-amber-200/[0.08] shadow-[0_0_90px_rgba(251,191,36,.18)]" : view.attention !== "normal" ? "border-red-300/60 bg-red-950/[0.12] shadow-[0_0_90px_rgba(248,113,113,.18)]" : "border-white/20 bg-slate-950/35";
  const possessionText = view.situation?.possessionText ?? view.situation?.possessionTeamAbbreviation;
  return <div className={`kiosk-sports-view relative flex h-[100dvh] w-full items-center justify-center overflow-hidden px-[clamp(1rem,3vw,3rem)] py-[clamp(1rem,3vh,2.5rem)] ${view.attention !== "normal" ? (view.attention === "flag" ? "bg-amber-300/[0.04]" : "bg-red-500/[0.05]") : ""}`}>
    <section className={`relative flex h-full w-full max-w-[1550px] flex-col overflow-hidden rounded-[clamp(1.5rem,3vw,2.75rem)] border backdrop-blur-md transition-colors duration-500 ${tone}`}>
      <header className="flex shrink-0 items-start justify-between border-b border-white/10 px-[clamp(1.25rem,3vw,2.5rem)] py-[clamp(.9rem,2vh,1.4rem)]"><div className="flex items-center gap-4"><span className={`mt-1 h-3 w-3 rounded-full shadow-[0_0_18px_currentColor] ${view.attention === "flag" ? "bg-amber-300 text-amber-300" : view.attention !== "normal" ? "bg-red-300 text-red-300" : "bg-red-400 text-red-400"}`} /><div><p className="text-[clamp(.7rem,1vw,.9rem)] font-bold uppercase tracking-[0.24em] text-white/90">{view.statusLabel} · {view.sportLabel}</p><h1 className="mt-1 max-w-[75vw] text-[clamp(1.15rem,2vw,1.7rem)] font-semibold tracking-tight text-white">{event.title}</h1></div></div><p className="text-right text-[clamp(.65rem,1vw,.85rem)] font-semibold uppercase tracking-[0.2em] text-white/70">COSMIC SPORTS</p></header>
      {view.attention !== "normal" ? <AttentionBanner view={view} /> : null}
      <div className="grid min-h-0 flex-1 grid-rows-[auto_1fr_auto] gap-[clamp(.8rem,2vh,1.5rem)] px-[clamp(1.25rem,4vw,4rem)] py-[clamp(1rem,3vh,2rem)]"><div className="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-center"><span className="text-[clamp(1rem,1.8vw,1.45rem)] font-black uppercase tracking-[.12em] text-white">{view.countdownLabel ?? (view.quarterLabel ? `${view.quarterLabel}${view.clock ? ` · ${view.clock}` : ""}` : view.lifecycleState === "pregame" ? "PREGAME" : view.lifecycleState === "halftime" ? "HALFTIME" : view.lifecycleState === "overtime" ? "OVERTIME" : "GAME CONTEXT")}</span>{view.rankings.map((rank) => <span key={rank} className="text-[clamp(.85rem,1.2vw,1.05rem)] font-bold text-amber-100">{rank}</span>)}</div>
        <div className="grid min-h-0 grid-cols-[1fr_auto_1fr] items-center gap-[clamp(1rem,4vw,4rem)]"><ScoreTeam event={event} side="away" team={view.away} /><CenterSituation view={view} possessionText={possessionText} /><ScoreTeam event={event} side="home" team={view.home} /></div>
        <div className="grid gap-3 lg:grid-cols-[1fr_1.8fr_1fr]"><InfoCard label="LAST PLAY" value={view.latestPlay?.shortDescription ?? view.latestPlay?.description ?? "No play-by-play yet"} /><KioskFootballContextCards stats={view.stats} currentDrive={view.currentDrive} away={view.away} home={view.home} lifecycleState={view.lifecycleState} attention={view.attention} /><InfoCard label="VENUE / NETWORK" value={[view.venue, view.broadcast].filter(Boolean).join(" · ") || view.penaltyText || view.reviewText || "Live detail updating"} emphasis={view.attention !== "normal"} /></div>
      </div>
      <footer className="flex shrink-0 items-center justify-between border-t border-white/10 px-[clamp(1.25rem,3vw,2.5rem)] py-3 text-[clamp(.6rem,1vw,.75rem)] font-semibold uppercase tracking-[0.16em] text-white/65"><span>{view.venue ?? "Football live center"}</span><span>{view.away.timeouts !== undefined || view.home.timeouts !== undefined ? `Timeouts ${view.away.timeouts ?? "—"} · ${view.home.timeouts ?? "—"}` : "Scoreboard updating"}</span></footer><div className="pointer-events-none absolute inset-0 rounded-[inherit] ring-1 ring-inset ring-white/10" />
    </section>
  </div>;
}

function AttentionBanner({ view }: { view: FootballView }) { return <div className="border-b border-current/20 px-[clamp(1.25rem,4vw,4rem)] py-3 text-center"><p className={`text-[clamp(1.1rem,2.4vw,2rem)] font-black uppercase tracking-[.2em] ${view.attention === "flag" ? "text-amber-100" : "text-red-100"}`}>{view.attentionLabel}</p>{view.attention === "challenge" && view.attentionTeam ? <p className="mt-1 text-[clamp(.8rem,1.2vw,1rem)] font-semibold uppercase tracking-[.14em] text-red-100/90">Challenge by {view.attentionTeam}</p> : null}{view.attention === "official-review" ? <p className="mt-1 text-[clamp(.8rem,1.2vw,1rem)] font-semibold text-red-100/90">Ruling on the field under review</p> : null}{view.reviewOutcome ? <p className="mt-1 text-[clamp(.8rem,1.2vw,1rem)] font-bold text-white">{view.reviewOutcome}</p> : null}</div>; }

function CenterSituation({ view, possessionText }: { view: FootballView; possessionText?: string }) { const situation = view.situation; return <div className="flex min-w-[clamp(7rem,16vw,13rem)] flex-col items-center gap-3 text-center"><p className="text-[clamp(1.5rem,3vw,2.8rem)] font-black leading-none text-white">{situation?.clock ?? "—"}</p><p className="text-[clamp(.8rem,1.1vw,1rem)] font-bold uppercase tracking-[.16em] text-white/80">{view.quarterLabel ?? "GAME"}</p><p className="text-[clamp(1rem,1.8vw,1.5rem)] font-black uppercase tracking-[.08em] text-white">{situation?.downDistanceText ?? "VS"}</p><FieldStrip view={view} possessionText={possessionText} /></div>; }

function FieldStrip({ view, possessionText }: { view: FootballView; possessionText?: string }) { const field = view.situation?.fieldPosition; const yard = field?.yardLine ?? view.situation?.ballYardLine; const first = view.situation?.firstDownYardLine; return <div className="w-full max-w-[19rem] rounded-xl border border-white/20 bg-emerald-950/55 p-2"><div className="flex justify-between text-[.55rem] font-black tracking-[.12em] text-white/80"><span>{view.away.abbreviation}</span><span>{view.home.abbreviation}</span></div><svg viewBox="0 0 220 30" className="mt-1 h-8 w-full" role="img" aria-label={possessionText ? `Field position ${possessionText}` : "Football field position"}><rect x="1" y="4" width="218" height="22" rx="3" fill="rgba(16,94,62,.75)" stroke="rgba(255,255,255,.35)" />{[22,44,66,88,110,132,154,176,198].map((x) => <line key={x} x1={x} x2={x} y1="5" y2="25" stroke="rgba(255,255,255,.28)" />)}{first !== undefined ? <line x1={Math.max(4, Math.min(216, first * 2.2))} x2={Math.max(4, Math.min(216, first * 2.2))} y1="5" y2="25" stroke="#facc15" strokeWidth="2" /> : null}{yard !== undefined ? <circle cx={Math.max(7, Math.min(213, yard * 2.2))} cy="15" r="4" fill="#fff" stroke="#111827" strokeWidth="2" /> : null}</svg><p className="mt-1 text-[.65rem] font-semibold text-white/80">{possessionText ? `🏈 ${possessionText}` : "Field position unavailable"}</p></div>; }

function ScoreTeam({ event, side, team }: { event: SportsEvent; side: "home" | "away"; team: FootballView["home"] }) { const source = side === "home" ? event.homeTeam : event.awayTeam; const identity = resolveSportsTeamIdentity(event.sport, source); return <div className={`${side === "home" ? "text-left" : "text-right"} min-w-0`}><div className={`mb-2 flex items-center gap-3 ${side === "home" ? "justify-start" : "justify-end"}`}><div className="rounded-full bg-white/90 p-1 shadow-lg">{identity?.logoPath ? <img className="h-10 w-10 object-contain" src={identity.logoPath} alt="" draggable={false} /> : <span className="block h-10 w-10" />}</div><div className="min-w-0"><p className="truncate text-[clamp(1.2rem,3vw,2.6rem)] font-black uppercase tracking-[-.035em]" style={{ color: team.possession && team.color ? team.color : "#fff" }}>{team.name}</p><p className="text-[clamp(.7rem,1vw,.9rem)] font-bold uppercase tracking-[.15em] text-white/75">{team.abbreviation}{team.record ? ` · ${team.record}` : ""}</p><Timeouts count={team.timeouts} /></div></div><p className="text-[clamp(4rem,11vw,8rem)] font-black leading-none tracking-[-.08em] text-white drop-shadow-[0_4px_18px_rgba(0,0,0,.7)]">{team.score}</p></div>; }
function Timeouts({ count }: { count?: number }) { if (count === undefined) return null; return <div className="mt-1 flex gap-1" aria-label={`${count} timeouts remaining`}>{[0, 1, 2].map((index) => <span key={index} className={`h-2.5 w-2.5 rounded-full border ${index < count ? "border-white/80 bg-white/85" : "border-white/35 bg-white/10"}`} />)}</div>; }
function InfoCard({ label, value, emphasis = false }: { label: string; value: string; emphasis?: boolean }) { return <div className={`rounded-2xl border px-4 py-3 ${emphasis ? "border-amber-200/40 bg-amber-300/15" : "border-white/15 bg-black/25"}`}><p className="text-[clamp(.65rem,1vw,.8rem)] font-black uppercase tracking-[.18em] text-white/80">{label}</p><p className="mt-1 line-clamp-2 text-[clamp(.85rem,1.2vw,1.05rem)] font-medium leading-snug text-white">{value}</p></div>; }
