"use client";
import type { SportsEvent } from "@/core/contracts/Sports";
import type { FootballLiveData } from "@/core/contracts/sports/Football";
import type { CollegeFootballLiveData } from "@/services/sports/providers/college-football-detail";
import { resolveSportsTeamIdentity } from "@/services/sports/identity";
import { createFootballPresentation } from "./footballPresentation";

export default function KioskFootballView({ event, live }: { event: SportsEvent; live?: FootballLiveData | CollegeFootballLiveData }) {
  const view = createFootballPresentation(event, live); const possession = view.situation?.possessionText ?? view.situation?.possessionTeamAbbreviation; const ball = view.situation?.fieldPosition?.display ?? possession;
  return <div className="kiosk-sports-view relative flex h-[100dvh] w-full items-center justify-center overflow-hidden px-[clamp(1rem,3vw,3rem)] py-[clamp(1rem,3vh,2.5rem)]"><section className="relative flex h-full w-full max-w-[1500px] flex-col overflow-hidden rounded-[clamp(1.5rem,3vw,2.75rem)] border border-white/15 bg-slate-950/35 shadow-[0_30px_120px_rgba(0,0,0,.32)] backdrop-blur-md">
    <header className="flex shrink-0 items-center justify-between border-b border-white/10 px-[clamp(1.25rem,3vw,2.5rem)] py-[clamp(.9rem,2vh,1.4rem)]"><div className="flex items-center gap-4"><span className="h-3 w-3 rounded-full bg-red-400 shadow-[0_0_18px_rgba(248,113,113,.9)]" /><div><p className="text-[clamp(.7rem,1vw,.9rem)] font-bold uppercase tracking-[0.24em] text-red-100/90">{view.statusLabel} · {view.sportLabel}</p><h1 className="text-[clamp(1.15rem,2vw,1.7rem)] font-semibold tracking-tight text-white">{event.title}</h1></div></div><p className="text-right text-[clamp(.65rem,1vw,.85rem)] font-semibold uppercase tracking-[0.2em] text-white/60">Cosmic Sports</p></header>
    <div className="grid min-h-0 flex-1 grid-rows-[auto_1fr_auto] gap-5 px-[clamp(1.25rem,4vw,4rem)] py-[clamp(1rem,3vh,2rem)]"><div className="flex flex-wrap items-center justify-center gap-x-5 gap-y-2 text-center text-[clamp(.9rem,1.5vw,1.25rem)] font-bold uppercase tracking-[.12em] text-white/90">{view.quarterLabel ? <span>{view.quarterLabel}{view.clock ? ` · ${view.clock}` : ""}</span> : null}{view.rankings.map((rank) => <span key={rank} className="text-amber-100">{rank}</span>)}{view.reviewText ? <span className="rounded-full bg-amber-300/20 px-3 py-1 text-amber-100">{view.reviewText}</span> : null}</div>
      <div className="grid min-h-0 grid-cols-[1fr_auto_1fr] items-center gap-[clamp(1rem,5vw,5rem)]"><ScoreTeam event={event} side="away" team={view.away} /><div className="flex flex-col items-center gap-4 text-center"><span className="text-[clamp(.8rem,1vw,1rem)] font-black uppercase tracking-[.22em] text-white/75">{view.situation?.downDistanceText ?? "VS"}</span><span className="text-[clamp(.8rem,1.2vw,1.1rem)] font-semibold uppercase tracking-[.15em] text-emerald-100/90">{possession ? `🏈 ${possession}` : "FOOTBALL"}</span><span className="text-[clamp(.75rem,1vw,.95rem)] font-semibold text-white/70">{ball ? `Ball on ${ball}` : "Awaiting drive data"}</span></div><ScoreTeam event={event} side="home" team={view.home} /></div>
      <div className="grid gap-3 md:grid-cols-3"><InfoCard label="LAST PLAY" value={view.latestPlay?.shortDescription ?? view.latestPlay?.description ?? "No play-by-play yet"} /><InfoCard label="CURRENT DRIVE" value={view.driveLabel ?? "Drive data unavailable"} /><InfoCard label={view.penaltyText ? "PENALTY" : "GAME STATUS"} value={view.penaltyText ?? (view.venue ?? "Live detail updating")} emphasis={Boolean(view.penaltyText)} /></div></div>
    <footer className="flex shrink-0 items-center justify-between border-t border-white/10 px-[clamp(1.25rem,3vw,2.5rem)] py-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-white/55"><span>Live football detail</span><span>{view.away.timeouts !== undefined || view.home.timeouts !== undefined ? `Timeouts ${view.away.timeouts ?? "—"} · ${view.home.timeouts ?? "—"}` : "Scoreboard updating"}</span></footer><div className="pointer-events-none absolute inset-0 rounded-[inherit] ring-1 ring-inset ring-white/10" /></section></div>;
}
function ScoreTeam({ event, side, team }: { event: SportsEvent; side: "home" | "away"; team: ReturnType<typeof createFootballPresentation>["home"] }) { const source = side === "home" ? event.homeTeam : event.awayTeam; const identity = resolveSportsTeamIdentity(event.sport, source); return <div className={`${side === "home" ? "text-left" : "text-right"} min-w-0`}><div className="mb-2 flex items-center gap-3"><div className="rounded-full bg-white/90 p-1 shadow-lg">{identity?.logoPath ? <img className="h-10 w-10 object-contain" src={identity.logoPath} alt="" draggable={false} /> : <span className="block h-10 w-10" />}</div><div className="min-w-0"><p className="truncate text-[clamp(1.2rem,3vw,2.6rem)] font-black uppercase tracking-[-.035em] text-white">{team.name}</p><p className="text-[clamp(.7rem,1vw,.9rem)] font-bold uppercase tracking-[.15em] text-white/75">{team.abbreviation}{team.record ? ` · ${team.record}` : ""}{team.possession ? " · POSSESSION" : ""}</p></div></div><p className="text-[clamp(4rem,11vw,8rem)] font-black leading-none tracking-[-.08em] text-white drop-shadow-[0_4px_18px_rgba(0,0,0,.7)]">{team.score}</p></div>; }
function InfoCard({ label, value, emphasis = false }: { label: string; value: string; emphasis?: boolean }) { return <div className={`rounded-2xl border px-4 py-3 ${emphasis ? "border-amber-200/40 bg-amber-300/15" : "border-white/15 bg-black/25"}`}><p className="text-[clamp(.65rem,1vw,.8rem)] font-black uppercase tracking-[.18em] text-white/75">{label}</p><p className="mt-1 line-clamp-2 text-[clamp(.85rem,1.2vw,1.05rem)] font-medium leading-snug text-white">{value}</p></div>; }
