"use client";

import { Bell, Cloud, Database, Gauge, Globe2, HardDrive, Laptop, Monitor, Moon, RefreshCw, ShieldCheck, SlidersHorizontal, Smartphone, Wifi, Zap } from "lucide-react";
import { useClockTick } from "@/hooks/os/useClock";
import { useDeveloperKioskData } from "@/hooks/os/useDeveloperKioskData";
import useWeather from "@/hooks/os/useWeather";
import { useSystem } from "@/hooks/os/useSystem";
import { useKioskUpdateStatus } from "@/hooks/os/useKioskUpdateStatus";
import { formatBytes } from "@/services/system/browser";

export default function CosmosSystemKioskScene(){
 const now=useClockTick(1000);const d=now?new Date(now):new Date();const kiosk=useDeveloperKioskData();const weather=useWeather();const {snapshot}=useSystem();const update=useKioskUpdateStatus();
 const used=snapshot.storage.usageBytes,quota=snapshot.storage.quotaBytes,pct=used!==undefined&&quota?Math.min(100,Math.round(used/quota*100)):null;
 const status=snapshot.network.online?"Connected":"Offline";
 const devices=[
  {icon:Laptop,name:"Cosmos",sub:update?("v"+update.currentVersion):snapshot.device.browser,state:update?.updateAvailable?"Update available":"Ready",ok:!update?.updateAvailable},
  {icon:Monitor,name:"Kiosk Display",sub:(snapshot.display.viewportWidth??"—")+" × "+(snapshot.display.viewportHeight??"—"),state:snapshot.visible?"Active":"Hidden",ok:snapshot.visible},
  {icon:Globe2,name:"Network",sub:snapshot.network.effectiveType??"Browser connection",state:status,ok:snapshot.network.online},
  {icon:Cloud,name:"Cosmos Data",sub:kiosk.error?"Data unavailable":"Kiosk services",state:kiosk.error?"Check connection":"Available",ok:!kiosk.error},
 ];
 const prefs=[{icon:Monitor,a:"Display",b:snapshot.display.profile+" · "+snapshot.display.orientation},{icon:Gauge,a:"Performance",b:snapshot.power.effective},{icon:Bell,a:"Notifications",b:String(snapshot.permissions.notifications)},{icon:Globe2,a:"Platform",b:snapshot.device.platform.replace(" (browser-reported)","")},{icon:ShieldCheck,a:"Privacy",b:"Permissions available"},{icon:SlidersHorizontal,a:"General",b:snapshot.install.mode}];
 return <section data-kiosk-rebuild="system" className="relative h-full w-full overflow-hidden bg-[#060a12] text-white" style={{height:"100dvh",maxHeight:"100dvh"}}>
  <div className="absolute inset-0 bg-[radial-gradient(circle_at_10%_20%,rgba(249,115,22,.30),transparent_25%),radial-gradient(circle_at_78%_12%,rgba(59,130,246,.31),transparent_31%),radial-gradient(circle_at_67%_80%,rgba(124,58,237,.24),transparent_34%),linear-gradient(135deg,#080b13,#07172b_48%,#150b24)]"/>
  <div className="relative z-10 box-border flex h-full min-h-0 flex-col px-[2.7vw] pt-[2.3vh] pb-[4.5vh]">
   <header className="flex h-[16vh] shrink-0 justify-between"><div><h1 className="text-[clamp(2.2rem,4.6vw,4.8rem)] font-light tracking-[.22em]">COSMOS</h1><p className="mt-1 text-center text-[clamp(.8rem,1.25vw,1.2rem)] tracking-[.55em] text-white/55">SYSTEM</p></div><div className="hidden"><div><p className="text-sm text-white/70">{d.toLocaleDateString([],{weekday:"short",month:"short",day:"numeric",year:"numeric"})}</p><p className="text-[clamp(2rem,4vw,4rem)] font-light">{d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</p></div><div className="border-l border-white/15 pl-[2vw]"><p className="text-[clamp(1.4rem,2.2vw,2.3rem)] font-semibold">{weather.weather?.temp!==undefined?Math.round(weather.weather.temp)+"°":"—"}</p><p className="text-sm text-white/70">{weather.weather?.condition??"Weather"}</p><p className="text-xs text-white/45">{kiosk.data?.location?.label??weather.weather?.city??""}</p></div></div></header>
   <div className="grid min-h-0 flex-1 grid-cols-[1.08fr_1.12fr_.72fr] grid-rows-[minmax(0,1fr)_minmax(0,.74fr)] gap-[1vw]">
    <Glass title="DEVICE STATUS"><div className="divide-y divide-white/10 rounded-xl bg-white/[.018] px-2">{devices.map(({icon:Icon,name,sub,state,ok})=><div key={name} className="flex items-center gap-3 py-[1.1vh]"><Icon className="h-6 w-6 text-sky-300"/><div className="min-w-0 flex-1"><p className="truncate text-sm">{name}</p><p className="truncate text-[clamp(10px,.68vw,11px)] text-white/52">{sub}</p></div><span className={"h-2 w-2 rounded-full "+(ok?"bg-emerald-400":"bg-amber-400")}/><span className="text-[11px] text-white/60">{state}</span></div>)}</div></Glass>
    <Glass title="PREFERENCES"><div className="grid h-[calc(100%-2rem)] grid-cols-3 grid-rows-2 gap-2">{prefs.map(({icon:Icon,a,b})=><div key={a} className="flex min-h-0 flex-col items-center justify-center rounded-xl border border-white/10 bg-white/[.035] px-2 text-center"><Icon className="h-6 w-6 text-sky-300"/><p className="mt-2 text-xs">{a}</p><p className="mt-1 max-w-full truncate text-[clamp(9px,.62vw,10px)] text-white/52">{b}</p></div>)}</div></Glass>
    <Glass title="STORAGE"><div className="flex h-[calc(100%-2rem)] flex-col"><div className="flex items-center gap-3"><HardDrive className="h-8 w-8 text-sky-300"/><div><p className="text-lg">{used!==undefined?formatBytes(used)+" used":"Estimate unavailable"}</p><p className="text-xs text-white/45">{quota!==undefined?"of "+formatBytes(quota):"Browser did not report storage"}</p></div></div><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-sky-400" style={{width:(pct??0)+"%"}}/></div><p className="mt-2 text-right text-sm">{pct!==null?pct+"%":"—"}</p><div className="mt-auto space-y-2 text-[clamp(10px,.7vw,12px)] text-white/60"><Row a="Local storage" b={snapshot.storage.localStorageAvailable?"Available":"Unavailable"}/><Row a="IndexedDB" b={snapshot.storage.indexedDBSupported?"Available":"Unavailable"}/><Row a="Persistent" b={snapshot.storage.persistent===undefined?"Unknown":snapshot.storage.persistent?"Yes":"No"}/></div></div></Glass>
    <Glass title="QUICK STATUS"><div className="grid h-[calc(100%-2rem)] grid-cols-4 gap-2">{[{icon:RefreshCw,a:"Updates",b:update?.updateAvailable?"Available":"Up to date"},{icon:Moon,a:"Power",b:snapshot.power.effective},{icon:Database,a:"Storage",b:snapshot.storage.estimateAvailable?"Ready":"Limited"},{icon:Zap,a:"Service Worker",b:snapshot.install.serviceWorkerRegistered?"Registered":"Not registered"}].map(({icon:Icon,a,b})=><div key={a} className="flex min-h-0 flex-col items-center justify-center rounded-xl border border-white/10 bg-white/[.035] text-center"><Icon className="h-5 w-5 text-sky-300"/><p className="mt-2 text-[11px]">{a}</p><p className="mt-1 text-[9px] text-white/45">{b}</p></div>)}</div></Glass>
    <Glass title="NETWORK"><div className="space-y-1.5 rounded-xl bg-white/[.018] px-2 py-1"><Status icon={Wifi} a="Connection" b={status} ok={snapshot.network.online}/><Status icon={Gauge} a="Effective type" b={snapshot.network.effectiveType??"Not reported"} ok={snapshot.network.online}/><Status icon={Globe2} a="Downlink" b={snapshot.network.downlinkMbps!==undefined?snapshot.network.downlinkMbps+" Mbps":"Not reported"} ok={snapshot.network.online}/><Status icon={Smartphone} a="Device" b={snapshot.device.deviceClass} ok={snapshot.ready}/></div></Glass>
    <Glass title="RUNTIME"><div className="space-y-2 rounded-xl bg-white/[.018] px-2 py-1 text-[clamp(10px,.72vw,12px)]"><Row a="Browser" b={snapshot.device.browser.replace(" (best effort)","")}/><Row a="Display" b={snapshot.display.profile}/><Row a="Mode" b={snapshot.install.mode}/><Row a="Processors" b={snapshot.device.logicalProcessors?.toString()??"Not reported"}/><Row a="Memory" b={snapshot.device.deviceMemoryGB!==undefined?snapshot.device.deviceMemoryGB+" GB":"Not reported"}/></div></Glass>
   </div>
  </div>
 </section>
}
function Glass({title,children}:{title:string;children:React.ReactNode}){return <article className="min-h-0 overflow-hidden rounded-[1.25vw] border border-white/20 bg-[linear-gradient(135deg,rgba(8,19,37,.76),rgba(24,18,43,.66))] p-[clamp(.7rem,1.15vw,1.1rem)] shadow-[inset_0_1px_0_rgba(255,255,255,.16),inset_0_-1px_0_rgba(124,58,237,.10),0_18px_44px_rgba(0,0,0,.34)] backdrop-blur-2xl"><div className="mb-2 border-b border-white/10 pb-2 text-[clamp(.65rem,.9vw,.9rem)] tracking-[.28em]">{title}</div>{children}</article>}
function Row({a,b}:{a:string;b:string}){return <div className="flex items-center justify-between gap-3 border-b border-white/8 pb-1"><span>{a}</span><span className="max-w-[58%] truncate text-right text-white/52">{b}</span></div>}
function Status({icon:Icon,a,b,ok}:{icon:typeof Wifi;a:string;b:string;ok:boolean}){return <div className="flex items-center gap-3 border-b border-white/8 pb-2"><Icon className="h-5 w-5 text-sky-300"/><div className="min-w-0 flex-1"><p className="text-xs">{a}</p><p className="truncate text-[clamp(10px,.68vw,11px)] text-white/52">{b}</p></div><span className={"h-2 w-2 rounded-full "+(ok?"bg-emerald-400":"bg-white/25")}/></div>}
