import assert from "node:assert/strict";
import test from "node:test";
import { localAcademicDate, nextActiveAfrotcEvent, normalizeOpordEvent, opordPeriod, pfraSummary, resolvedUniform, selectCurrentOpord, upcomingPtEvents, type OpordSource } from "./selectors";
import type { OpordEvent } from "./types";

const event = (overrides: Partial<OpordEvent> = {}) => ({ id: "e", title: "Wednesday PT", date: { status: "explicit", value: "2026-09-09" }, reportTime: { status: "explicit", value: "05:55" }, reportQualifier: { status: "explicit", value: "unspecified" }, startTime: { status: "explicit", value: "06:00" }, endTime: { status: "explicit", value: "07:00" }, location: { status: "explicit", value: "Legacy Fields" }, formUpLocation: { status: "explicit", value: "Legacy Fields" }, activityLocations: [], uniform: { status: "unknown", value: null }, uniformRequirements: [{ audience: "GMC", uniform: "OCP" }], bring: [], instructions: [], timeline: [], workouts: [{ title: "Slow Repetitions Workout", blocks: [{ category: "Workout", exercises: [{ name: "Sit-ups", reps: 10, relevance: "direct-pfra", source: "Attachment 4" }, { name: "Regular Push-ups", reps: 10, relevance: "supporting", source: "Attachment 4" }], running: [{ name: "Run", distance: "2 laps", relevance: "direct-pfra", source: "Attachment 4" }] }], notes: [], source: "Attachment 4" }], specialConditions: [], deadlines: [], status: "scheduled", sourceId: "s", sourceName: "Week 02 OPORD", provenance: { sourceName: "Week 02 OPORD", excerpt: "Attachment 4" }, ...overrides }) as OpordEvent;
const source = (events: OpordEvent[]) => ({ id: "s", document: { events } } as never);

test("uses local academic dates and selects the next active event", () => { assert.match(localAcademicDate(new Date(2026, 8, 9)), /^2026-09-09$/); const cancelled = event({ id: "cancelled", status: "cancelled" }); const next = nextActiveAfrotcEvent([source([cancelled, event()])], "2026-09-01"); assert.equal(next?.event.id, "e"); });
test("resolves category UOD and keeps PT relevance source-derived", () => { const item = event(); assert.equal(resolvedUniform(item, "GMC"), "OCP"); assert.deepEqual(pfraSummary(item), ["Sit-ups", "Push-up prep", "Run prep"]); assert.equal(resolvedUniform({ ...item, uniformRequirements: [], uniform: { status: "explicit", value: "PTG" } }, "POC"), "PTG"); });
test("resolves singular First Term Cadet and POC against source audience rows", () => { const item = event({ uniformRequirements: [{ audience: "First Term Cadets", uniform: "Det Polo (Utility)" }, { audience: "GMC", uniform: "OCP" }, { audience: "POC", uniform: "OCP / FDU" }] }); assert.equal(resolvedUniform(item, "First Term Cadet"), "Det Polo (Utility)"); assert.equal(resolvedUniform(item, "GMC"), "OCP"); assert.equal(resolvedUniform(item, "POC"), "OCP / FDU"); assert.equal(resolvedUniform(item), null); assert.equal(resolvedUniform(item, "Unknown"), null); });
test("selects only active PT workouts in the local Monday-Sunday week", () => { const result = upcomingPtEvents([source([event()])], new Date(2026, 8, 7)); assert.equal(result.length, 1); });
test("legacy OPORD events without V2 arrays remain safe", () => { const legacy = event() as unknown as Record<string, unknown>; delete legacy.workouts; delete legacy.uniformRequirements; delete legacy.activityLocations; delete legacy.timeline; delete legacy.specialConditions; assert.deepEqual(pfraSummary(legacy as never), []); assert.equal(nextActiveAfrotcEvent([source([legacy as never])], "2026-09-01")?.event.id, "e"); });
test("legacy OPORD events without V2 structured fields normalize to unknown", () => { const legacy = event() as unknown as Record<string, unknown>; delete legacy.date; delete legacy.reportTime; delete legacy.reportQualifier; delete legacy.startTime; delete legacy.endTime; delete legacy.formUpLocation; delete legacy.uniform; delete legacy.workouts; delete legacy.activityLocations; delete legacy.uniformRequirements; delete legacy.timeline; delete legacy.specialConditions; const normalized = normalizeOpordEvent(legacy as never); for (const field of [normalized.date, normalized.reportTime, normalized.reportQualifier, normalized.startTime, normalized.endTime, normalized.formUpLocation, normalized.uniform]) assert.deepEqual(field, { status: "unknown", value: null }); assert.deepEqual(normalized.workouts, []); assert.deepEqual(normalized.activityLocations, []); assert.deepEqual(normalized.uniformRequirements, []); assert.deepEqual(normalized.timeline, []); assert.deepEqual(normalized.specialConditions, []); assert.deepEqual(pfraSummary(normalized), []); });
test("partially legacy OPORD events preserve explicit fields", () => { const legacy = event() as unknown as Record<string, unknown>; delete legacy.reportTime; delete legacy.startTime; delete legacy.formUpLocation; const normalized = normalizeOpordEvent(legacy as never); assert.deepEqual(normalized.date, { status: "explicit", value: "2026-09-09" }); assert.deepEqual(normalized.uniform, { status: "unknown", value: null }); assert.deepEqual(normalized.reportTime, { status: "unknown", value: null }); assert.deepEqual(normalized.startTime, { status: "unknown", value: null }); assert.deepEqual(normalized.formUpLocation, { status: "unknown", value: null }); });
test("legacy false document sections remain excluded from operational types", () => { const legacy = event({ title: "Operational Risk Management (ORM) LLAB & PT ORM" }); delete (legacy as unknown as Record<string, unknown>).type; const normalized = normalizeOpordEvent(legacy as never); assert.equal(normalized.type, undefined); });
test("keeps current, upcoming, and past OPORDs isolated by source dates", () => { const make = (id: string, date: string, uniform: string, weekNumber: number) => ({ id, document: { weekNumber, weekLabel: `Week ${String(weekNumber).padStart(2, "0")}`, events: [event({ id: `${id}-event`, sourceId: id, date: { status: "explicit", value: date }, uniformRequirements: [{ audience: "First Term Cadets", uniform }] })] } }) as unknown as OpordSource; const week02 = make("week-02", "2026-09-09", "Week 02 Polo", 2); const week03 = make("week-03", "2026-09-16", "Week 03 Polo", 3); const week01 = make("week-01", "2026-09-02", "Week 01 Polo", 1); assert.equal(opordPeriod(week02, "2026-09-09"), "current"); assert.equal(opordPeriod(week03, "2026-09-09"), "upcoming"); assert.equal(opordPeriod(week01, "2026-09-09"), "past"); assert.equal(selectCurrentOpord([week03, week02, week01], "2026-09-09")?.id, "week-02"); assert.equal(selectCurrentOpord([week03, week02, week01], "2026-09-16")?.id, "week-03"); assert.equal(resolvedUniform(week02.document.events[0], "First Term Cadet"), "Week 02 Polo"); assert.equal(resolvedUniform(week03.document.events[0], "First Term Cadet"), "Week 03 Polo"); });
