import type { OpordDocument, OpordEvent, OpordField, PtExercise } from "./types";

export type OpordSource = { id: string; title?: string; createdAt?: string | Date; updatedAt?: string | Date; document: OpordDocument };
export type OpordEventRef = { source: OpordSource; event: OpordEvent };
export type OpordPeriod = "current" | "upcoming" | "past" | "unclassified";

function unknownField<T>(): OpordField<T> { return { status: "unknown", value: null }; }
function normalizeField<T>(field: unknown): OpordField<T> { if (!field || typeof field !== "object") return unknownField<T>(); const candidate = field as { status?: string; value?: T | null; values?: T[]; excerpt?: string }; if (candidate.status === "explicit" && candidate.value != null) return field as OpordField<T>; if (candidate.status === "conflicting" && Array.isArray(candidate.values)) return field as OpordField<T>; if (candidate.status === "unknown") return { status: "unknown", value: null, ...(candidate.excerpt ? { excerpt: candidate.excerpt } : {}) }; return unknownField<T>(); }
function eventType(event: OpordEvent): OpordEvent["type"] { if (event.type) return event.type; if (/operational risk|\bORM\b|catastrophic|approval|attachment|emergency|map/i.test(event.title)) return undefined; if (/physical training|\bPT\b/i.test(event.title)) return "pt"; if (/leadership laboratory|\bLLAB\b/i.test(event.title)) return "llab"; return undefined; }
export function normalizeOpordEvent(event: OpordEvent): OpordEvent { return { ...event, type: eventType(event), date: normalizeField<string>(event.date), reportTime: normalizeField<string>(event.reportTime), reportQualifier: normalizeField<"NLT" | "NET" | "Pre-Formation" | "unspecified">(event.reportQualifier), startTime: normalizeField<string>(event.startTime), endTime: normalizeField<string>(event.endTime), location: normalizeField<string>(event.location), formUpLocation: normalizeField<string>(event.formUpLocation), uniform: normalizeField<string>(event.uniform), workouts: event.workouts ?? [], uniformRequirements: event.uniformRequirements ?? [], activityLocations: event.activityLocations ?? [], timeline: event.timeline ?? [], specialConditions: event.specialConditions ?? [] }; }
export function normalizeOpordDocument(document: OpordDocument): OpordDocument { return { ...document, events: (document.events ?? []).map(normalizeOpordEvent) }; }

export function localAcademicDate(date = new Date()) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function dateOf(item: OpordEventRef) { return item.event.date.status === "explicit" ? item.event.date.value : null; }
export function activeOpordEvents(sources: OpordSource[]): OpordEventRef[] { return activeSources(sources).flatMap((source) => normalizeOpordDocument(source.document).events.filter((event) => event.status !== "cancelled").map((event) => ({ source, event }))); }
export function nextActiveAfrotcEvent(sources: OpordSource[], today = localAcademicDate()): OpordEventRef | undefined { return activeOpordEvents(sources).filter((item) => (dateOf(item) ?? "") >= today).sort((a, b) => (dateOf(a) ?? "9999").localeCompare(dateOf(b) ?? "9999"))[0]; }
export function todayAfrotcEvents(sources: OpordSource[], today = localAcademicDate()) { return activeOpordEvents(sources).filter((item) => dateOf(item) === today); }
export function upcomingPtEvents(sources: OpordSource[], today = new Date()): OpordEventRef[] { const monday = new Date(today.getFullYear(), today.getMonth(), today.getDate() - ((today.getDay() + 6) % 7)); const sunday = new Date(monday); sunday.setDate(monday.getDate() + 7); return activeOpordEvents(sources).filter(({ event }) => (event.workouts ?? []).length && event.date.status === "explicit" && event.date.value >= localAcademicDate(monday) && event.date.value < localAcademicDate(sunday)); }
function normalizeAudience(value: string) { return value.trim().toLowerCase().replace(/\s+/g, " ").replace(/s$/, ""); }
export function resolvedUniform(event: OpordEvent, category?: string) { if (event.uniformRequirements?.length) { if (!category) return null; const matches = event.uniformRequirements.filter((item) => normalizeAudience(item.audience) === normalizeAudience(category)); return matches.length === 1 ? matches[0].uniform : null; } return event.uniform.status === "explicit" ? event.uniform.value : null; }
export function opordEventDates(source: OpordSource): string[] { return normalizeOpordDocument(source.document).events.map((event) => dateOf({ source, event })).filter((date): date is string => Boolean(date)); }
export function opordPeriod(source: OpordSource, today = localAcademicDate()): OpordPeriod { const dates = opordEventDates(source).sort(); if (!dates.length) return "unclassified"; if (dates[0] <= today && dates[dates.length - 1] >= today) return "current"; return dates[0] > today ? "upcoming" : "past"; }
function activeSources(sources: OpordSource[]) { return sources.filter((source) => !source.document.isSuperseded); }
export function selectCurrentOpord(sources: OpordSource[], today = localAcademicDate()): OpordSource | undefined { const available = activeSources(sources); const dated = available.filter((source) => opordEventDates(source).length); const current = dated.filter((source) => opordPeriod(source, today) === "current").sort((a, b) => Math.max(...opordEventDates(b).map((date) => Number(date.replaceAll("-", "")))) - Math.max(...opordEventDates(a).map((date) => Number(date.replaceAll("-", ""))))); if (current[0]) return current[0]; const upcoming = dated.filter((source) => opordPeriod(source, today) === "upcoming").sort((a, b) => opordEventDates(a).sort()[0].localeCompare(opordEventDates(b).sort()[0])); if (upcoming[0]) return upcoming[0]; return available.slice().sort((a, b) => String(b.updatedAt ?? b.createdAt ?? "").localeCompare(String(a.updatedAt ?? a.createdAt ?? "")))[0]; }
export function nextOpord(sources: OpordSource[], today = localAcademicDate()): OpordSource | undefined { return activeSources(sources).filter((source) => opordPeriod(source, today) === "upcoming").sort((a, b) => opordEventDates(a).sort()[0].localeCompare(opordEventDates(b).sort()[0]))[0]; }
export function sortOpords(sources: OpordSource[], today = localAcademicDate()): OpordSource[] { const rank: Record<OpordPeriod, number> = { current: 0, upcoming: 1, past: 2, unclassified: 3 }; return sources.slice().sort((a, b) => { const periodDiff = rank[opordPeriod(a, today)] - rank[opordPeriod(b, today)]; if (periodDiff) return periodDiff; const aDate = opordEventDates(a).sort()[0] ?? "9999"; const bDate = opordEventDates(b).sort()[0] ?? "9999"; return aDate.localeCompare(bDate) || (b.document.weekNumber ?? 999) - (a.document.weekNumber ?? 999); }); }
export function pfraSummary(event: OpordEvent) { const exercises: PtExercise[] = (event.workouts ?? []).flatMap((workout) => workout.blocks.flatMap((block) => [...(block.exercises ?? []), ...(block.running ?? [])])); return [...new Set(exercises.map((item) => item.relevance === "direct-pfra" ? (item.name === "Run" ? "Run prep" : item.name) : item.relevance === "supporting" ? (item.name.toLowerCase().includes("push") ? "Push-up prep" : "Supporting strength") : "Other"))]; }
