import "server-only";
import type { MailMessage } from "@/core/contracts/Mail";
import type { MailProviderAdapter } from "@/engines/mail";
import { markProviderReconnectRequired, setProviderCredentials } from "@/services/providers/store";
import { normalizeOutlookMessage, type OutlookGraphMessage } from "./outlookNormalization";

export interface OutlookToken { access_token: string; refresh_token?: string; expires_at?: number; scope?: string; }
export const OUTLOOK_MAIL_SCOPES = ["openid", "profile", "offline_access", "User.Read", "Mail.Read"] as const;
export const OUTLOOK_IDENTITY_SCOPES = ["openid", "profile", "email", "User.Read"] as const;
const GRAPH = "https://graph.microsoft.com/v1.0";

export function isOutlookConfigured() { return Boolean(process.env.MICROSOFT_CLIENT_ID && process.env.MICROSOFT_CLIENT_SECRET && process.env.MICROSOFT_REDIRECT_URI); }
export function getOutlookAuthorizationUrl(state: string) { if (!isOutlookConfigured()) throw new Error("Outlook OAuth is not configured."); const query = new URLSearchParams({ client_id: process.env.MICROSOFT_CLIENT_ID!, redirect_uri: process.env.MICROSOFT_REDIRECT_URI!, response_type: "code", response_mode: "query", scope: OUTLOOK_MAIL_SCOPES.join(" "), state }); return `https://login.microsoftonline.com/common/oauth2/v2.0/authorize?${query}`; }
export function getMicrosoftIdentityAuthorizationUrl(state: string) { if (!isOutlookConfigured()) throw new Error("Microsoft identity OAuth is not configured."); const redirectUri = process.env.MICROSOFT_IDENTITY_REDIRECT_URI ?? process.env.MICROSOFT_REDIRECT_URI!; const query = new URLSearchParams({ client_id: process.env.MICROSOFT_CLIENT_ID!, redirect_uri: redirectUri, response_type: "code", response_mode: "query", scope: OUTLOOK_IDENTITY_SCOPES.join(" "), state }); return `https://login.microsoftonline.com/common/oauth2/v2.0/authorize?${query}`; }
export async function exchangeMicrosoftIdentityCode(code: string): Promise<{ access_token: string }> { const redirectUri = process.env.MICROSOFT_IDENTITY_REDIRECT_URI ?? process.env.MICROSOFT_REDIRECT_URI!; const response = await fetch("https://login.microsoftonline.com/common/oauth2/v2.0/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: process.env.MICROSOFT_CLIENT_ID!, client_secret: process.env.MICROSOFT_CLIENT_SECRET!, redirect_uri: redirectUri, grant_type: "authorization_code", code, scope: OUTLOOK_IDENTITY_SCOPES.join(" ") }) }); if (!response.ok) throw new Error("Microsoft identity sign-in failed."); const token = await response.json() as { access_token?: string }; if (!token.access_token) throw new Error("Microsoft identity token is missing."); return { access_token: token.access_token }; }
export async function exchangeMicrosoftCode(code: string): Promise<OutlookToken> { const response = await fetch("https://login.microsoftonline.com/common/oauth2/v2.0/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: process.env.MICROSOFT_CLIENT_ID!, client_secret: process.env.MICROSOFT_CLIENT_SECRET!, redirect_uri: process.env.MICROSOFT_REDIRECT_URI!, grant_type: "authorization_code", code, scope: OUTLOOK_MAIL_SCOPES.join(" ") }) }); if (!response.ok) throw new Error("Microsoft OAuth token exchange failed."); const token = await response.json() as OutlookToken & { expires_in?: number }; return { ...token, expires_at: token.expires_in ? Date.now() + token.expires_in * 1000 : undefined }; }

export async function storeAccountOutlookToken(accountId: string, token: OutlookToken) {
  const response = await fetch(`${GRAPH}/me?$select=id,displayName,mail,userPrincipalName`, { headers: { Authorization: `Bearer ${token.access_token}` } });
  if (!response.ok) throw new Error("Outlook account identity could not be verified.");
  const profile = await response.json() as { id?: string; displayName?: string; mail?: string; userPrincipalName?: string };
  if (!profile.id) throw new Error("Outlook account identity is missing.");
  const { upsertProviderConnection } = await import("@/services/providers/store");
  const email = profile.mail ?? profile.userPrincipalName;
  const connection = await upsertProviderConnection(accountId, { provider: "outlook", providerAccountId: profile.id, ...(email ? { email } : {}), displayName: profile.displayName ?? email ?? "Outlook", metadata: { capabilities: ["mail.read"] } });
  await setProviderCredentials(accountId, connection.id, token as unknown as Record<string, unknown>);
  return connection;
}

export class OutlookProvider implements MailProviderAdapter {
  constructor(private token: OutlookToken, private readonly connectionId: string, private readonly accountId: string) {}
  async getMessages(options: { limit?: number } = {}): Promise<MailMessage[]> { const limit = Math.min(Math.max(options.limit ?? 30, 1), 50); const url = new URL(`${GRAPH}/me/mailFolders/inbox/messages`); url.searchParams.set("$top", String(limit)); url.searchParams.set("$orderby", "receivedDateTime desc"); url.searchParams.set("$select", "id,conversationId,subject,bodyPreview,body,sender,toRecipients,ccRecipients,receivedDateTime,isRead,hasAttachments,webLink"); const result = await this.request<{ value?: OutlookGraphMessage[] }>(url.toString()); return (result.value ?? []).filter((item) => item.id).map((item) => normalizeOutlookMessage(item)); }
  async getMessage(id: string) { const url = new URL(`${GRAPH}/me/messages/${encodeURIComponent(id)}`); url.searchParams.set("$select", "id,conversationId,subject,bodyPreview,body,sender,toRecipients,ccRecipients,receivedDateTime,isRead,hasAttachments,webLink,attachments"); return normalizeOutlookMessage(await this.request<OutlookGraphMessage>(url.toString())); }
  private async request<T>(url: string): Promise<T> { if (this.token.expires_at && this.token.expires_at <= Date.now() + 60_000) await this.refresh(); let response = await fetch(url, { headers: { Authorization: `Bearer ${this.token.access_token}` } }); if (response.status === 401) { await this.refresh(); response = await fetch(url, { headers: { Authorization: `Bearer ${this.token.access_token}` } }); } if (response.status === 403) throw new Error("Outlook mail permission is required."); if (!response.ok) throw new Error(`Outlook request failed (${response.status}).`); return response.json() as Promise<T>; }
  private async refresh() { if (!this.token.refresh_token) { await markProviderReconnectRequired(this.accountId, this.connectionId); throw new Error("Outlook reconnect required."); } const response = await fetch("https://login.microsoftonline.com/common/oauth2/v2.0/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: process.env.MICROSOFT_CLIENT_ID!, client_secret: process.env.MICROSOFT_CLIENT_SECRET!, grant_type: "refresh_token", refresh_token: this.token.refresh_token, scope: OUTLOOK_MAIL_SCOPES.join(" ") }) }); if (!response.ok) { await markProviderReconnectRequired(this.accountId, this.connectionId); throw new Error("Outlook reconnect required."); } const refreshed = await response.json() as OutlookToken & { expires_in?: number }; this.token = { ...this.token, ...refreshed, refresh_token: refreshed.refresh_token ?? this.token.refresh_token, expires_at: refreshed.expires_in ? Date.now() + refreshed.expires_in * 1000 : this.token.expires_at }; await setProviderCredentials(this.accountId, this.connectionId, this.token as unknown as Record<string, unknown>); }
}
