CREATE TABLE "kiosk_device_settings" (
	"device_id" text PRIMARY KEY NOT NULL,
	"setup_completed" boolean DEFAULT false NOT NULL,
	"setup_version" integer DEFAULT 0 NOT NULL,
	"viewport_width" integer,
	"viewport_height" integer,
	"physical_screen_width" integer,
	"physical_screen_height" integer,
	"device_pixel_ratio" double precision,
	"aspect_ratio" double precision,
	"orientation" text,
	"density" text,
	"ui_scale" double precision DEFAULT 1 NOT NULL,
	"touch_detected" boolean,
	"pointer" text,
	"timezone" text,
	"clock_format" text,
	"location_latitude" double precision,
	"location_longitude" double precision,
	"location_label" text,
	"location_source" text,
	"night_dim_enabled" boolean DEFAULT true NOT NULL,
	"night_dim_start" text DEFAULT '20:00' NOT NULL,
	"night_dim_end" text DEFAULT '06:00' NOT NULL,
	"night_dim_opacity" double precision DEFAULT 0.35 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "kiosk_device_settings_device_id_devices_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."devices"("id") ON DELETE cascade,
	CONSTRAINT "kiosk_device_settings_orientation_check" CHECK ("orientation" is null or "orientation" in ('landscape', 'portrait')),
	CONSTRAINT "kiosk_device_settings_density_check" CHECK ("density" is null or "density" in ('compact', 'standard', 'large')),
	CONSTRAINT "kiosk_device_settings_pointer_check" CHECK ("pointer" is null or "pointer" in ('coarse', 'fine', 'unknown')),
	CONSTRAINT "kiosk_device_settings_clock_format_check" CHECK ("clock_format" is null or "clock_format" in ('12h', '24h')),
	CONSTRAINT "kiosk_device_settings_ui_scale_check" CHECK ("ui_scale" >= 0.9 and "ui_scale" <= 1.1),
	CONSTRAINT "kiosk_device_settings_dim_opacity_check" CHECK ("night_dim_opacity" >= 0 and "night_dim_opacity" <= 1)
);
CREATE INDEX "kiosk_device_settings_updated_index" ON "kiosk_device_settings" USING btree ("updated_at");
