"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useBillingStatus } from "@/hooks/os/useBillingStatus";
import { useCosmicAccount } from "./AccountProvider";
import IdentityMethodsPanel from "./IdentityMethodsPanel";

type Connection = { id: string; provider: string; providerType?: string | null; status: string; reconnectRequired: boolean; displayName?: string | null; email?: string | null };

export default function ConnectionsPanel({ returnTo }: { returnTo?: string } = {}) { return <><IdentityMethodsPanel returnTo={returnTo} /><BillingSummary /><ConnectionsPanelContent returnTo={returnTo} /><AccountDeletionPanel /></>; }

function BillingSummary() {
  const { data, loading } = useBillingStatus();
  return <section className="mt-5 rounded-2xl border border-fuchsia-200/12 bg-fuchsia-200/[0.035] p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-fuchsia-100/55">Billing</p><p className="mt-1 font-semibold text-white">{loading ? "Loading…" : data.subscription?.status === "past_due" || data.subscription?.status === "unpaid" ? "Cosmic+ payment needs attention" : data.plan === "cosmic_plus" ? "Cosmic+ active" : "Free"}</p>{data.plan === "cosmic_plus" && data.subscription?.currentPeriodEnd ? <p className="mt-1 text-xs text-white/45">{data.subscription.cancelAtPeriodEnd ? "Active until" : "Renews"} {new Date(data.subscription.currentPeriodEnd).toLocaleDateString()}</p> : null}</div><Link href="/cosmic-plus" className="rounded-xl border border-fuchsia-200/20 bg-fuchsia-200/10 px-3 py-2 text-sm text-fuchsia-50">{data.plan === "cosmic_plus" ? "Manage" : "View billing"}</Link></div></section>;
}

function AccountDeletionPanel() {
  const { account } = useCosmicAccount();
  const [confirmation, setConfirmation] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  async function deleteAccount() {
    setBusy(true); setError(undefined);
    try { const response = await fetch("/api/account/delete", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmation }) }); const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Account deletion failed."); window.location.assign("/account"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Account deletion failed."); setBusy(false); }
  }
  return <section className="mt-5 rounded-2xl border border-rose-200/12 bg-rose-200/[0.035] p-5"><h2 className="font-semibold text-rose-100/90">Delete account</h2><p className="mt-1 text-sm leading-6 text-white/50">This removes private account data, sessions, provider credentials, and billing mappings. Any active Stripe subscription is canceled first.</p><label className="mt-4 block text-sm text-white/60">Type DELETE to confirm<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-white" autoComplete="off" /></label>{error ? <p role="alert" className="mt-3 text-sm text-rose-200">{error}</p> : null}<button type="button" disabled={!account || confirmation !== "DELETE" || busy} onClick={() => void deleteAccount()} className="mt-4 rounded-xl border border-rose-200/20 bg-rose-200/10 px-3 py-2 text-sm text-rose-50 disabled:opacity-40">{busy ? "Deleting…" : "Delete account"}</button></section>;
}

function ConnectionsPanelContent({ returnTo }: { returnTo?: string }) {
  const [connections, setConnections] = useState<Connection[]>([]);
  const [error, setError] = useState<string | null>(null);
  async function load() { const response = await fetch("/api/account/connections"); const data = await response.json() as { connections?: Connection[]; error?: string }; if (!response.ok) { setError(data.error ?? "Connections are unavailable."); return; } setConnections(data.connections ?? []); }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function disconnect(id: string) { const response = await fetch("/api/account/connections", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ connectionId: id }) }); if (!response.ok) { setError("Could not disconnect provider."); return; } await load(); }
  const oauthReturn = returnTo ? `?returnTo=${encodeURIComponent(returnTo)}` : "";
  return <section className="mt-8 rounded-2xl border border-white/10 bg-white/[0.04] p-5"><h2 className="text-lg font-bold">Add to Cosmic Calendar</h2><p className="mt-1 text-sm text-white/45">Connect a private calendar or add a read-only subscription. Calendar credentials stay encrypted on Cosmic servers.</p>{error ? <p className="mt-4 text-sm text-rose-200">{error}</p> : null}<div className="mt-5 grid gap-3 sm:grid-cols-2"><CalendarForm onCreated={() => void load()} /><div className="rounded-xl border border-white/10 p-4"><p className="font-semibold">Calendar subscriptions</p><p className="mt-1 text-sm text-white/45">Add an HTTPS ICS or webcal feed. Recurring events are supported.</p><SubscriptionManager onChanged={() => void load()} /></div></div><div className="mt-5 rounded-xl border border-white/10 p-4"><p className="font-semibold">Cosmic Sports</p><p className="mt-1 text-sm text-white/45">Sports events follow your existing Cosmic Sports preferences. They are separate from subscribed sports feeds.</p><Link className="mt-3 inline-block text-sm text-cyan-100/80" href="/settings">Manage followed sports</Link></div><div className="mt-6 border-t border-white/10 pt-5"><h3 className="font-semibold">Connected accounts</h3><div className="mt-3 space-y-3">{connections.map((connection) => <div key={connection.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 p-3"><div><p className="font-semibold capitalize">{connection.provider}{connection.providerType ? ` · ${connection.providerType}` : ""}</p><p className="text-xs text-white/45">{connection.email ?? connection.displayName ?? connection.status}{connection.reconnectRequired ? " · reconnect required" : ""}</p></div><button type="button" className="text-xs text-rose-200/80" onClick={() => void disconnect(connection.id)}>Disconnect</button></div>)}{connections.length === 0 && !error ? <p className="text-sm text-white/40">No account-owned connections yet.</p> : null}</div></div><div className="mt-5 flex gap-3 text-sm"><a className="text-cyan-100/80" href={`/api/auth/google${oauthReturn}`}>Connect Gmail</a><a className="text-cyan-100/80" href={`/api/auth/spotify${oauthReturn}`}>Connect Spotify</a></div></section>;
}

function CalendarForm({ onCreated }: { onCreated: () => void }) {
  const [open, setOpen] = useState(false); const [kind, setKind] = useState<"icloud" | "caldav">("icloud"); const [displayName, setDisplayName] = useState(""); const [serverUrl, setServerUrl] = useState(""); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(null); setBusy(true); try { const response = await fetch("/api/account/connections/calendar", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, displayName, serverUrl, username, password }) }); const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Calendar connection failed."); setPassword(""); setOpen(false); onCreated(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Calendar connection failed."); } finally { setBusy(false); } }
  if (!open) return <div className="rounded-xl border border-white/10 p-4"><p className="font-semibold">Private calendars</p><p className="mt-1 text-sm text-white/45">iCloud and compatible CalDAV accounts are supported.</p><button type="button" className="mt-3 text-sm text-cyan-100/80" onClick={() => setOpen(true)}>Connect private calendar</button></div>;
  return <form onSubmit={submit} className="rounded-xl border border-white/10 p-4"><div className="flex gap-2 text-xs"><button type="button" className={kind === "icloud" ? "rounded-lg bg-white/15 px-2 py-1" : "rounded-lg px-2 py-1 text-white/50"} onClick={() => setKind("icloud")}>iCloud</button><button type="button" className={kind === "caldav" ? "rounded-lg bg-white/15 px-2 py-1" : "rounded-lg px-2 py-1 text-white/50"} onClick={() => setKind("caldav")}>Other CalDAV</button></div><p className="mt-3 text-xs leading-5 text-white/50">{kind === "icloud" ? <>Use your Apple email and an app-specific password. <a className="text-cyan-100/80" href="https://support.apple.com/en-us/102654" target="_blank" rel="noreferrer">Apple instructions</a></> : "Use an HTTPS CalDAV server address. Cosmic verifies it before saving."}</p><input placeholder="Name (optional)" value={displayName} onChange={(e) => setDisplayName(e.target.value)} className="mt-3 w-full rounded-lg bg-white/10 p-2 text-sm" />{kind === "caldav" ? <input required placeholder="caldav.example.com" value={serverUrl} onChange={(e) => setServerUrl(e.target.value)} className="mt-2 w-full rounded-lg bg-white/10 p-2 text-sm" /> : null}<input required type="email" placeholder="Apple email" value={username} onChange={(e) => setUsername(e.target.value)} className="mt-2 w-full rounded-lg bg-white/10 p-2 text-sm" /><input required type="password" placeholder="App-specific password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 w-full rounded-lg bg-white/10 p-2 text-sm" />{error ? <p className="mt-2 text-xs text-rose-200">{error}</p> : null}<div className="mt-3 flex gap-3"><button disabled={busy} className="text-sm text-cyan-100/80">{busy ? "Verifying…" : "Verify and connect"}</button><button type="button" className="text-sm text-white/45" onClick={() => setOpen(false)}>Cancel</button></div></form>;
}

type Subscription = { id: string; name: string; enabled: boolean; status: string; lastSuccessfulRefreshAt?: string | null };
function SubscriptionManager({ onChanged }: { onChanged: () => void }) {
  const [items, setItems] = useState<Subscription[]>([]); const [url, setUrl] = useState(""); const [name, setName] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function load() { const response = await fetch("/api/calendar/subscriptions", { cache: "no-store" }); const body = await response.json() as { subscriptions?: Subscription[] }; if (response.ok) setItems(body.subscriptions ?? []); }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function add(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const response = await fetch("/api/calendar/subscriptions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url, displayName: name }) }); const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Subscription could not be added."); setUrl(""); setName(""); await load(); onChanged(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Subscription could not be added."); } finally { setBusy(false); } }
  async function update(id: string, body: Record<string, unknown>) { await fetch("/api/calendar/subscriptions", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, ...body }) }); await load(); onChanged(); }
  async function rename(item: Subscription) { const next = window.prompt("Calendar name", item.name); if (next?.trim()) await update(item.id, { displayName: next.trim() }); }
  async function remove(id: string) { await fetch("/api/calendar/subscriptions", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); await load(); onChanged(); }
  return <div><form onSubmit={add} className="mt-3 space-y-2"><input required type="url" placeholder="https://example.com/calendar.ics" value={url} onChange={(e) => setUrl(e.target.value)} className="w-full rounded-lg bg-white/10 p-2 text-sm" /><input placeholder="Calendar name (optional)" value={name} onChange={(e) => setName(e.target.value)} className="w-full rounded-lg bg-white/10 p-2 text-sm" />{error ? <p className="text-xs text-rose-200">{error}</p> : null}<button disabled={busy} className="text-sm text-cyan-100/80">{busy ? "Checking…" : "Test and add feed"}</button></form>{items.length ? <div className="mt-4 space-y-2">{items.map((item) => <div key={item.id} className="flex items-center justify-between gap-2 rounded-lg border border-white/10 p-2 text-sm"><span>{item.name}{!item.enabled ? " · paused" : ""}</span><span className="flex gap-2 text-xs"><button type="button" className="text-cyan-100/80" onClick={() => void rename(item)}>Rename</button><button type="button" className="text-cyan-100/80" onClick={() => void update(item.id, { refresh: true })}>Refresh</button><button type="button" className="text-white/50" onClick={() => void update(item.id, { enabled: !item.enabled })}>{item.enabled ? "Pause" : "Enable"}</button><button type="button" className="text-rose-200/80" onClick={() => void remove(item.id)}>Remove</button></span></div>)}</div> : null}</div>;
}
