"use client";

import { useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { useCosmicAccount } from "./AccountProvider";

export default function DeviceRecoveryView() {
  const { loading, account } = useCosmicAccount();
  const challenge = useSearchParams().get("challenge") ?? "";
  const [state, setState] = useState<"ready" | "approved" | "error">("ready");
  const [error, setError] = useState<string | null>(null);
  if (!challenge) return <PasswordRecoveryView />;
  async function approve() {
    setState("ready"); setError(null);
    try {
      const response = await fetch("/api/devices/enrollment/authorize", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ challengeId: challenge }), credentials: "include", cache: "no-store" });
      const body = await response.json() as { error?: string };
      if (!response.ok) throw new Error(body.error ?? "Enrollment authorization failed.");
      setState("approved");
    } catch (caught) { setState("error"); setError(caught instanceof Error ? caught.message : "Enrollment authorization failed."); }
  }
  if (loading) return <main className="grid min-h-screen place-items-center bg-[#030511] text-white/60">Checking Cosmic account…</main>;
  const returnTo = `/activate/recover?challenge=${encodeURIComponent(challenge)}`;
  return <main className="grid min-h-screen place-items-center bg-[#030511] px-5 py-10 text-white"><div className="w-full max-w-md rounded-[2rem] border border-white/10 bg-white/[0.04] p-7 shadow-2xl"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-200/60">Cosmic OS</p>{!account ? <><h1 className="mt-4 text-3xl font-black">Sign in to recover your display</h1><p className="mt-3 text-sm leading-6 text-white/55">The current Cosmic account owner must approve recovery for this physical display.</p><Link className="mt-7 inline-block rounded-xl border border-cyan-200/20 bg-cyan-200/10 px-4 py-3 text-sm text-cyan-50" href={`/account?returnTo=${encodeURIComponent(returnTo)}`}>Sign in to continue</Link></> : state === "approved" ? <><h1 className="mt-4 text-3xl font-black">Recovery authorized</h1><p className="mt-3 text-sm leading-6 text-white/55">Return to the display. The trusted helper will finish enrollment without exposing its credential to the browser.</p></> : <><h1 className="mt-4 text-3xl font-black">Recover Cosmic Display</h1><p className="mt-3 text-sm leading-6 text-white/55">You are signed in as {account.email}. Approve recovery only if you are physically setting up this display.</p>{error ? <p className="mt-4 text-sm text-rose-200">{error}</p> : null}<button type="button" disabled={!challenge} onClick={() => void approve()} className="mt-7 w-full rounded-xl border border-cyan-200/20 bg-cyan-200/10 px-4 py-3 font-semibold text-cyan-50 disabled:opacity-40">Approve display recovery</button></>}</div></main>;
}

function PasswordRecoveryView() {
  const token = useSearchParams().get("token") ?? "";
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState("");
  const [message, setMessage] = useState<string | null>(null); const [resetUrl, setResetUrl] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function requestReset(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(null); setMessage(null); setResetUrl(null); try { const response = await fetch("/api/account/password-reset/request", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }), cache: "no-store" }); const body = await response.json() as { message?: string; resetUrl?: string }; if (!response.ok) throw new Error(body.message ?? "Recovery request failed."); setResetUrl(body.resetUrl ?? null); setMessage(body.message ?? "Recovery instructions are ready."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Recovery request failed."); } finally { setBusy(false); } }
  async function resetPassword(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(null); setMessage(null); if (password !== confirm) { setError("Passwords do not match."); setBusy(false); return; } try { const response = await fetch("/api/account/password-reset/confirm", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, password }), cache: "no-store" }); const body = await response.json() as { message?: string; error?: string }; if (!response.ok) throw new Error(body.error ?? "Password could not be updated."); setMessage(body.message ?? "Password updated."); setPassword(""); setConfirm(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Password could not be updated."); } finally { setBusy(false); } }
  const input = "mt-2 w-full rounded-xl border border-white/12 bg-black/20 px-4 py-3 text-sm text-white outline-none focus:border-cyan-200/55";
  return <main className="grid min-h-screen place-items-center bg-[#030511] px-5 py-10 text-white"><div className="w-full max-w-md rounded-[2rem] border border-white/10 bg-white/[0.04] p-7 shadow-2xl"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-200/60">Cosmic OS</p><h1 className="mt-4 text-3xl font-black">{token ? "Choose a new password" : "Reset your password"}</h1><p className="mt-3 text-sm leading-6 text-white/55">{token ? "Choose a new password for your Cosmic account. This link can only be used once." : "Enter your account email and we’ll prepare secure recovery instructions."}</p>{token ? <form onSubmit={resetPassword} className="mt-7 space-y-4"><label className="block text-sm text-white/70">New password<input required minLength={10} type="password" className={input} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" /></label><label className="block text-sm text-white/70">Confirm new password<input required minLength={10} type="password" className={input} value={confirm} onChange={(event) => setConfirm(event.target.value)} autoComplete="new-password" /></label><button disabled={busy} className="w-full rounded-xl border border-cyan-200/20 bg-cyan-200/10 px-4 py-3 font-semibold text-cyan-50 disabled:opacity-40">{busy ? "Updating…" : "Set new password"}</button></form> : <form onSubmit={requestReset} className="mt-7 space-y-4"><label className="block text-sm text-white/70">Email address<input required type="email" className={input} value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" /></label><button disabled={busy} className="w-full rounded-xl border border-cyan-200/20 bg-cyan-200/10 px-4 py-3 font-semibold text-cyan-50 disabled:opacity-40">{busy ? "Preparing…" : "Send recovery instructions"}</button></form>}{error ? <p role="alert" className="mt-4 break-words text-sm text-rose-200">{error}</p> : null}{message ? <p role="status" className="mt-4 text-sm text-emerald-200">{message}</p> : null}{resetUrl ? <a className="mt-3 block break-all text-sm text-cyan-200 underline" href={resetUrl}>Open local reset link</a> : null}<Link className="mt-6 inline-block text-sm text-white/55 hover:text-white" href="/account">← Back to sign in</Link></div></main>;
}
