"use client";

import Link from "next/link";
import { BookOpen, CalendarDays, CheckCircle2, Clock3, ListChecks, MapPin } from "lucide-react";
import { useEffect, useState } from "react";
import type { Course } from "@/core/contracts/School";
import type { SchoolPlanningAssignment } from "@/core/contracts/SchoolPlanning";
import { useSchool } from "./context/SchoolDataContext";
import { getNextClassToday, getOverdueAssignments, getSchoolToday, getSchoolWeek, getUpcomingAssignments, localAssignmentToPlanning, projectCourseMeetings } from "@/services/school/semesterConsumers";
import { buildProactivePlan } from "@/services/school/planning/academicPlanner";

const panel = "rounded-[1.35rem] border border-white/[0.09] bg-[#101c35]/75";
const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
const courseLabel = (course: Course) => course.code ? `${course.code} · ${course.name}` : course.name;
const localDate = (date: Date) => date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
const localTime = (date: Date) => date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });

function relative(minutes: number) { if (minutes < 1) return "Starting now"; if (minutes < 60) return `Starts in ${minutes} min`; const hours = Math.floor(minutes / 60); return `Starts in ${hours}h ${minutes % 60}m`; }
function dueLabel(item: SchoolPlanningAssignment, now: Date) { if (!item.dueAt) return "No due date"; const date = item.dueAt; const today = date.toDateString() === now.toDateString(); const tomorrow = new Date(now); tomorrow.setDate(tomorrow.getDate() + 1); if (today) return `Today${date.getHours() || date.getMinutes() ? ` · ${localTime(date)}` : ""}`; if (date.toDateString() === tomorrow.toDateString()) return `Tomorrow${date.getHours() || date.getMinutes() ? ` · ${localTime(date)}` : ""}`; return `${localDate(date)}${date.getHours() || date.getMinutes() ? ` · ${localTime(date)}` : ""}`; }

function AssignmentItem({ item, now }: { item: SchoolPlanningAssignment; now: Date }) { return <Link href={`/school/assignments/${encodeURIComponent(item.id)}`} className="group flex items-center gap-3 border-t border-white/[0.07] px-4 py-3 transition hover:bg-white/[0.04]"><CheckCircle2 className="size-4 shrink-0 text-sky-200/70" /><span className="min-w-0 flex-1"><span className="block truncate text-sm text-white/85">{item.title}</span><span className="mt-1 block truncate text-xs text-white/40">{item.courseName ?? "Course not specified"}</span></span><span className={`shrink-0 text-right text-xs ${item.dueAt && item.dueAt < now ? "text-rose-200" : "text-white/55"}`}>{item.dueAt && item.dueAt < now ? "Overdue" : dueLabel(item, now)}</span></Link>; }

export function AcademicCommandCenterHome() {
  const { snapshot, local, loading } = useSchool();
  const [now, setNow] = useState(() => new Date());
  const [selectedDay, setSelectedDay] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 60_000); return () => window.clearInterval(timer); }, []);
  const term = local.data.terms.find((item) => item.active) ?? local.data.terms[0];
  const courses = local.data.courses.filter((course) => !term || course.termId === term.id);
  const courseMap = new Map(courses.map((course) => [course.id, course]));
  const assignments = [...(snapshot?.planningAssignments ?? []), ...local.data.assignments.map((item) => localAssignmentToPlanning(item, item.courseId ? courseMap.get(item.courseId) : undefined))];
  const today = getSchoolToday(courses, term, assignments, snapshot?.events ?? [], now);
  const week = getSchoolWeek(courses, term, assignments, snapshot?.events ?? [], now);
  const upcoming = getUpcomingAssignments(assignments, now).slice(0, 6);
  const overdue = getOverdueAssignments(assignments, now).slice(0, 3);
  const nextClass = getNextClassToday(today.meetings, now);
  const proactivePlan = snapshot ? buildProactivePlan({ ...snapshot, planningAssignments: assignments }, now) : null;
  const assignmentById = new Map(assignments.map((item) => [item.id, item]));
  const nextByCourse = new Map(courses.map((course) => [course.id, projectCourseMeetings([course], term, now, 7).find((meeting) => meeting.start >= now)]));
  if (loading) return <div className="space-y-4"><div className={`${panel} h-28 animate-pulse bg-white/[0.03]`} /><div className="grid gap-4 md:grid-cols-2"><div className={`${panel} h-64 animate-pulse bg-white/[0.03]`} /><div className={`${panel} h-64 animate-pulse bg-white/[0.03]`} /></div></div>;
  const nextState = nextClass ? nextClass.start <= now && nextClass.end > now ? "IN CLASS NOW" : "NEXT CLASS" : "NO MORE CLASSES TODAY";
  const weekMeetingDays = new Set(week.meetings.map((item) => item.start.getDay()));
  const weekDueDays = new Set(week.assignments.flatMap((item) => item.dueAt ? [item.dueAt.getDay()] : []));
  const weekEventDays = new Set(week.events.map((item) => item.start.getDay()));
  return <div className="space-y-6">
    {proactivePlan && <section className={`${panel} border-emerald-200/15 p-5`}><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-emerald-200/70">Proactive planning</p><h2 className="mt-1 text-xl font-semibold text-white">Today’s plan</h2><p className="mt-1 text-sm text-white/45">Derived work dates protect your Canvas deadlines.</p></div><span className="text-xs text-emerald-100/80">{proactivePlan.shouldNotifyToday ? "Needs attention today" : "On track"}</span></div><div className="mt-4 grid gap-2 md:grid-cols-2">{proactivePlan.workBlocks.filter((block) => block.date.toDateString() === now.toDateString()).map((block) => { const item = assignmentById.get(block.assignmentId); const plan = proactivePlan.assignments.find((entry) => entry.assignmentId === block.assignmentId); return item ? <Link key={`${block.assignmentId}:${block.date.toISOString()}`} href={`/school/assignments/${encodeURIComponent(item.id)}`} className="rounded-xl bg-white/[0.04] p-3"><div className="flex justify-between gap-3"><span className="text-sm text-white/85">{item.title}</span><span className="text-sm font-semibold text-emerald-100">{block.minutes} min</span></div><p className="mt-1 text-xs text-amber-100/70">{plan?.urgency ?? "START SOON"} · {block.reason}</p></Link> : null; })}{!proactivePlan.workBlocks.some((block) => block.date.toDateString() === now.toDateString()) && <p className="text-sm text-white/45">No work blocks recommended today.</p>}</div></section>}
    <header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-sky-200/55">School</p><h1 className="mt-2 text-4xl font-black tracking-[-0.045em] text-white">{term?.name ?? "Academic Command Center"}</h1><p className="mt-2 text-sm text-white/45">{now.toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}</p></div><nav aria-label="School quick actions" className="flex flex-wrap gap-2"><Link href="/school/notes/new" className="rounded-xl bg-sky-200/15 px-3.5 py-2.5 text-sm font-semibold text-sky-50 transition hover:bg-sky-200/25">Add Note</Link><Link href="/school/assignments" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3.5 py-2.5 text-sm text-white/70 transition hover:bg-white/[0.05]"><ListChecks className="size-4" /> Assignments</Link><Link href="/school/calendar" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3.5 py-2.5 text-sm text-white/70 transition hover:bg-white/[0.05]"><CalendarDays className="size-4" /> Calendar</Link></nav></header>
    <section className={`${panel} overflow-hidden border-sky-200/20 bg-gradient-to-br from-sky-200/[0.12] to-white/[0.03] p-6`}><p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-sky-200/70">{nextState}</p>{nextClass ? <div className="mt-3 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold text-white">{courseLabel(nextClass.course)}</h2><p className="mt-2 flex items-center gap-2 text-sm text-white/60"><Clock3 className="size-4" />{localTime(nextClass.start)}–{localTime(nextClass.end)}</p>{(nextClass.meeting.location ?? nextClass.course.location) && <p className="mt-2 flex items-center gap-2 text-sm text-white/60"><MapPin className="size-4" />{nextClass.meeting.location ?? nextClass.course.location}</p>}</div><p className="text-lg font-semibold text-sky-100">{nextClass.start <= now ? "In progress" : relative(Math.max(0, Math.ceil((nextClass.start.getTime() - now.getTime()) / 60_000)))}</p></div> : <p className="mt-3 text-sm text-white/50">{today.meetings.length ? "No more classes today." : "No classes today."}</p>}</section>
    <section className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><div className={`${panel} overflow-hidden`}><div className="p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-sky-200/60">Today</p><h2 className="mt-1 text-xl font-semibold text-white">Your day at a glance</h2></div>{today.meetings.map((item) => <div key={item.id} className="flex items-center gap-3 border-t border-white/[0.07] px-5 py-3"><Clock3 className="size-4 text-sky-200/70" /><span className="min-w-0 flex-1 truncate text-sm text-white/80">{item.course.name}</span><span className="text-xs text-white/50">{localTime(item.start)}–{localTime(item.end)}</span></div>)}{today.assignments.map((item) => <AssignmentItem key={item.id} item={item} now={now} />)}{today.events.map((item) => <div key={`${item.source}:${item.id}`} className="flex items-center gap-3 border-t border-white/[0.07] px-5 py-3"><CalendarDays className="size-4 text-violet-200/70" /><span className="min-w-0 flex-1 truncate text-sm text-white/80">{item.title}</span><span className="text-xs text-violet-100/60">Event</span></div>)}{!today.meetings.length && !today.assignments.length && !today.events.length && <p className="px-5 pb-5 text-sm text-white/45">Nothing scheduled or due today.</p>}</div><div className={`${panel} overflow-hidden`}><div className="flex items-center justify-between p-5"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-sky-200/60">Upcoming work</p><h2 className="mt-1 text-xl font-semibold text-white">Next 7 days</h2></div><Link href="/school/assignments" className="text-sm text-sky-100/70 hover:text-white">View all</Link></div>{overdue.map((item) => <AssignmentItem key={`overdue-${item.id}`} item={item} now={now} />)}{upcoming.map((item) => <AssignmentItem key={item.id} item={item} now={now} />)}{!overdue.length && !upcoming.length && <p className="px-5 pb-5 text-sm text-white/45">Nothing due in the next 7 days.</p>}</div></section>
    <section className={`${panel} p-5`}><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-sky-200/60">This week</p><h2 className="mt-1 text-xl font-semibold text-white">Monday–Sunday</h2></div><Link href="/school/schedule" className="text-sm text-sky-100/70 hover:text-white">Open schedule</Link></div><div className="mt-5 grid grid-cols-7 gap-1.5">{days.map((label, index) => { const day = ((week.start.getDay() - 1 + index) % 7) + 1; const normalized = day === 7 ? 0 : day; const selected = selectedDay === index; return <button type="button" key={label} onClick={() => setSelectedDay(index)} className={`rounded-xl px-1 py-2 text-center transition ${selected ? "bg-sky-200/20 text-white" : "text-white/45 hover:bg-white/[0.05]"}`}><span className="block text-[10px] font-semibold uppercase">{label}</span><span className="mt-1 block text-sm">{new Date(week.start.getFullYear(), week.start.getMonth(), week.start.getDate() + index).getDate()}</span><span className="mx-auto mt-2 flex justify-center gap-0.5" aria-label={`${label} activity`}>{weekMeetingDays.has(normalized) && <i className="size-1.5 rounded-full bg-sky-200" />}{weekDueDays.has(normalized) && <i className="size-1.5 rounded-full bg-amber-200" />}{weekEventDays.has(normalized) && <i className="size-1.5 rounded-full bg-violet-200" />}</span></button>; })}</div><div className="mt-5 space-y-2">{[...week.meetings.map((item) => ({ key: item.id, date: item.start, label: item.course.name, detail: `${localTime(item.start)} · Class` })), ...week.assignments.map((item) => ({ key: item.id, date: item.dueAt!, label: item.title, detail: `${localTime(item.dueAt!)} · Due` })), ...week.events.map((item) => ({ key: `${item.source}:${item.id}`, date: item.start, label: item.title, detail: `${localTime(item.start)} · Event` }))].filter((item) => item.date.getDay() === (selectedDay === 6 ? 0 : selectedDay + 1) && item.date >= now).slice(0, 4).map((item) => <div key={item.key} className="flex items-center gap-3 rounded-xl bg-white/[0.03] px-3 py-2.5"><span className="text-xs text-white/40">{localTime(item.date)}</span><span className="min-w-0 flex-1 truncate text-sm text-white/75">{item.label}</span><span className="text-xs text-white/40">{item.detail.split(" · ")[1]}</span></div>)}{![...week.meetings, ...week.assignments, ...week.events].some((item) => { const date = "start" in item ? item.start : item.dueAt; return date && date.getDay() === (selectedDay === 6 ? 0 : selectedDay + 1) && date >= now; }) && <p className="text-sm text-white/40">No remaining items on {days[selectedDay]}.</p>}</div></section>
    <section><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-sky-200/60">Courses</p><h2 className="mt-1 text-xl font-semibold text-white">Your active courses</h2></div><Link href="/school/courses" className="text-sm text-sky-100/70 hover:text-white">View courses</Link></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{courses.map((course) => { const nextMeeting = nextByCourse.get(course.id); const nextAssignment = upcoming.find((item) => item.courseId === course.id || item.courseName === course.name || item.courseName === course.code); return <Link key={course.id} href={`/school/courses/${encodeURIComponent(course.id)}`} className={`${panel} group p-4 transition hover:-translate-y-0.5 hover:border-sky-200/25`}><div className="flex items-start justify-between"><BookOpen className="size-5 text-sky-200/70" /><span className="text-white/30 transition group-hover:text-white/70">→</span></div><p className="mt-4 text-xs uppercase tracking-[0.15em] text-sky-100/55">{course.code ?? "Course"}</p><h3 className="mt-1 font-semibold text-white">{course.name}</h3>{course.instructor && <p className="mt-2 text-xs text-white/45">{course.instructor}</p>}{nextMeeting && <p className="mt-3 text-xs text-white/60">Next meeting · {days[nextMeeting.start.getDay() === 0 ? 6 : nextMeeting.start.getDay() - 1]} {localTime(nextMeeting.start)}</p>}{nextAssignment && <p className="mt-1 truncate text-xs text-white/40">Next work · {nextAssignment.title}</p>}</Link>})}{!courses.length && <div className={`${panel} p-5 text-sm text-white/45`}>No active courses configured.</div>}</div></section>
  </div>;
}
