"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { getAfrotcBriefing, type AfrotcBriefingEvent } from "@/services/school/opord/briefing";
import type { OpordDocument } from "@/services/school/opord/types";
import type { OpordSource } from "@/services/school/opord/selectors";

const profileKey = "cosmic.afrotc.cadet-category";
type ApiSource = OpordSource & { title: string; originalFileName: string | null; document: OpordDocument };
function value(field: AfrotcBriefingEvent["event"]["reportTime"] | AfrotcBriefingEvent["event"]["startTime"]) { return field.status === "explicit" ? field.value : "Not specified"; }
function label(event: AfrotcBriefingEvent) { return event.event.type === "pt" ? "PT" : event.event.type === "llab" ? "LLAB" : "AFROTC"; }
function Brief({ item }: { item: AfrotcBriefingEvent }) { return <div className="mt-4 rounded-xl border border-white/10 bg-black/10 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-violet-200/70">{label(item)} · {item.moment}</p><h3 className="mt-1 font-semibold text-white">{item.event.title}</h3></div><Link href={`/school/opords/${encodeURIComponent(item.source.id)}#${item.event.id}`} className="text-xs text-violet-100/80">View event →</Link></div><div className="mt-3 grid gap-2 text-sm text-white/70 sm:grid-cols-2"><p><span className="text-white/40">Wear:</span> {item.uniform ?? (item.event.uniformRequirements.length ? "Unable to resolve your UOD from this OPORD." : "Uniform not resolved")}</p><p><span className="text-white/40">Report:</span> {value(item.event.reportTime)}</p><p><span className="text-white/40">Start:</span> {value(item.event.startTime)}</p><p><span className="text-white/40">Location:</span> {item.location ?? "Not specified"}</p></div>{item.bring.length ? <div className="mt-3"><p className="text-xs uppercase tracking-[0.16em] text-white/40">Bring</p>{item.bring.map((thing) => <p key={thing} className="mt-1 text-sm text-white/70">☐ {thing}</p>)}</div> : null}{item.workoutTitle ? <div className="mt-3"><p className="text-xs uppercase tracking-[0.16em] text-emerald-100/65">PT · {item.workoutTitle}</p>{item.workoutSummary.length ? <p className="mt-1 text-sm text-white/65">{item.workoutSummary.join(" · ")}</p> : null}{item.pfraFocus.length ? <p className="mt-1 text-xs text-emerald-100/65">PFRA focus · {item.pfraFocus.join(" · ")}</p> : null}</div> : null}</div>; }

export function AfrotcOpordCard() { const [sources, setSources] = useState<ApiSource[]>([]); const [category] = useState(() => typeof window === "undefined" ? "" : window.localStorage.getItem(profileKey) ?? ""); useEffect(() => { const load = () => { void fetch("/api/school/opords", { cache: "no-store" }).then((response) => response.ok ? response.json() : null).then((body: { sources?: ApiSource[] } | null) => setSources(body?.sources ?? [])).catch(() => setSources([])); }; load(); const timer = window.setInterval(load, 60_000); return () => window.clearInterval(timer); }, []); const briefing = getAfrotcBriefing(sources, category); if (briefing.status === "none") return <section className="rounded-[1.35rem] border border-violet-200/15 bg-violet-200/[0.06] p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-violet-200/70">AFROTC awareness</p><p className="mt-2 text-sm text-white/55">No current or upcoming AFROTC event is available.</p><Link href="/school/opords" className="mt-3 inline-block text-sm text-violet-100/80">Open OPORDs →</Link></section>; return <section className="rounded-[1.35rem] border border-violet-200/15 bg-violet-200/[0.06] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-violet-200/70">{briefing.status === "today" ? "AFROTC this morning" : briefing.status === "tomorrow" ? "AFROTC tomorrow" : "Next AFROTC event"}</p><h2 className="mt-1 text-xl font-semibold text-white">{briefing.event?.event.title}</h2></div><Link href="/school/opords" className="text-sm text-violet-100/80">OPORDs →</Link></div>{briefing.event ? <Brief item={briefing.event} /> : null}{briefing.tomorrowEvent ? <div className="mt-4"><p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-violet-200/60">Tomorrow</p><Brief item={briefing.tomorrowEvent} /></div> : null}{briefing.status === "today" && briefing.nextEvent ? <p className="mt-3 text-xs text-white/45">Next: {briefing.nextEvent.event.title}</p> : null}</section>; }
