"use client";

import { useEffect, useState } from "react";
import { fieldClass, primaryClass } from "./SchoolModal";

const button = "rounded-xl border border-white/10 px-3 py-2 text-sm text-white/65 hover:bg-white/10 disabled:opacity-40";

export default function CanvasAcademicConnection() {
  const [baseUrl, setBaseUrl] = useState("https://usu.instructure.com"); const [token, setToken] = useState(""); const [status, setStatus] = useState("not_connected"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void fetch("/api/school/canvas/academic", { cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error(); const data = await response.json() as { status?: string }; setStatus(data.status ?? "not_connected"); }).catch(() => setMessage("Canvas Academic Data status is unavailable.")); }, []);
  async function connect() { setBusy(true); setMessage(""); try { const response = await fetch("/api/school/canvas/academic", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ baseUrl, token }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Canvas credentials could not be validated."); setToken(""); setStatus("connected"); setMessage("Canvas Academic API connected."); window.dispatchEvent(new Event("cosmic:school-refresh")); } catch (error) { setMessage(error instanceof Error ? error.message : "Canvas connection failed."); } finally { setBusy(false); } }
  async function sync() { setBusy(true); setMessage(""); try { const response = await fetch("/api/school/canvas/academic", { method: "POST" }); const body = await response.json() as { error?: string; courses?: number; assignments?: number; truncated?: boolean }; if (!response.ok) throw new Error(body.error ?? "Canvas sync failed."); setMessage(`Canvas synced · ${body.courses ?? 0} courses · ${body.assignments ?? 0} assignments${body.truncated ? " · safety limit reached" : ""}.`); window.dispatchEvent(new Event("cosmic:school-refresh")); } catch (error) { setStatus("error"); setMessage(error instanceof Error ? error.message : "Canvas sync failed."); } finally { setBusy(false); } }
  return <div className="mb-6 rounded-2xl border border-violet-200/10 bg-violet-200/[0.04] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-white">Canvas Academic API</h2><p className="mt-1 text-sm text-white/50">{status === "connected" ? "Connected" : status === "error" ? "Sync error" : "Institution access required"}</p></div><button type="button" disabled={busy || status !== "connected"} onClick={() => void sync()} className={button}>Sync Canvas</button></div><p className="mt-3 text-xs leading-5 text-white/40">Your institution may restrict personal Canvas API tokens. USU currently limits self-service token creation; an institution-approved integration may be required. Cosmic never asks for your USU password, A-number, or SSO credentials. The optional token is encrypted and never returned to this page.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><input type="url" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} placeholder="https://usu.instructure.com" className={fieldClass} aria-label="Canvas base URL" /><input type="password" value={token} onChange={(event) => setToken(event.target.value)} placeholder="Personal access token" className={fieldClass} aria-label="Canvas personal access token" autoComplete="new-password" /></div><button type="button" disabled={busy || !token.trim()} onClick={() => void connect()} className={`mt-3 ${primaryClass}`}>{busy ? "Validating…" : "Connect Academic API"}</button>{message && <p className="mt-3 text-sm text-amber-100/75" role="status">{message}</p>}</div>;
}
