"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useSchool } from "./context/SchoolDataContext";
type Note = { id: string; title: string; content: string; courseId?: string | null; topics?: unknown; classDate?: string | null };
const field = "mt-2 w-full rounded-xl border border-white/10 bg-black/15 px-3 py-2.5 text-sm text-white outline-none focus:border-sky-200/50";
export default function NoteEditor({ noteId }: { noteId?: string }) { const router = useRouter(); const { local } = useSchool(); const [note, setNote] = useState<Note>({ id: "", title: "", content: "", courseId: "", topics: [], classDate: "" }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!noteId) return; void fetch(`/api/school/notes/${encodeURIComponent(noteId)}`, { cache: "no-store" }).then((res) => res.json()).then((body: { note?: Note; error?: string }) => { if (!body.note) throw new Error(body.error); setNote({ ...body.note, topics: Array.isArray(body.note.topics) ? body.note.topics : [] }); }).catch((err: unknown) => setError(err instanceof Error ? err.message : "Note unavailable.")); }, [noteId]);
  async function save() { if (!note.title.trim() || !note.content.trim()) return setError("Title and content are required."); setSaving(true); setError(""); const payload = { title: note.title, content: note.content, courseId: note.courseId ?? "", classDate: note.classDate || undefined, topics: Array.isArray(note.topics) ? note.topics : [] }; const res = await fetch(noteId ? `/api/school/notes/${encodeURIComponent(noteId)}` : "/api/school/notes", { method: noteId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await res.json() as { note?: Note; error?: string }; setSaving(false); if (!res.ok) return setError(body.error ?? "Could not save note."); if (!noteId && body.note) router.push(`/school/notes/${body.note.id}`); }
  async function remove() { if (!noteId || !window.confirm("Delete this note?")) return; await fetch(`/api/school/notes/${encodeURIComponent(noteId)}`, { method: "DELETE" }); router.push("/school/notes"); }
  return <div className="mx-auto max-w-3xl space-y-5"><Link href="/school/notes" className="text-sm text-white/45">← Notes</Link><section className="rounded-[1.35rem] border border-white/[0.09] bg-[#101c35]/75 p-5"><p className="text-[11px] uppercase tracking-[0.24em] text-sky-200/55">{noteId ? "Edit note" : "Manual note"}</p><h1 className="mt-2 text-3xl font-black text-white">{noteId ? note.title || "Edit note" : "Add a study note"}</h1><div className="mt-6 grid gap-4"><label className="text-sm text-white/65">Title<input className={field} value={note.title} onChange={(e) => setNote({ ...note, title: e.target.value })} /></label><label className="text-sm text-white/65">Course<select className={field} value={note.courseId ?? ""} onChange={(e) => setNote({ ...note, courseId: e.target.value })}><option value="">General study note</option>{local.data.courses.map((course) => <option key={course.id} value={course.id}>{course.code ? `${course.code} · ` : ""}{course.name}</option>)}</select></label><label className="text-sm text-white/65">Class date<input type="date" className={field} value={note.classDate ? note.classDate.slice(0, 10) : ""} onChange={(e) => setNote({ ...note, classDate: e.target.value })} /></label><label className="text-sm text-white/65">Topics <span className="text-white/35">(comma separated)</span><input className={field} value={Array.isArray(note.topics) ? note.topics.join(", ") : ""} onChange={(e) => setNote({ ...note, topics: e.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} /></label><label className="text-sm text-white/65">Content<textarea className={field} rows={12} value={note.content} onChange={(e) => setNote({ ...note, content: e.target.value })} /></label></div>{error && <p className="mt-4 text-sm text-red-200">{error}</p>}<div className="mt-6 flex flex-wrap justify-end gap-3"><Link href="/school/notes" className="rounded-xl border border-white/10 px-4 py-2.5 text-sm text-white/65">Cancel</Link>{noteId && <button type="button" onClick={() => void remove()} className="rounded-xl border border-red-200/20 px-4 py-2.5 text-sm text-red-200/75">Delete</button>}<button type="button" disabled={saving} onClick={() => void save()} className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-slate-950">{saving ? "Saving…" : "Save note"}</button></div></section></div>;
}
