"use client";

import { useState } from "react";

export default function SchoolEmailImport() {
  const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/school/email/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ importId: crypto.randomUUID(), sender: form.get("sender"), subject: form.get("subject"), receivedAt: form.get("receivedAt"), body: form.get("body"), to: form.get("to"), cc: form.get("cc") }) }); const body = await response.json() as { message?: string; error?: string }; if (!response.ok) throw new Error(body.error ?? "Email import failed."); setMessage(body.message ?? "Email imported."); event.currentTarget.reset(); setOpen(false); } catch (error) { setMessage(error instanceof Error ? error.message : "Email import failed."); } finally { setBusy(false); } }
  return <div className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-white">Manual Email Import</h2><p className="mt-1 text-sm text-white/50">Paste a school-related email for the same review-first School analysis.</p></div><button type="button" onClick={() => setOpen((value) => !value)} className="rounded-xl border border-white/10 px-3 py-2 text-sm text-white/70">{open ? "Close" : "Import Email"}</button></div>{message && <p className="mt-3 text-sm text-emerald-100/75" role="status">{message}</p>}{open && <form onSubmit={(event) => void submit(event)} className="mt-4 grid gap-3 sm:grid-cols-2"><input name="sender" placeholder="From" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white" /><input name="subject" placeholder="Subject" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white" /><input name="receivedAt" type="datetime-local" required className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white" /><input name="to" placeholder="To (optional)" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white" /><input name="cc" placeholder="CC (optional)" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white" /><textarea name="body" required maxLength={50000} placeholder="Paste email body" className="min-h-40 rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white sm:col-span-2" /><p className="text-xs text-white/40 sm:col-span-2">Cosmic does not connect to Outlook Web or store your Microsoft credentials. Imported emails are analyzed for School updates and placed in review.</p><button disabled={busy} className="rounded-xl border border-violet-200/20 bg-violet-300/10 px-3 py-2 text-sm text-violet-100 sm:col-span-2">{busy ? "Analyzing…" : "Analyze Email"}</button></form>}</div>;
}
