"use client";

import { useState } from "react";
import type { SchoolTerm } from "@/core/contracts/School";
import { useSchool } from "./context/SchoolDataContext";
import SchoolBreadcrumbs from "./layout/SchoolBreadcrumbs";
import { AssignmentsView, CoursesView, GoalsView, GradesView, ResourcesView, ScheduleView } from "./SchoolCrudViews";
import { fieldClass, primaryClass, SchoolConfirm } from "./SchoolModal";

type Section = "Courses" | "Assignments" | "Grades" | "Schedule" | "Goals" | "Resources" | "AFROTC" | "Settings";

export default function SchoolSection({ section }: { section: Section }) {
  const { error, local } = useSchool();
  if (!local.ready) return <p className="py-16 text-white/60">Loading School…</p>;
  return <section className="space-y-6"><SchoolBreadcrumbs currentPage={section} /><header><h1 className="text-3xl font-bold tracking-tight text-white">{section}</h1><p className="mt-2 text-sm text-white/55">{section === "Assignments" ? "Manage local work alongside read-only Canvas assignments." : section === "Schedule" ? "Your configured weekly class schedule." : `${section} for your local School workspace.`}</p>{error && <p className="mt-2 text-xs text-amber-100/70">Canvas data is temporarily unavailable. Local School tools remain available.</p>}</header>{section === "Courses" ? <CoursesView /> : section === "Assignments" ? <AssignmentsView /> : section === "Grades" ? <GradesView /> : section === "Schedule" ? <ScheduleView /> : section === "Goals" ? <GoalsView /> : section === "Resources" ? <ResourcesView /> : section === "Settings" ? <SettingsView /> : <div className="rounded-2xl border border-white/10 bg-white/5 p-6 text-sm text-white/55">No AFROTC information is configured. AFROTC resources can be stored from the Resources page.</div>}</section>;
}

function parseLocalDate(value: string) { const [year, month, day] = value.split("-").map(Number); return [year, month, day].every(Number.isInteger) ? new Date(year, month - 1, day) : null; }
function SettingsView() { const { local } = useSchool(); const [name, setName] = useState(""); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [error, setError] = useState<string | null>(null); const [confirmReset, setConfirmReset] = useState(false); function save() { const startDate = parseLocalDate(start); const endDate = parseLocalDate(end); if (!name.trim() || !startDate || !endDate || endDate <= startDate) { setError("Enter a term name and an end date after the start date."); return; } local.saveTerm({ id: crypto.randomUUID(), name: name.trim(), startDate, endDate, active: local.data.terms.length === 0 }); setName(""); setStart(""); setEnd(""); setError(null); }
  return <><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold text-white">Academic Terms</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-sm text-white/65">Term name<input value={name} onChange={(event) => setName(event.target.value)} className={fieldClass} /></label><label className="text-sm text-white/65">Start date<input type="date" value={start} onChange={(event) => setStart(event.target.value)} className={`${fieldClass} [color-scheme:dark]`} /></label><label className="text-sm text-white/65">End date<input type="date" value={end} onChange={(event) => setEnd(event.target.value)} className={`${fieldClass} [color-scheme:dark]`} /></label></div>{error && <p className="mt-3 text-sm text-red-200">{error}</p>}<button type="button" onClick={save} className={`mt-4 ${primaryClass}`}>Create Term</button></div><div className="space-y-2">{local.data.terms.map((term: SchoolTerm) => <div key={term.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3"><span className="text-white/75">{term.name}{term.active ? " · Active" : ""}</span><button type="button" onClick={() => local.setActiveTerm(term.id)} className={primaryClass}>Set Active</button></div>)}</div><div className="rounded-2xl border border-red-300/10 bg-red-300/5 p-5"><h2 className="font-semibold text-red-100">Reset Local School Data</h2><p className="mt-2 text-sm text-white/55">Removes local terms, courses, meetings, assignments, grades, goals, and resources. Canvas, Apple Calendar, Gmail, and other Cosmic data are unchanged.</p><button type="button" onClick={() => setConfirmReset(true)} className="mt-4 rounded-xl border border-red-300/20 px-4 py-2 text-sm text-red-100">Reset Local Data</button></div>{confirmReset && <SchoolConfirm title="Reset Local School Data?" message="This permanently removes all locally entered School data. Canvas and other Cosmic systems are not affected." onCancel={() => setConfirmReset(false)} onConfirm={() => { local.reset(); setConfirmReset(false); }} />}</>;
}
