"use client";

import { useEffect, useState } from "react";

type Proposal = { id: string; title: string; description: string; evidence: string; confidence: number; status: string; error?: string; };
const button = "rounded-xl border border-white/10 px-3 py-2 text-sm text-white/65 hover:bg-white/10 disabled:opacity-40";

export default function SchoolEmailUpdates() {
  const [items, setItems] = useState<Proposal[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { const statuses = ["pending", "applied", "dismissed", "needs_target", "failed"]; const results = await Promise.all(statuses.map((status) => fetch(`/api/school/email/proposals?status=${status}`, { cache: "no-store" }))); const proposals = (await Promise.all(results.filter((response) => response.ok).map(async (response) => ((await response.json()) as { proposals?: Proposal[] }).proposals ?? []))).flat(); setItems(proposals); }
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch(() => setMessage("School updates are unavailable.")); }, 0); return () => window.clearTimeout(timer); }, []);
  async function scan() { setBusy(true); setMessage(""); try { const response = await fetch("/api/school/email/scan", { method: "POST" }); const body = await response.json() as { error?: string; scanned?: number; relevant?: number; proposals?: number }; if (!response.ok) throw new Error(body.error ?? "School email scan failed."); setMessage(`Scanned ${body.scanned ?? 0} messages · ${body.relevant ?? 0} relevant · ${body.proposals ?? 0} new updates.`); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "School email scan failed."); } finally { setBusy(false); } }
  async function decide(id: string, status: "approved" | "dismissed") { const response = await fetch(`/api/school/email/proposals/${encodeURIComponent(id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const body = await response.json() as { proposal?: Proposal }; if (response.ok) { setMessage(body.proposal?.status === "applied" ? "School update applied." : body.proposal?.error ?? "That update needs attention before it can be applied."); await load(); } else setMessage("That School update could not be changed."); }
  return <section className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold text-white">School Updates</h1><p className="mt-2 text-sm text-white/55">Review relevant Gmail updates before they affect School planning.</p></div><button type="button" onClick={() => void scan()} disabled={busy} className={button}>{busy ? "Scanning…" : "Scan School Email"}</button></div>{message && <p className="text-sm text-amber-100/75" role="status">{message}</p>}{items.length ? items.map((item) => <article key={item.id} className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-xs uppercase tracking-widest text-violet-200/60">{item.status === "needs_target" ? "Needs attention" : item.status} · {Math.round(item.confidence * 100)}% confidence</p><h2 className="mt-2 font-semibold text-white">{item.title}</h2><p className="mt-2 text-sm text-white/65">{item.description}</p><p className="mt-3 rounded-xl border border-white/10 bg-black/15 p-3 text-sm text-white/55">“{item.evidence}”</p>{item.error && <p className="mt-3 text-sm text-amber-100/75">{item.error}</p>}{item.status === "pending" && <div className="mt-4 flex gap-2"><button type="button" onClick={() => void decide(item.id, "approved")} className={button}>Approve</button><button type="button" onClick={() => void decide(item.id, "dismissed")} className={button}>Dismiss</button></div>}</article>) : <p className="rounded-2xl border border-white/10 bg-white/5 p-5 text-sm text-white/55">No School updates are waiting for review.</p>}</section>;
}
