"use client";

import { Inbox, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import SourcesView from "./SourcesView";

/** Intake-first presentation over the existing, owner-scoped School Sources pipeline. */
export default function SchoolInboxView() {
  return <div className="space-y-6"><header><p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-sky-200/55">School / Inbox</p><div className="mt-2 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-sky-300/10 text-sky-100"><Inbox className="size-5" /></span><div><h1 className="text-4xl font-black tracking-[-0.045em] text-white">School inbox</h1><p className="mt-1 text-sm text-white/45">Give Cosmic the material you receive. Review findings before they enter School.</p></div></div></header><section className="grid gap-3 md:grid-cols-3"><InboxNote icon={<Sparkles />} title="Extract" body="Text is normalized and checked for evidence-supported facts, events, and actions." /><InboxNote icon={<ShieldCheck />} title="Review first" body="Meaningful academic changes remain proposals until you approve them." /><InboxNote icon={<Inbox />} title="One source of truth" body="Approved intelligence flows back through School Sources and SchoolSnapshot." /></section><ImageQuickUpload /><SourcesView /></div>;
}

function ImageQuickUpload() { const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); async function upload(file: File) { setBusy(true); setMessage(""); try { const form = new FormData(); form.set("file", file); const response = await fetch("/api/school/sources/upload", { method: "POST", body: form }); const body = await response.json() as { source?: { id?: string }; error?: string }; if (!response.ok) throw new Error(body.error ?? "Image upload failed."); setMessage(body.source?.id ? "Image retained and queued for analysis. Open it from the source library to review findings." : "Image uploaded."); } catch (error) { setMessage(error instanceof Error ? error.message : "Image upload failed."); } finally { setBusy(false); } } return <section className="rounded-[1.35rem] border border-sky-200/15 bg-sky-200/[0.055] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-sky-200/55">Image intake</p><h2 className="mt-1 text-lg font-semibold text-white">Drop a class note or Canvas screenshot</h2><p className="mt-1 text-sm text-white/45">PNG · JPEG · WEBP · camera-ready on mobile</p></div><label className="cursor-pointer rounded-xl bg-sky-200/15 px-4 py-2.5 text-sm font-semibold text-sky-50 hover:bg-sky-200/25">{busy ? "Analyzing…" : "Choose image"}<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp,.png,.jpg,.jpeg,.webp" capture="environment" disabled={busy} onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); event.currentTarget.value = ""; }} /></label></div>{message && <p role="status" className="mt-3 text-sm text-sky-100/75">{message}</p>}</section>; }

function InboxNote({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) { return <div className="rounded-[1.25rem] border border-white/[0.09] bg-[#101c35]/65 p-4"><span className="text-sky-100/65">{icon}</span><h2 className="mt-3 text-sm font-semibold text-white/85">{title}</h2><p className="mt-1 text-xs leading-5 text-white/40">{body}</p></div>; }
