import { NextResponse } from "next/server";
import { requireSchoolAccess } from "@/services/school/access";
import { createSchoolSourceRecord } from "@/services/school/sources/repository";
import { createSchoolAsset } from "@/services/school/assetRepository";
import { getSchoolAssetStore } from "@/services/school/sources/storage";
import { createSchoolAudioTranscript } from "@/services/school/audioRepository";
import { processSchoolAudio } from "@/services/school/audioProcessing";
import { validateSchoolAudio } from "@/services/school/audio";
import { assertSameOrigin } from "@/services/security/origin";

export async function POST(request: Request) {
  try { assertSameOrigin(request); const account = await requireSchoolAccess(request); const form = await request.formData(); const file = form.get("file"); if (!(file instanceof File)) return NextResponse.json({ error: "A recording is required." }, { status: 400 }); const bytes = new Uint8Array(await file.arrayBuffer()); const mime = validateSchoolAudio({ type: file.type, name: file.name, size: file.size }, bytes); const sourceId = crypto.randomUUID(); const assetId = crypto.randomUUID(); const transcriptId = crypto.randomUUID(); const title = typeof form.get("title") === "string" ? String(form.get("title")).trim().slice(0, 500) : ""; const safeName = `${assetId}${file.name.toLowerCase().match(/\.(mp3|m4a|wav|webm|aac|ogg)$/)?.[0] ?? ".audio"}`; const source = await createSchoolSourceRecord({ id: sourceId, userId: account.id, title: title || "Voice recording", sourceType: "voice-recording", courseId: typeof form.get("courseId") === "string" && String(form.get("courseId")).trim() ? String(form.get("courseId")).trim() : null, originalFileName: file.name.slice(0, 160), mimeType: mime, fileSize: file.size, processingStatus: "uploaded" }); const stored = await getSchoolAssetStore().put({ accountId: account.id, sourceId, bytes, mimeType: mime, safeFileName: safeName }); await createSchoolAsset({ id: assetId, userId: account.id, sourceId, originalFileName: file.name.slice(0, 160), safeFileName: safeName, mimeType: mime, size: file.size, storageProvider: stored.provider, storageKey: stored.key }); await createSchoolAudioTranscript({ id: transcriptId, userId: account.id, sourceId, assetId, courseId: source.courseId, title: title || null, status: "uploaded" }); const job = await processSchoolAudio(account.id, transcriptId); return NextResponse.json({ voiceNote: job, sourceId, status: job?.status ?? "uploaded" }, { status: 201 }); } catch (error) { if (error instanceof Response) return error; return NextResponse.json({ error: error instanceof Error ? error.message : "Recording could not be saved." }, { status: 422 }); }
}
