import { NextResponse } from "next/server";
import { requireAdmin } from "@/services/admin/auth";
import { assertSameOrigin } from "@/services/security/origin";
import { deleteAccountSafely, getAdminAccount, recordAudit } from "@/services/admin/repository";
import { getAccountEntitlements } from "@/services/entitlements/service";

export const dynamic = "force-dynamic";
export async function GET(request: Request, context: { params: Promise<{ accountId: string }> }) { try { await requireAdmin(request); const { accountId } = await context.params; const account = await getAdminAccount(accountId); return account ? NextResponse.json({ ...account, effectivePlan: (await getAccountEntitlements(accountId)).plan }, { headers: { "Cache-Control": "no-store" } }) : NextResponse.json({ error: "Account not found." }, { status: 404 }); } catch (error) { if (error instanceof Response) return error; return NextResponse.json({ error: "Account detail unavailable." }, { status: 503 }); } }
export async function DELETE(request: Request, context: { params: Promise<{ accountId: string }> }) { try { assertSameOrigin(request); const actor = await requireAdmin(request); const { accountId } = await context.params; const body = await request.json().catch(() => null) as { confirmation?: unknown; reason?: unknown } | null; const target = await getAdminAccount(accountId); if (!target) return NextResponse.json({ error: "Account not found." }, { status: 404 }); if (accountId === actor.id) return NextResponse.json({ error: "Self-deletion is disabled in the Admin Console." }, { status: 400 }); if (body?.confirmation !== `DELETE ${target.user.email}`) return NextResponse.json({ error: `Type DELETE ${target.user.email} to confirm.` }, { status: 400 }); const deleted = await deleteAccountSafely(accountId); if (!deleted) return NextResponse.json({ error: "Account could not be deleted." }, { status: 409 }); await recordAudit(actor.id, accountId, "account.delete", { reason: typeof body?.reason === "string" ? body.reason.slice(0, 300) : null }); return new Response(null, { status: 204 }); } catch (error) { if (error instanceof Response) return error; return NextResponse.json({ error: error instanceof Error ? error.message : "Account deletion unavailable." }, { status: 409 }); } }
