"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { SportsEvent, SportsTeam } from "@/core/contracts/Sports";
import type { FootballLiveData, FootballPlay } from "@/core/contracts/sports/Football";
import type { BasketballLiveData } from "@/core/contracts/sports/Basketball";
import type { CollegeFootballLiveData } from "@/services/sports/providers/college-football-detail";
import { useSportsEvent } from "@/hooks/os/useSportsEvent";
import { findNewTouchdown, touchdownKey } from "@/services/sports/football/celebration";
import MlbEventCenter from "@/components/apps/sports/event/MlbEventCenter";
import SportsTeamLogo from "@/components/apps/sports/SportsTeamLogo";
import FootballField from "@/components/apps/sports/event/FootballField";
import FootballCelebration from "@/components/apps/sports/event/FootballCelebration";
import MotorsportTrackMap from "@/components/apps/sports/MotorsportTrackMap";

const panel = "rounded-3xl border border-white/10 bg-white/[0.045] p-5";
const label = "text-[11px] uppercase tracking-[0.2em] text-cyan-100/45";
const statusText = (status: SportsEvent["status"]) => status === "scheduled" ? "Upcoming" : status.charAt(0).toUpperCase() + status.slice(1);

function ScoreHeader({ event, scoreOverride }: { event: SportsEvent; scoreOverride?: { away?: number; home?: number } }) {
  const away = event.awayTeam; const home = event.homeTeam;
  return <section className={`${panel} overflow-hidden bg-gradient-to-br from-cyan-300/[0.10] via-white/[0.045] to-transparent`}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className={label}>{event.sport.toUpperCase()} · {statusText(event.status)}</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-white sm:text-4xl">{event.title}</h1><p className="mt-2 text-sm text-white/45">{event.statusDetail ?? event.venue ?? event.start.toLocaleString()}</p></div><span className="rounded-full border border-white/12 bg-white/[0.07] px-3 py-1 text-xs uppercase tracking-wider text-white/65">{statusText(event.status)}</span></div>{away && home ? <div className="mt-7 grid grid-cols-[1fr_auto_1fr] items-end gap-3 text-center"><div><SportsTeamLogo sport={event.sport} team={away} size="lg"/><p className="mt-3 text-sm text-white/70">{away.abbreviation ?? away.name}</p><p className="mt-1 text-5xl font-semibold text-white sm:text-7xl">{scoreOverride?.away ?? away.score ?? "—"}</p></div><p className="pb-2 text-xs uppercase tracking-widest text-white/25">at</p><div><SportsTeamLogo sport={event.sport} team={home} size="lg"/><p className="mt-3 text-sm text-white/70">{home.abbreviation ?? home.name}</p><p className="mt-1 text-5xl font-semibold text-white sm:text-7xl">{scoreOverride?.home ?? home.score ?? "—"}</p></div></div> : null}</section>;
}

function PlayFeed({ plays, selected, onSelect }: { plays?: FootballPlay[]; selected?: string; onSelect: (play: FootballPlay) => void }) {
  return <section className={panel}><div className="flex items-center justify-between gap-3"><p className={label}>Play by play</p><span className="text-xs text-white/35">Select a play to restore its field state</span></div><div className="mt-3 space-y-2">{plays?.slice().reverse().map((play, index) => <button type="button" key={play.id ?? `${play.sequence ?? "play"}-${index}`} onClick={() => onSelect(play)} className={`block w-full rounded-xl border-l-2 p-3 text-left transition ${selected === play.id ? "border-cyan-200 bg-cyan-200/[.08]" : "border-white/15 hover:bg-white/[.05]"}`}><p className="text-sm leading-6 text-white/75">{play.description}</p><p className="mt-1 text-xs text-white/35">{play.clock ?? ""}{play.downDistanceText ? ` · ${play.downDistanceText}` : ""}{play.scoringPlay ? " · Scoring play" : ""}</p></button>)}{!plays?.length ? <p className="text-sm text-white/38">Provider play data is unavailable.</p> : null}</div></section>;
}

function SituationCard({ live, situation }: { live: FootballLiveData; situation: FootballLiveData["situation"] }) {
  const rows = [["Down & distance", situation.shortDownDistanceText ?? situation.downDistanceText], ["Quarter / game clock", `Q${situation.quarter ?? "—"}${situation.clock ? ` · ${situation.clock}` : ""}`], ["Play clock", situation.playClock], ["Possession", situation.possessionText ?? situation.possessionTeamAbbreviation], ["Red zone", situation.redZone === undefined ? undefined : situation.redZone ? "Yes" : "No"]];
  return <section className={panel}><p className={label}>Game situation</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{rows.filter(([, value]) => value).map(([name, value]) => <div key={name}><p className="text-xs text-white/35">{name}</p><p className="mt-1 text-sm font-medium text-white/75">{value}</p></div>)}{!rows.some(([, value]) => value) ? <p className="text-sm text-white/38">Live situation unavailable.</p> : null}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div><p className="text-xs text-white/35">Timeouts</p><p className="mt-1 text-sm text-white/65">{live.away.team.abbreviation ?? live.away.team.name}: {live.away.timeoutsRemaining ?? "—"} · {live.home.team.abbreviation ?? live.home.team.name}: {live.home.timeoutsRemaining ?? "—"}</p></div><div><p className="text-xs text-white/35">Records</p><p className="mt-1 text-sm text-white/65">{live.away.record ?? "—"} · {live.home.record ?? "—"}</p></div></div></section>;
}

function FootballView({ event, live }: { event: SportsEvent; live: FootballLiveData }) {
  const [selected, setSelected] = useState<FootballPlay>(); const situation = live.situation; const plays = live.plays ?? live.recentPlays;
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(20rem,.85fr)]"><div className="space-y-5"><SituationCard live={live} situation={situation}/><FootballField sport="nfl" homeTeam={event.homeTeam} home={live.home} away={live.away} situation={situation} selectedPlay={selected}/><PlayFeed plays={plays} selected={selected?.id} onSelect={setSelected}/></div><aside className={panel}><p className={label}>Current drive</p><p className="mt-3 text-sm text-white/60">{live.currentDrive?.description ?? live.currentDrive?.result ?? "Drive details unavailable."}</p>{live.drives?.length ? <div className="mt-5 space-y-2">{live.drives.slice().reverse().slice(0, 5).map((drive, index) => <div key={drive.id ?? index} className="border-l border-white/15 pl-3 text-xs text-white/45">{drive.teamAbbreviation ?? "Drive"} · {drive.result ?? drive.description ?? "Provider drive"}</div>)}</div> : null}</aside></div>;
}

function CollegeFootballView({ event, live }: { event: SportsEvent; live: CollegeFootballLiveData }) {
  const cfbPlays: FootballPlay[] | undefined = live.normalizedPlays; const [selected, setSelected] = useState<FootballPlay>(); const home = event.homeTeam ?? live.home.team; const away = event.awayTeam ?? live.away.team;
  return <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="space-y-5"><section className={`${panel} bg-gradient-to-br from-red-300/[0.08] to-transparent`}><p className={label}>College Football game state</p><p className="mt-2 text-3xl font-semibold text-white">{live.status ?? "Game state unavailable"}</p><p className="mt-2 text-sm text-white/55">{live.period !== undefined ? `Q${live.period}` : "Quarter unavailable"}{live.clock ? ` · ${live.clock}` : ""}</p><div className="mt-6 grid grid-cols-[1fr_auto_1fr] items-end gap-3 text-center"><div><SportsTeamLogo sport="college-football" team={away} size="md"/><p className="mt-2 text-sm text-white/50">{away.abbreviation ?? away.name}</p><p className="mt-1 text-5xl font-semibold text-white">{live.away.score}</p></div><p className="pb-2 text-xs uppercase tracking-widest text-white/25">at</p><div><SportsTeamLogo sport="college-football" team={home} size="md"/><p className="mt-2 text-sm text-white/50">{home.abbreviation ?? home.name}</p><p className="mt-1 text-5xl font-semibold text-white">{live.home.score}</p></div></div></section><FootballField sport="college-football" homeTeam={home} situation={live.situation} selectedPlay={selected}/><PlayFeed plays={cfbPlays} selected={selected?.id} onSelect={setSelected}/><section className={panel}><p className={label}>Scoring summary</p><div className="mt-3 space-y-3">{live.scoringPlays?.map((play, index) => <p key={`${play}-${index}`} className="border-l border-amber-200/30 pl-3 text-sm text-white/70">{play}</p>)}{!live.scoringPlays?.length ? <p className="text-sm text-white/38">Scoring plays unavailable.</p> : null}</div></section></div><aside className={panel}><p className={label}>Venue · records · rankings</p><p className="mt-3 text-sm text-white/70">{live.venue?.name ?? "Venue unavailable"}{live.venue?.city ? ` · ${live.venue.city}` : ""}</p><p className="mt-4 text-sm text-white/55">{away.record ?? "—"} · {home.record ?? "—"}</p>{live.rankings?.length ? <div className="mt-5 space-y-2">{live.rankings.map((rank) => <p key={`${rank.team}-${rank.rank}`} className="text-xs text-white/55">#{rank.rank} {rank.team}</p>)}</div> : null}</aside></div>;
}

function RaceView({ event }: { event: SportsEvent }) { return <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className={`${panel} bg-gradient-to-br from-red-300/[0.08] to-transparent`}><p className={label}>{event.sport === "f1" ? "Race weekend" : "NASCAR race"}</p><h2 className="mt-2 text-3xl font-semibold text-white">{event.metadata?.competition ?? event.title}</h2><p className="mt-3 text-sm text-white/55">{event.metadata?.sessionType ?? "Race session"} · {statusText(event.status)} · {event.start.toLocaleString()}</p><div className="mt-6"><MotorsportTrackMap event={event}/></div></section><aside className={panel}><p className={label}>Results</p><p className="mt-3 text-sm text-white/40">Provider result data is shown when available. No positions or telemetry are inferred.</p></aside></div>; }
function GenericDetail({ event }: { event: SportsEvent }) { return <section className={panel}><p className={label}>Event detail</p><p className="mt-3 text-sm text-white/60">{statusText(event.status)}{event.metadata?.period !== undefined ? ` · Period ${event.metadata.period}` : ""}{event.metadata?.clock ? ` · ${event.metadata.clock}` : ""}</p></section>; }
function BasketballView({ live }: { live: BasketballLiveData }) { return <section className={panel}><p className={label}>Basketball game state</p><p className="mt-3 text-sm text-white/60">{live.status ?? "Status unavailable"}{live.period !== undefined ? ` · Q${live.period}` : ""}{live.clock ? ` · ${live.clock}` : ""}</p><p className="mt-4 text-xs text-white/35">Provider play-by-play remains unavailable for this event.</p></section>; }

function footballData(live: FootballLiveData | CollegeFootballLiveData): { plays: FootballPlay[]; home: SportsTeam; away: SportsTeam } {
  if ("normalizedPlays" in live) return { plays: live.normalizedPlays ?? [], home: live.home.team, away: live.away.team };
  const nfl = live as FootballLiveData;
  return { plays: nfl.plays ?? [], home: nfl.home.team, away: nfl.away.team };
}

export default function LiveEventCenter({ eventId }: { eventId: string }) {
  const { data, loading, error } = useSportsEvent(eventId); const seen = useRef(new Set<string>()); const initialized = useRef(false); const [celebration, setCelebration] = useState<{ play: FootballPlay; team?: SportsTeam }>();
  useEffect(() => { if (!data?.live || (data.live.sport !== "nfl" && data.event.sport !== "college-football")) return; const current = footballData(data.live as unknown as FootballLiveData | CollegeFootballLiveData); const next = findNewTouchdown(seen.current, current.plays, initialized.current); current.plays.forEach((play) => seen.current.add(touchdownKey(play))); initialized.current = true; if (next) { const team = current.home.id === next.teamId ? current.home : current.away.id === next.teamId ? current.away : undefined; setCelebration({ play: next, team }); const timer = window.setTimeout(() => setCelebration(undefined), 5000); return () => window.clearTimeout(timer); } }, [data]);
  if (loading && !data) return <div className={`${panel} animate-pulse text-sm text-white/45`}>Loading event center…</div>;
  if (!data) return <div className={panel}><h2 className="text-xl font-semibold text-white">Event unavailable</h2><p className="mt-2 text-sm text-white/50">{error ?? "This event could not be resolved from the current Sports providers."}</p><Link href="/sports" className="mt-4 inline-flex text-sm text-cyan-100/75 hover:text-white">Back to Sports</Link></div>;
  const live = data.live;
  return <div className="mx-auto max-w-[1440px] space-y-5"><FootballCelebration play={celebration?.play} team={celebration?.team}/><Link href="/sports" className="inline-flex text-sm text-white/45 hover:text-white">← Sports overview</Link>{live?.sport === "mlb" ? <MlbEventCenter event={data.event} live={live} error={error}/> : <><ScoreHeader event={data.event} scoreOverride={data.event.sport === "college-football" && live ? { away: (live as unknown as CollegeFootballLiveData).away.score, home: (live as unknown as CollegeFootballLiveData).home.score } : undefined}/>{error ? <p role="status" className="rounded-2xl border border-amber-200/15 bg-amber-200/[0.06] px-4 py-3 text-sm text-amber-100/75">Detailed game data is temporarily unavailable. Showing the latest event summary.</p> : null}{data.event.sport === "college-football" && live ? <CollegeFootballView event={data.event} live={live as unknown as CollegeFootballLiveData}/> : live?.sport === "nfl" ? <FootballView event={data.event} live={live}/> : live?.sport === "nba" ? <BasketballView live={live}/> : data.event.sport === "f1" || data.event.sport === "nascar" ? <RaceView event={data.event}/> : <GenericDetail event={data.event}/>}</>}</div>;
}
