"use client";

import Link from "next/link";
import type { SportsEvent } from "@/core/contracts/Sports";
import type { FootballLiveData } from "@/core/contracts/sports/Football";
import type { BasketballLiveData } from "@/core/contracts/sports/Basketball";
import { useSportsEvent } from "@/hooks/os/useSportsEvent";
import MlbEventCenter from "@/components/apps/sports/event/MlbEventCenter";

const panel = "rounded-3xl border border-white/10 bg-white/[0.045] p-5";
const label = "text-[11px] uppercase tracking-[0.2em] text-cyan-100/45";
const statusText = (status: SportsEvent["status"]) => status === "scheduled" ? "Upcoming" : status.charAt(0).toUpperCase() + status.slice(1);

function ScoreHeader({ event }: { event: SportsEvent }) {
  const away = event.awayTeam;
  const home = event.homeTeam;
  return <section className={`${panel} overflow-hidden bg-gradient-to-br from-cyan-300/[0.10] via-white/[0.045] to-transparent`}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className={label}>{event.sport.toUpperCase()} · {statusText(event.status)}</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-white sm:text-4xl">{event.title}</h1><p className="mt-2 text-sm text-white/45">{event.statusDetail ?? event.venue ?? event.start.toLocaleString()}</p></div><span className="rounded-full border border-white/12 bg-white/[0.07] px-3 py-1 text-xs uppercase tracking-wider text-white/65">{statusText(event.status)}</span></div>{away && home ? <div className="mt-7 grid grid-cols-[1fr_auto_1fr] items-end gap-3 text-center"><div><p className="text-sm text-white/50">{away.abbreviation ?? away.name}</p><p className="mt-1 text-5xl font-semibold text-white sm:text-7xl">{away.score ?? "—"}</p></div><p className="pb-2 text-xs uppercase tracking-widest text-white/25">at</p><div><p className="text-sm text-white/50">{home.abbreviation ?? home.name}</p><p className="mt-1 text-5xl font-semibold text-white sm:text-7xl">{home.score ?? "—"}</p></div></div> : null}</section>;
}


function FootballField({ situation }: { situation: FootballLiveData["situation"] }) {
  const position = situation.fieldPosition?.yardLine;
  return <div className={panel}><div className="flex items-center justify-between"><p className={label}>Field position</p><span className="text-xs text-white/45">{situation.possessionText ?? situation.fieldPosition?.display ?? "Unavailable"}</span></div><div className="mt-4 h-12 rounded-xl border border-white/15 bg-gradient-to-r from-emerald-500/20 via-white/[0.05] to-emerald-500/20"><div className="relative h-full border-x border-white/20" style={position === undefined ? undefined : { marginLeft: `${Math.max(0, Math.min(90, position))}%`, width: "2px", background: "rgba(251,191,36,.8)" }} /></div>{position === undefined ? <p className="mt-2 text-xs text-white/35">Provider field position unavailable.</p> : null}</div>;
}

function FootballView({ live }: { live: FootballLiveData }) {
  const situation = live.situation;
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(20rem,.85fr)]"><div className="space-y-5"><section className={`${panel} bg-gradient-to-br from-green-300/[0.08] to-transparent`}><p className={label}>Game situation</p><p className="mt-2 text-4xl font-semibold text-white">{situation.shortDownDistanceText ?? situation.downDistanceText ?? "Situation unavailable"}</p><div className="mt-3 flex flex-wrap gap-4 text-sm text-white/55"><span>Q{situuationValue(situation.quarter)}{situation.clock ? ` · ${situation.clock}` : ""}</span><span>{situation.possessionText ?? "Possession unavailable"}</span></div></section><FootballField situation={situation}/><section className={panel}><p className={label}>Recent plays</p><div className="mt-3 space-y-3">{live.recentPlays?.slice().reverse().map((play, index) => <div key={play.id ?? `${play.sequence ?? "play"}-${index}`} className="border-l border-green-200/25 pl-3"><p className="text-sm leading-6 text-white/72">{play.description}</p><p className="mt-1 text-xs text-white/35">{play.clock ?? ""}{play.scoringPlay ? " · Scoring play" : ""}</p></div>)}{!live.recentPlays?.length ? <p className="text-sm text-white/38">Play data is unavailable.</p> : null}</div></section></div><aside className="space-y-5"><section className={panel}><p className={label}>Current drive</p>{live.currentDrive ? <><p className="mt-2 text-lg text-white/78">{live.currentDrive.teamAbbreviation ?? "Drive"}</p><p className="mt-2 text-sm text-white/48">{live.currentDrive.plays !== undefined ? `${live.currentDrive.plays} plays` : "Play count unavailable"}{live.currentDrive.yards !== undefined ? ` · ${live.currentDrive.yards} yards` : ""}</p><p className="mt-2 text-sm text-white/55">{live.currentDrive.description ?? live.currentDrive.result ?? "Drive details unavailable"}</p></> : <p className="mt-3 text-sm text-white/38">Current drive data is unavailable.</p>}</section><section className={panel}><p className={label}>Team timeouts</p><div className="mt-3 grid grid-cols-2 gap-3 text-sm text-white/60"><span>{live.away.team.abbreviation ?? live.away.team.name}: {live.away.timeoutsRemaining ?? "—"}</span><span>{live.home.team.abbreviation ?? live.home.team.name}: {live.home.timeoutsRemaining ?? "—"}</span></div></section></aside></div>;
}

function situuationValue(value?: number) { return value ?? "—"; }

function LeagueDetail({ event }: { event: SportsEvent }) {
  const metadata = event.metadata;
  return <section className={panel}><p className={label}>{event.sport === "nba" ? "Basketball state" : "Match state"}</p><div className="mt-3 grid gap-3 text-sm text-white/60 sm:grid-cols-3"><div><p className={label}>Status</p><p className="mt-1 text-white/80">{statusText(event.status)}</p></div>{metadata?.period !== undefined ? <div><p className={label}>Period</p><p className="mt-1 text-white/80">{metadata.period}</p></div> : null}{metadata?.clock ? <div><p className={label}>Clock</p><p className="mt-1 text-white/80">{metadata.clock}</p></div> : null}</div><p className="mt-4 text-xs text-white/35">Detailed play-by-play and advanced statistics are not exposed by the current public source.</p></section>;
}

function BasketballView({ live }: { live: BasketballLiveData }) {
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(20rem,.85fr)]"><div className="space-y-5"><section className={`${panel} bg-gradient-to-br from-orange-300/[0.08] to-transparent`}><p className={label}>Game situation</p><p className="mt-2 text-3xl font-semibold text-white">{live.status ?? "Game summary"}</p><p className="mt-2 text-sm text-white/55">{live.period !== undefined ? `Q${live.period}` : "Period unavailable"}{live.clock ? ` · ${live.clock}` : ""}</p></section><section className={panel}><p className={label}>Recent plays</p><div className="mt-3 space-y-3">{live.plays?.slice(0, 12).map((play, index) => <div key={play.id ?? `${play.clock ?? "play"}-${index}`} className="border-l border-orange-200/25 pl-3"><p className="text-sm leading-6 text-white/72">{play.text}</p><p className="mt-1 text-xs text-white/35">{play.clock ?? "Play"}{play.teamAbbreviation ? ` · ${play.teamAbbreviation}` : ""}</p></div>)}{!live.plays?.length ? <p className="text-sm text-white/38">Play-by-play is unavailable from the current summary.</p> : null}</div></section></div><aside className="space-y-5"><section className={panel}><p className={label}>Leaders</p><div className="mt-3 space-y-3">{live.leaders?.map((leader) => <div key={`${leader.category}-${leader.name}`} className="flex items-center justify-between gap-3 text-sm"><span className="text-white/55">{leader.category}</span><span className="text-right text-white/80">{leader.name}{leader.value ? ` · ${leader.value}` : ""}</span></div>)}{!live.leaders?.length ? <p className="text-sm text-white/38">Leaders unavailable.</p> : null}</div></section><section className={panel}><p className={label}>Team stats</p><div className="mt-3 space-y-3">{live.teamStats?.map((team) => <div key={team.team.id ?? team.team.name}><p className="text-sm text-white/75">{team.team.abbreviation ?? team.team.name}</p><p className="mt-1 text-xs leading-5 text-white/45">{Object.entries(team.stats).slice(0, 8).map(([name, value]) => `${name}: ${value}`).join(" · ")}</p></div>)}{!live.teamStats?.length ? <p className="text-sm text-white/38">Team statistics unavailable.</p> : null}</div></section></aside></div>;
}

function RaceView({ event }: { event: SportsEvent }) {
  const session = event.metadata?.sessionType ?? (event.sport === "nascar" ? "Race" : "Session");
  return <section className={panel}><p className={label}>{event.sport === "f1" ? "Race weekend session" : "Race state"}</p><p className="mt-2 text-2xl font-semibold text-white">{session}</p><div className="mt-4 grid gap-3 text-sm text-white/60 sm:grid-cols-3"><div><p className={label}>Status</p><p className="mt-1 text-white/80">{statusText(event.status)}</p></div><div><p className={label}>{event.sport === "f1" ? "Circuit" : "Track"}</p><p className="mt-1 text-white/80">{event.metadata?.circuit ?? event.metadata?.track ?? event.venue ?? "Unavailable"}</p></div><div><p className={label}>Start</p><p className="mt-1 text-white/80">{event.start.toLocaleString()}</p></div></div><p className="mt-5 text-sm text-white/40">Live timing and running order are shown only when a reliable public timing feed is available.</p></section>;
}

export default function LiveEventCenter({ eventId }: { eventId: string }) {
  const { data, loading, error } = useSportsEvent(eventId);
  if (loading && !data) return <div className={`${panel} animate-pulse text-sm text-white/45`}>Loading event center…</div>;
  if (!data) return <div className={panel}><h2 className="text-xl font-semibold text-white">Event unavailable</h2><p className="mt-2 text-sm text-white/50">{error ?? "This event could not be resolved from the current Sports providers."}</p><Link href="/sports" className="mt-4 inline-flex text-sm text-cyan-100/75 hover:text-white">Back to Sports</Link></div>;
  const live = data.live;
  return <div className="mx-auto max-w-[1440px] space-y-5"><Link href="/sports" className="inline-flex text-sm text-white/45 hover:text-white">← Sports overview</Link>{live?.sport === "mlb" ? <MlbEventCenter event={data.event} live={live} error={error}/> : <><ScoreHeader event={data.event}/>{error ? <p role="status" className="rounded-2xl border border-amber-200/15 bg-amber-200/[0.06] px-4 py-3 text-sm text-amber-100/75">Detailed game data is temporarily unavailable. Showing the latest event summary.</p> : null}{live?.sport === "nfl" ? <FootballView live={live}/> : live?.sport === "nba" ? <BasketballView live={live}/> : data.event.sport === "mls" ? <LeagueDetail event={data.event}/> : data.event.sport === "f1" || data.event.sport === "nascar" ? <RaceView event={data.event}/> : <section className={panel}><p className={label}>Event detail</p><p className="mt-2 text-lg text-white/75">Detailed provider data is not currently available for this event.</p></section>}</>}</div>;
}
