"use client";

import Link from "next/link";
import type { SportsEvent } from "@/core/contracts/Sports";
import type { BaseballLiveData } from "@/core/contracts/sports/Baseball";
import type { FootballLiveData } from "@/core/contracts/sports/Football";
import { useSportsEvent } from "@/hooks/os/useSportsEvent";

const panel = "rounded-3xl border border-white/10 bg-white/[0.045] p-5";
const label = "text-[11px] uppercase tracking-[0.2em] text-cyan-100/45";
const statusText = (status: SportsEvent["status"]) => status === "scheduled" ? "Upcoming" : status.charAt(0).toUpperCase() + status.slice(1);

function ScoreHeader({ event }: { event: SportsEvent }) {
  const away = event.awayTeam;
  const home = event.homeTeam;
  return <section className={`${panel} overflow-hidden bg-gradient-to-br from-cyan-300/[0.10] via-white/[0.045] to-transparent`}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className={label}>{event.sport.toUpperCase()} · {statusText(event.status)}</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-white sm:text-4xl">{event.title}</h1><p className="mt-2 text-sm text-white/45">{event.statusDetail ?? event.venue ?? event.start.toLocaleString()}</p></div><span className="rounded-full border border-white/12 bg-white/[0.07] px-3 py-1 text-xs uppercase tracking-wider text-white/65">{statusText(event.status)}</span></div>{away && home ? <div className="mt-7 grid grid-cols-[1fr_auto_1fr] items-end gap-3 text-center"><div><p className="text-sm text-white/50">{away.abbreviation ?? away.name}</p><p className="mt-1 text-5xl font-semibold text-white sm:text-7xl">{away.score ?? "—"}</p></div><p className="pb-2 text-xs uppercase tracking-widest text-white/25">at</p><div><p className="text-sm text-white/50">{home.abbreviation ?? home.name}</p><p className="mt-1 text-5xl font-semibold text-white sm:text-7xl">{home.score ?? "—"}</p></div></div> : null}</section>;
}

function BaseballDiamond({ bases }: { bases: BaseballLiveData["bases"] }) {
  const occupied = (base: 1 | 2 | 3) => Boolean(base === 1 ? bases?.first : base === 2 ? bases?.second : bases?.third);
  return <div className="relative mx-auto h-40 w-40" aria-label={`Bases: first ${occupied(1) ? "occupied" : "empty"}, second ${occupied(2) ? "occupied" : "empty"}, third ${occupied(3) ? "occupied" : "empty"}`}><div className="absolute left-1/2 top-5 h-20 w-20 -translate-x-1/2 rotate-45 border-2 border-cyan-100/55 bg-cyan-200/[0.06]" /><span className={`absolute left-1/2 top-0 h-7 w-7 -translate-x-1/2 rotate-45 border ${occupied(2) ? "border-amber-200 bg-amber-200/70" : "border-white/25 bg-white/[0.04]"}`} /><span className={`absolute right-2 top-1/2 h-7 w-7 -translate-y-1/2 rotate-45 border ${occupied(1) ? "border-amber-200 bg-amber-200/70" : "border-white/25 bg-white/[0.04]"}`} /><span className={`absolute bottom-0 left-1/2 h-7 w-7 -translate-x-1/2 rotate-45 border ${occupied(3) ? "border-amber-200 bg-amber-200/70" : "border-white/25 bg-white/[0.04]"}`} /><span className="absolute bottom-5 left-1/2 h-5 w-5 -translate-x-1/2 rotate-45 border border-white/35 bg-white/10" /></div>;
}

function BaseballView({ live }: { live: BaseballLiveData }) {
  const count = live.count;
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(20rem,.8fr)]"><div className="space-y-5"><section className={panel}><div className="grid gap-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className={label}>Game situation</p><p className="mt-2 text-3xl font-semibold text-white">{live.inning ? `${live.inningHalf && live.inningHalf !== "unknown" ? `${live.inningHalf} ` : ""}${live.inning}` : "In progress"}</p>{live.currentAtBat?.description ? <p className="mt-2 text-sm text-white/52">{live.currentAtBat.description}</p> : null}</div><BaseballDiamond bases={live.bases} /></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-white/[0.05] p-3"><p className={label}>Balls</p><p className="mt-1 text-2xl text-white">{count?.balls ?? "—"}</p></div><div className="rounded-2xl bg-white/[0.05] p-3"><p className={label}>Strikes</p><p className="mt-1 text-2xl text-white">{count?.strikes ?? "—"}</p></div><div className="rounded-2xl bg-white/[0.05] p-3"><p className={label}>Outs</p><p className="mt-1 text-2xl text-white">{count?.outs ?? "—"}</p></div></div></section><section className={panel}><p className={label}>Recent plays</p><div className="mt-3 space-y-3">{live.recentPlays?.slice().reverse().map((play, index) => <div key={play.id ?? `${play.sequence ?? "play"}-${index}`} className="border-l border-cyan-200/25 pl-3"><p className="text-sm leading-6 text-white/72">{play.description}</p><p className="mt-1 text-xs text-white/35">{play.inning ? `${play.inningHalf ?? ""} ${play.inning}` : "Play"}{play.scoringPlay ? " · Scoring play" : ""}</p></div>)}{!live.recentPlays?.length ? <p className="text-sm text-white/38">Recent play data is unavailable.</p> : null}</div></section></div><aside className="space-y-5"><section className={panel}><p className={label}>Current matchup</p><div className="mt-4 space-y-4"><PersonRow title="Batter" person={live.matchup?.batter?.name} /><PersonRow title="Pitcher" person={live.matchup?.pitcher?.name} /></div></section><section className={panel}><p className={label}>Line score</p><div className="mt-3 space-y-2 text-sm">{live.linescore?.innings.slice(-6).map((inning) => <div key={inning.inning} className="flex justify-between border-b border-white/[0.07] pb-2 text-white/55"><span>Inning {inning.inning}</span><span>{inning.away?.runs ?? "—"} · {inning.home?.runs ?? "—"}</span></div>) ?? <p className="text-white/38">Line score unavailable.</p>}</div></section></aside></div>;
}

function PersonRow({ title, person }: { title: string; person?: string }) { return <div><p className={label}>{title}</p><p className="mt-1 text-lg text-white/78">{person ?? "Unavailable"}</p></div>; }

function FootballField({ situation }: { situation: FootballLiveData["situation"] }) {
  const position = situation.fieldPosition?.yardLine;
  return <div className={panel}><div className="flex items-center justify-between"><p className={label}>Field position</p><span className="text-xs text-white/45">{situation.possessionText ?? situation.fieldPosition?.display ?? "Unavailable"}</span></div><div className="mt-4 h-12 rounded-xl border border-white/15 bg-gradient-to-r from-emerald-500/20 via-white/[0.05] to-emerald-500/20"><div className="relative h-full border-x border-white/20" style={position === undefined ? undefined : { marginLeft: `${Math.max(0, Math.min(90, position))}%`, width: "2px", background: "rgba(251,191,36,.8)" }} /></div>{position === undefined ? <p className="mt-2 text-xs text-white/35">Provider field position unavailable.</p> : null}</div>;
}

function FootballView({ live }: { live: FootballLiveData }) {
  const situation = live.situation;
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(20rem,.85fr)]"><div className="space-y-5"><section className={`${panel} bg-gradient-to-br from-green-300/[0.08] to-transparent`}><p className={label}>Game situation</p><p className="mt-2 text-4xl font-semibold text-white">{situation.shortDownDistanceText ?? situation.downDistanceText ?? "Situation unavailable"}</p><div className="mt-3 flex flex-wrap gap-4 text-sm text-white/55"><span>Q{situuationValue(situation.quarter)}{situation.clock ? ` · ${situation.clock}` : ""}</span><span>{situation.possessionText ?? "Possession unavailable"}</span></div></section><FootballField situation={situation}/><section className={panel}><p className={label}>Recent plays</p><div className="mt-3 space-y-3">{live.recentPlays?.slice().reverse().map((play, index) => <div key={play.id ?? `${play.sequence ?? "play"}-${index}`} className="border-l border-green-200/25 pl-3"><p className="text-sm leading-6 text-white/72">{play.description}</p><p className="mt-1 text-xs text-white/35">{play.clock ?? ""}{play.scoringPlay ? " · Scoring play" : ""}</p></div>)}{!live.recentPlays?.length ? <p className="text-sm text-white/38">Play data is unavailable.</p> : null}</div></section></div><aside className="space-y-5"><section className={panel}><p className={label}>Current drive</p>{live.currentDrive ? <><p className="mt-2 text-lg text-white/78">{live.currentDrive.teamAbbreviation ?? "Drive"}</p><p className="mt-2 text-sm text-white/48">{live.currentDrive.plays !== undefined ? `${live.currentDrive.plays} plays` : "Play count unavailable"}{live.currentDrive.yards !== undefined ? ` · ${live.currentDrive.yards} yards` : ""}</p><p className="mt-2 text-sm text-white/55">{live.currentDrive.description ?? live.currentDrive.result ?? "Drive details unavailable"}</p></> : <p className="mt-3 text-sm text-white/38">Current drive data is unavailable.</p>}</section><section className={panel}><p className={label}>Team timeouts</p><div className="mt-3 grid grid-cols-2 gap-3 text-sm text-white/60"><span>{live.away.team.abbreviation ?? live.away.team.name}: {live.away.timeoutsRemaining ?? "—"}</span><span>{live.home.team.abbreviation ?? live.home.team.name}: {live.home.timeoutsRemaining ?? "—"}</span></div></section></aside></div>;
}

function situuationValue(value?: number) { return value ?? "—"; }

export default function LiveEventCenter({ eventId }: { eventId: string }) {
  const { data, loading, error } = useSportsEvent(eventId);
  if (loading && !data) return <div className={`${panel} animate-pulse text-sm text-white/45`}>Loading event center…</div>;
  if (!data) return <div className={panel}><h2 className="text-xl font-semibold text-white">Event unavailable</h2><p className="mt-2 text-sm text-white/50">{error ?? "This event could not be resolved from the current Sports providers."}</p><Link href="/sports" className="mt-4 inline-flex text-sm text-cyan-100/75 hover:text-white">Back to Sports</Link></div>;
  const live = data.live;
  return <div className="mx-auto max-w-[1440px] space-y-5"><Link href="/sports" className="inline-flex text-sm text-white/45 hover:text-white">← Sports overview</Link><ScoreHeader event={data.event}/>{error ? <p role="status" className="rounded-2xl border border-amber-200/15 bg-amber-200/[0.06] px-4 py-3 text-sm text-amber-100/75">Live detail is temporarily unavailable. Showing the latest event summary.</p> : null}{live?.sport === "mlb" ? <BaseballView live={live}/> : live?.sport === "nfl" ? <FootballView live={live}/> : <section className={panel}><p className={label}>{data.event.sport === "f1" ? "Motorsport session" : data.event.sport === "nascar" ? "Race state" : "Event detail"}</p><p className="mt-2 text-lg text-white/75">Detailed provider data is not currently available for this event.</p><p className="mt-2 text-sm text-white/40">Cosmic will show richer timing and race-state information when a truthful provider feed is available.</p></section>}</div>;
}
