"use client";

import type { SportsEvent } from "@/core/contracts/Sports";
import type { BaseballLiveData, BaseballPlayerRef, BaseballPlayerStats } from "@/core/contracts/sports/Baseball";
import TeamLogo from "@/components/apps/sports/TeamLogo";
import { getMlbTeamTheme } from "@/services/sports/providers/mlb/teamThemes";

const panel = "rounded-[24px] border border-white/10 bg-[#07101f]/85 p-4 shadow-[0_18px_60px_rgba(0,0,0,.22)]";
const label = "text-[10px] uppercase tracking-[.22em] text-white/40";
const value = (v?: number | string) => v === undefined || v === null ? "—" : v;
const name = (person?: BaseballPlayerRef) => person?.name ?? "Unavailable";
const prettyHalf = (half?: string) => half === "bottom" ? "Bottom" : half === "top" ? "Top" : half === "middle" ? "Middle" : half === "end" ? "End" : "In progress";

function TeamMark({ team, size = 76 }: { team: { id?: string; abbreviation?: string; name: string }; size?: number }) {
  const theme = getMlbTeamTheme(team);
  return theme.logo ? <TeamLogo league="mlb" team={theme.abbreviation} size={size} /> : <span className="grid place-items-center rounded-full border border-white/20 bg-white/10 text-xs font-bold text-white/70" style={{ width: size, height: size }}>{team.abbreviation ?? team.name.slice(0, 3)}</span>;
}

function Diamond({ live }: { live: BaseballLiveData }) {
  const occupied = { first: Boolean(live.bases?.first), second: Boolean(live.bases?.second), third: Boolean(live.bases?.third) };
  const text = Object.entries(occupied).map(([base, isOccupied]) => `${base} ${isOccupied ? "occupied" : "empty"}`).join(", ");
  return <div className="flex flex-col items-center gap-3"><div className="relative h-44 w-44" role="img" aria-label={`Base runners: ${text}`}><div className="absolute left-1/2 top-7 h-28 w-28 -translate-x-1/2 rotate-45 border border-cyan-100/35 bg-gradient-to-br from-cyan-200/[.12] to-transparent" /><Base label="2B" occupied={occupied.second} className="left-1/2 top-0 -translate-x-1/2" /><Base label="1B" occupied={occupied.first} className="right-1 top-1/2 -translate-y-1/2" /><Base label="3B" occupied={occupied.third} className="bottom-0 left-1/2 -translate-x-1/2" /><span className="absolute bottom-7 left-1/2 h-6 w-6 -translate-x-1/2 rotate-45 border border-white/35 bg-white/[.08]" /></div><p className="text-xs text-white/45">{text}</p></div>;
}

function Base({ label: baseLabel, occupied, className }: { label: string; occupied: boolean; className: string }) { return <span className={`absolute grid h-8 w-8 rotate-45 place-items-center border text-[8px] font-bold ${className} ${occupied ? "border-amber-200 bg-amber-200 text-[#131b2b] shadow-[0_0_22px_rgba(253,230,138,.7)]" : "border-white/20 bg-[#101b2e] text-white/35"}`}><span className="-rotate-45">{baseLabel}</span></span>; }

function Scoreboard({ event, live }: { event: SportsEvent; live: BaseballLiveData }) {
  const away = live.away.team; const home = live.home.team; const awayTheme = getMlbTeamTheme(away); const homeTheme = getMlbTeamTheme(home);
  const situation = live.inning ? `${prettyHalf(live.inningHalf)} ${live.inning}` : "Game state unavailable";
  return <section className="relative overflow-hidden rounded-[28px] border border-white/10 bg-[#050b17] p-5 sm:p-7" style={{ backgroundImage: `radial-gradient(circle at 0% 50%, ${awayTheme.primary}55, transparent 38%), radial-gradient(circle at 100% 50%, ${homeTheme.primary}55, transparent 38%)` }}><div className="relative flex items-center justify-between gap-3"><div><p className={label}>MLB · {event.status === "live" ? "Live game" : event.statusDetail ?? event.status}</p><h1 className="mt-2 text-xl font-semibold tracking-tight text-white sm:text-3xl">{away.name} <span className="text-white/30">at</span> {home.name}</h1></div><span className={`rounded-full border px-3 py-1 text-[10px] font-semibold uppercase tracking-[.18em] ${event.status === "live" ? "border-red-300/30 bg-red-400/10 text-red-100" : "border-white/15 bg-white/[.06] text-white/60"}`}>{event.status === "live" ? "● Live" : event.status}</span></div><div className="relative mt-8 grid grid-cols-[1fr_auto_1fr] items-center gap-3 sm:gap-8"><ScoreTeam team={away} score={live.away.score} theme={awayTheme} align="right"/><div className="text-center"><p className="text-[10px] uppercase tracking-[.18em] text-cyan-100/55">{situation}</p><p className="mt-2 text-xs text-white/35">{live.count?.outs !== undefined ? `${live.count.outs} out${live.count.outs === 1 ? "" : "s"}` : "Outs —"}</p></div><ScoreTeam team={home} score={live.home.score} theme={homeTheme} align="left"/></div></section>;
}

function ScoreTeam({ team, score, theme, align }: { team: { name: string; abbreviation?: string }; score: number; theme: ReturnType<typeof getMlbTeamTheme>; align: "left" | "right" }) { return <div className={`flex items-center gap-3 ${align === "right" ? "justify-end text-right" : "text-left"}`}><div className="hidden sm:block"><p className="text-xs font-semibold" style={{ color: theme.accent }}>{team.abbreviation ?? team.name}</p><p className="mt-1 max-w-[150px] text-xs text-white/50">{team.name}</p></div><TeamMark team={team} size={64}/><p className="tabular-nums text-5xl font-semibold text-white sm:text-7xl">{score}</p></div>; }

function Situation({ live }: { live: BaseballLiveData }) { const c = live.count; return <section className={`${panel} bg-gradient-to-br from-cyan-200/[.08] to-transparent`}><p className={label}>Game situation</p><div className="mt-3 grid gap-4 sm:grid-cols-[1fr_auto]"><div><p className="text-3xl font-semibold text-white">{live.inning ? `${prettyHalf(live.inningHalf)} ${live.inning}` : "In progress"}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center">{[["Balls", c?.balls], ["Strikes", c?.strikes], ["Outs", c?.outs]].map(([title, number]) => <div key={title} className="rounded-xl bg-white/[.06] px-2 py-3"><p className={label}>{title}</p><p className="mt-1 text-2xl tabular-nums text-white">{value(number as number)}</p></div>)}</div></div><Diamond live={live}/></div></section>; }

function Matchup({ live }: { live: BaseballLiveData }) { const batter = live.matchup?.batter; const pitcher = live.matchup?.pitcher; const findStats = (person?: BaseballPlayerRef): BaseballPlayerStats | undefined => { if (!person?.id) return undefined; return [...(live.boxScore?.away?.players ?? []), ...(live.boxScore?.home?.players ?? [])].find((entry) => entry.player.id === person.id); }; const batterStats = findStats(batter)?.batting; const pitcherStats = findStats(pitcher)?.pitching; return <section className={panel}><p className={label}>Current matchup</p><div className="mt-4 grid gap-5 sm:grid-cols-2"><Person title="Batter" person={batter} /><Person title="Pitcher" person={pitcher}/></div><div className="mt-5 grid gap-4 border-t border-white/[.08] pt-4 sm:grid-cols-2"><Stats title="At bat" items={[["AB", batterStats?.atBats], ["H", batterStats?.hits], ["RBI", batterStats?.rbi], ["BB", batterStats?.walks], ["K", batterStats?.strikeouts], ["HR", batterStats?.homeRuns]]}/><Stats title={`Pitching${pitcherStats?.pitchesThrown !== undefined ? ` · ${pitcherStats.pitchesThrown} pitches` : ""}`} items={[["IP", pitcherStats?.inningsPitched], ["H", pitcherStats?.hits], ["R", pitcherStats?.runs], ["ER", pitcherStats?.earnedRuns], ["BB", pitcherStats?.walks], ["K", pitcherStats?.strikeouts]]}/></div>{live.latestPitch ? <div className="mt-4 rounded-xl bg-cyan-100/[.06] p-3 text-sm text-white/70"><span className="text-cyan-100/55">Last pitch · </span>{live.latestPitch.typeName ?? live.latestPitch.description ?? "Pitch"}{live.latestPitch.velocityMph !== undefined ? ` · ${live.latestPitch.velocityMph} mph` : ""}{live.latestPitch.result ? ` · ${live.latestPitch.result}` : ""}</div> : null}</section>; }
function Person({ title, person }: { title: string; person?: BaseballPlayerRef }) { return <div><p className={label}>{title}</p><p className="mt-2 text-lg font-medium text-white">{name(person)}</p><p className="mt-1 text-xs text-white/40">{person?.position ?? "Position unavailable"}{person?.jerseyNumber ? ` · #${person.jerseyNumber}` : ""}</p></div>; }
function Stats({ title, items }: { title: string; items: [string, number | string | undefined][] }) { return <div><p className={label}>{title}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-2">{items.filter(([, v]) => v !== undefined).map(([key, v]) => <span key={key} className="text-xs text-white/55"><b className="mr-1 text-white/85">{v}</b>{key}</span>)}</div></div>; }

function LineScore({ live }: { live: BaseballLiveData }) { const innings = live.linescore?.innings ?? []; return <section className={`${panel} overflow-hidden`}><div className="flex items-center justify-between"><p className={label}>Line score</p><span className="text-[10px] text-white/35">R / H / E</span></div><div className="mt-4 overflow-x-auto"><table className="min-w-[520px] w-full border-collapse text-right text-xs"><thead><tr className="text-white/35"><th className="w-28 pb-3 text-left">TEAM</th>{innings.map((inning) => <th key={inning.inning} className={`pb-3 px-2 ${live.inning === inning.inning ? "text-cyan-100" : ""}`}>{inning.inning}</th>)}<th className="border-l border-white/10 pb-3 pl-3">R</th><th className="pb-3 pl-3">H</th><th className="pb-3 pl-3">E</th></tr></thead><tbody>{[["away", live.away, live.linescore?.away], ["home", live.home, live.linescore?.home]].map(([side, team, totals]) => <tr key={side as string} className="border-t border-white/[.07] text-white/75"><th className="py-3 text-left font-semibold">{(team as BaseballLiveData["away"]).team.abbreviation ?? (team as BaseballLiveData["away"]).team.name}</th>{innings.map((inning) => <td key={inning.inning} className={`px-2 py-3 tabular-nums ${live.inning === inning.inning ? "bg-cyan-100/[.06] text-white" : ""}`}>{value((side === "away" ? inning.away : inning.home)?.runs)}</td>)}<td className="border-l border-white/10 pl-3 tabular-nums">{value((totals as { runs?: number } | undefined)?.runs)}</td><td className="pl-3 tabular-nums">{value((totals as { hits?: number } | undefined)?.hits)}</td><td className="pl-3 tabular-nums">{value((totals as { errors?: number } | undefined)?.errors)}</td></tr>)}</tbody></table></div></section>; }

function Plays({ live }: { live: BaseballLiveData }) { const plays = live.recentPlays ?? []; const scoring = plays.filter((play) => play.scoringPlay); return <div className="grid gap-5 lg:grid-cols-2"><section className={panel}><p className={label}>Last play</p>{live.latestPlay ? <><p className="mt-3 text-lg font-medium text-white">{live.latestPlay.result ?? "Completed play"}</p><p className="mt-2 text-sm leading-6 text-white/60">{live.latestPlay.description}</p><p className="mt-3 text-xs text-white/35">{live.latestPlay.inning ? `${prettyHalf(live.latestPlay.inningHalf)} ${live.latestPlay.inning}` : "Recent"}</p></> : <p className="mt-3 text-sm text-white/40">No completed play is available.</p>}</section><section className={panel}><p className={label}>Scoring plays</p>{scoring.length ? scoring.slice().reverse().map((play, index) => <div key={play.id ?? index} className="mt-3 border-l-2 border-amber-200/60 pl-3"><p className="text-sm text-white/75">{play.description}</p><p className="mt-1 text-xs text-white/35">{prettyHalf(play.inningHalf)} {play.inning ?? "—"}</p></div>) : <p className="mt-3 text-sm text-white/40">No scoring plays in the current feed window.</p>}</section></div>; }

function RecentPlays({ live }: { live: BaseballLiveData }) { return <section className={panel}><div className="flex items-center justify-between"><p className={label}>Recent plays</p><span className="text-xs text-white/30">Provider feed</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{(live.recentPlays ?? []).slice().reverse().map((play, index) => <div key={play.id ?? index} className="border-l border-cyan-200/25 pl-3"><p className="text-sm leading-6 text-white/70">{play.description}</p><p className="mt-1 text-xs text-white/35">{prettyHalf(play.inningHalf)} {play.inning ?? "—"}{play.batter?.name ? ` · ${play.batter.name}` : ""}</p></div>)}{!live.recentPlays?.length ? <p className="text-sm text-white/40">Recent play data is unavailable.</p> : null}</div></section>; }

export default function MlbEventCenter({ event, live, error }: { event: SportsEvent; live: BaseballLiveData; error?: string | null }) { return <div className="space-y-5"><Scoreboard event={event} live={live}/>{error ? <p role="status" className="rounded-2xl border border-amber-200/15 bg-amber-200/[.06] px-4 py-3 text-sm text-amber-100/75">LIVE DATA DELAYED · Showing the last known game state.</p> : null}<div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(0,1.15fr)_minmax(0,1fr)]"><div className="space-y-5"><Matchup live={live}/>{live.matchup?.onDeck || live.matchup?.inHole ? <section className={panel}><p className={label}>Due up</p><div className="mt-3 grid grid-cols-2 gap-3"><Person title="On deck" person={live.matchup.onDeck}/><Person title="In the hole" person={live.matchup.inHole}/></div></section> : null}</div><Situation live={live}/><LineScore live={live}/></div><Plays live={live}/><RecentPlays live={live}/>{live.venue?.name ? <p className="text-xs text-white/35">{live.venue.name}{live.venue.city ? ` · ${live.venue.city}` : ""}{live.weather?.temperatureF !== undefined ? ` · ${live.weather.temperatureF}°F` : ""}</p> : null}</div>; }
