import "server-only";
import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import type { MusicCapabilities, MusicSnapshot } from "@/core/contracts/Music";
import { getProviderCredentials, listProviderConnections, setProviderCredentials, upsertProviderConnection } from "@/services/providers/store";
export type Token={access_token:string;refresh_token?:string;expires_at?:number;scope?:string}; const path=join(process.cwd(),".cosmic","spotify-token.json"); const caps:MusicCapabilities={canPlay:true,canPause:true,canSkipNext:true,canSkipPrevious:true,canSeek:true,canSetVolume:true,canReadQueue:true};
export const configured=()=>Boolean(process.env.SPOTIFY_CLIENT_ID&&process.env.SPOTIFY_CLIENT_SECRET&&process.env.SPOTIFY_REDIRECT_URI);
export const readToken=():Token|undefined=>{try{return JSON.parse(readFileSync(path,"utf8")) as Token}catch{return undefined}};
export const storeToken=(token:Token)=>{mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify({...readToken(),...token,refresh_token:token.refresh_token??readToken()?.refresh_token}),{mode:0o600})};
export const disconnect=()=>{if(existsSync(path))unlinkSync(path)};
function selectSpotifyArtwork(images?:Array<{url:string;width?:number;height?:number}>){return images?.slice().sort((a,b)=>Math.abs((a.width??640)-640)-Math.abs((b.width??640)-640))[0]?.url;}
async function token(){let t=readToken();if(!t)throw new Error("Spotify reconnect required.");if(!t.expires_at||t.expires_at>Date.now()+60000)return t;const r=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{Authorization:`Basic ${Buffer.from(`${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`).toString("base64")}`,"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:t.refresh_token??""})});if(!r.ok)throw new Error("Spotify reconnect required.");const n=await r.json() as Token&{expires_in:number};t={...t,...n,expires_at:Date.now()+n.expires_in*1000};storeToken(t);return t}
export async function snapshot():Promise<MusicSnapshot>{if(!configured())return {connected:false,capabilities:{...caps,canPlay:false,canPause:false,canSkipNext:false,canSkipPrevious:false,canSeek:false,canSetVolume:false,canReadQueue:false},playback:{playing:false,positionMs:0,updatedAt:""}};try{const t=await token();const r=await fetch("https://api.spotify.com/v1/me/player",{headers:{Authorization:`Bearer ${t.access_token}`}});if(r.status===204)return {provider:"spotify",connected:true,capabilities:caps,playback:{playing:false,positionMs:0,updatedAt:new Date().toISOString()}};if(!r.ok)throw new Error("Spotify playback unavailable.");const d=await r.json() as {is_playing:boolean;progress_ms:number;item?:{id:string;name:string;duration_ms:number;artists:{name:string}[];album?:{name:string;images?:{url:string;width?:number;height?:number}[]}};device?:{name:string;volume_percent?:number}};return {provider:"spotify",connected:true,capabilities:caps,playback:{playing:d.is_playing,positionMs:d.progress_ms??0,durationMs:d.item?.duration_ms,volume:d.device?.volume_percent,deviceName:d.device?.name,updatedAt:new Date().toISOString(),track:d.item?{id:d.item.id,title:d.item.name,artists:d.item.artists.map(a=>a.name),album:d.item.album?.name,artworkUrl:selectSpotifyArtwork(d.item.album?.images),durationMs:d.item.duration_ms,provider:"spotify"}:undefined}}}catch{return {provider:"spotify",connected:false,capabilities:{...caps,canPlay:false,canPause:false,canSkipNext:false,canSkipPrevious:false,canSeek:false,canSetVolume:false,canReadQueue:false},playback:{playing:false,positionMs:0,updatedAt:""},error:"Reconnect Spotify to continue."}}}
export async function exchange(code:string){const r=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{Authorization:`Basic ${Buffer.from(`${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`).toString("base64")}`,"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"authorization_code",code,redirect_uri:process.env.SPOTIFY_REDIRECT_URI??""})});if(!r.ok)throw new Error("Spotify authorization failed.");const d=await r.json() as Token&{expires_in:number};return {...d,expires_at:Date.now()+d.expires_in*1000}}
export async function storeAccountToken(userId:string, token:Token){const profileResponse=await fetch("https://api.spotify.com/v1/me",{headers:{Authorization:`Bearer ${token.access_token}`}});if(!profileResponse.ok)throw new Error("Spotify account identity could not be verified.");const profile=await profileResponse.json() as {id:string;display_name?:string;email?:string};const connection=await upsertProviderConnection(userId,{provider:"spotify",providerAccountId:profile.id,displayName:profile.display_name,email:profile.email});await setProviderCredentials(userId,connection.id,token as Record<string,unknown>);return connection;}
export async function accountToken(userId:string, connectionId:string){return getProviderCredentials<Token>(userId,connectionId)}
async function ownedToken(userId:string) { const connection = (await listProviderConnections(userId)).find((item) => item.provider === "spotify"); if (!connection) return null; const token = await getProviderCredentials<Token>(userId, connection.id); return token ? { token, connection } : null; }
export async function accountSnapshot(userId:string):Promise<MusicSnapshot>{ if (!configured()) return snapshot(); const owned = await ownedToken(userId); if (!owned) return { connected:false, capabilities:{...caps,canPlay:false,canPause:false,canSkipNext:false,canSkipPrevious:false,canSeek:false,canSetVolume:false,canReadQueue:false}, playback:{playing:false,positionMs:0,updatedAt:""}, error:"Connect Spotify to continue." }; return snapshotWithToken(owned.token); }
async function snapshotWithToken(t:Token):Promise<MusicSnapshot>{ try { const r=await fetch("https://api.spotify.com/v1/me/player",{headers:{Authorization:`Bearer ${t.access_token}`}}); if(r.status===204)return {provider:"spotify",connected:true,capabilities:caps,playback:{playing:false,positionMs:0,updatedAt:new Date().toISOString()}}; if(!r.ok)throw new Error(); const d=await r.json() as {is_playing:boolean;progress_ms:number;item?:{id:string;name:string;duration_ms:number;artists:{name:string}[];album?:{name:string;images?:{url:string;width?:number;height?:number}[]}};device?:{name:string;volume_percent?:number}}; return {provider:"spotify",connected:true,capabilities:caps,playback:{playing:d.is_playing,positionMs:d.progress_ms??0,durationMs:d.item?.duration_ms,volume:d.device?.volume_percent,deviceName:d.device?.name,updatedAt:new Date().toISOString(),track:d.item?{id:d.item.id,title:d.item.name,artists:d.item.artists.map(a=>a.name),album:d.item.album?.name,artworkUrl:selectSpotifyArtwork(d.item.album?.images),durationMs:d.item.duration_ms,provider:"spotify"}:undefined}}; } catch { return {provider:"spotify",connected:false,capabilities:{...caps,canPlay:false,canPause:false,canSkipNext:false,canSkipPrevious:false,canSeek:false,canSetVolume:false,canReadQueue:false},playback:{playing:false,positionMs:0,updatedAt:""},error:"Reconnect Spotify to continue."}; } }
export async function accountAction(userId:string,name:"play"|"pause"|"next"|"previous"|"seek"|"volume",value?:number){const owned=await ownedToken(userId);if(!owned)throw new Error("Connect Spotify to continue.");return actionWithToken(owned.token,name,value)}
export async function action(name:"play"|"pause"|"next"|"previous"|"seek"|"volume", value?:number){const t=await token();const paths={play:["PUT","/me/player/play"],pause:["PUT","/me/player/pause"],next:["POST","/me/player/next"],previous:["POST","/me/player/previous"],seek:["PUT",`/me/player/seek?position_ms=${value}`],volume:["PUT",`/me/player/volume?volume_percent=${value}`]} as const;const [method,path]=paths[name];const r=await fetch(`https://api.spotify.com/v1${path}`,{method,headers:{Authorization:`Bearer ${t.access_token}`}});if(!r.ok){if(r.status===404)throw new Error("Spotify playback control requires an active Spotify device.");if(r.status===403)throw new Error("Spotify playback control is unavailable for this account.");throw new Error("Spotify could not complete that playback action.")}}
async function actionWithToken(t:Token,name:"play"|"pause"|"next"|"previous"|"seek"|"volume",value?:number){const paths={play:["PUT","/me/player/play"],pause:["PUT","/me/player/pause"],next:["POST","/me/player/next"],previous:["POST","/me/player/previous"],seek:["PUT",`/me/player/seek?position_ms=${value}`],volume:["PUT",`/me/player/volume?volume_percent=${value}`]} as const;const [method,path]=paths[name];const r=await fetch(`https://api.spotify.com/v1${path}`,{method,headers:{Authorization:`Bearer ${t.access_token}`}});if(!r.ok)throw new Error("Spotify could not complete that playback action.")}
