import type { Note, NotesLocalData } from "@/core/contracts/Notes";
import type { ProjectsLocalData } from "@/core/contracts/Projects";
import type { CosmicSettingsLocalData } from "@/core/contracts/Settings";
import type { FinanceSnapshot } from "@/core/contracts/Finance";
import type { GarageLocalData } from "@/core/contracts/Garage";
import type { LocalSchoolData } from "@/components/school/data/localRepository";

function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function text(value: unknown, max: number): value is string { return typeof value === "string" && value.length <= max; }
function size(value: unknown, max: number) { try { return JSON.stringify(value).length <= max; } catch { return false; } }

export function validateSettingsSync(value: unknown): value is CosmicSettingsLocalData { if (!record(value) || value.version !== 1 || !record(value.appearance) || typeof value.appearance.reducedEffects !== "boolean" || !record(value.background) || !["low", "normal", "high"].includes(String(value.background.intensity)) || !["off", "subtle", "normal"].includes(String(value.background.motion)) || !record(value.ambient) || typeof value.ambient.enabled !== "boolean" || ![null, 1, 2, 5, 10, 15, 30].includes(value.ambient.idleMinutes as number | null) || !record(value.system) || !["automatic", "full", "balanced", "reduced"].includes(String(value.system.performanceMode)) || !["automatic", "desktop", "tablet", "phone", "display"].includes(String(value.system.deviceProfileOverride)) || !record(value.preferences) || !record(value.preferences.sports) || !record(value.preferences.dashboard) || !record(value.preferences.modules) || !record(value.preferences.context)) return false; return size(value, 250_000); }
function validNote(value: unknown): value is Note { return record(value) && text(value.id, 200) && text(value.title, 500) && text(value.body, 200_000) && Array.isArray(value.tags) && value.tags.length <= 100 && value.tags.every((tag) => text(tag, 100)) && (value.folder === undefined || text(value.folder, 200)) && typeof value.pinned === "boolean" && typeof value.archived === "boolean" && text(value.createdAt, 80) && text(value.updatedAt, 80); }
export function validateNotesSync(value: unknown): value is NotesLocalData { return record(value) && value.version === 1 && Array.isArray(value.notes) && value.notes.length <= 10_000 && value.notes.every(validNote) && size(value, 2_000_000); }
function validEntity(value: unknown) { return record(value) && text(value.id, 200); }
export function validateProjectsSync(value: unknown): value is ProjectsLocalData { if (!record(value) || value.version !== 1 || !Array.isArray(value.projects) || !Array.isArray(value.tasks) || !Array.isArray(value.milestones) || value.projects.length > 5_000 || value.tasks.length > 20_000 || value.milestones.length > 10_000 || !value.projects.every(validEntity) || !value.tasks.every(validEntity) || !value.milestones.every(validEntity) || (value.selectedProjectId !== undefined && !text(value.selectedProjectId, 200))) return false; return size(value, 4_000_000); }
function integer(value: unknown, minimum = Number.MIN_SAFE_INTEGER) { return typeof value === "number" && Number.isSafeInteger(value) && value >= minimum; }
export function validateFinanceSync(value: unknown): value is FinanceSnapshot { if (!record(value) || value.version !== 1 || !Array.isArray(value.accounts) || !Array.isArray(value.categories) || !Array.isArray(value.transactions) || !Array.isArray(value.recurringItems) || !Array.isArray(value.budgets) || typeof value.hideBalances !== "boolean" || value.accounts.length > 100 || value.transactions.length > 100_000 || value.recurringItems.length > 10_000 || value.budgets.length > 10_000 || !size(value, 10_000_000)) return false; const accounts = value.accounts.filter((item) => record(item) && text(item.id, 200) && text(item.name, 300) && ["checking", "savings", "cash", "credit", "other"].includes(String(item.type)) && integer(item.startingBalanceMinor) && typeof item.archived === "boolean"); const accountIds = new Set(accounts.map((item) => item.id)); const categories = value.categories.filter((item) => record(item) && text(item.id, 200) && text(item.name, 200) && typeof item.system === "boolean" && typeof item.archived === "boolean"); const categoryIds = new Set(categories.map((item) => item.id)); const validTransactions = value.transactions.every((item) => record(item) && text(item.id, 200) && accountIds.has(String(item.accountId)) && categoryIds.has(String(item.categoryId)) && text(item.date, 80) && text(item.description, 500) && integer(item.amountMinor, 0) && ["income", "expense", "transfer"].includes(String(item.direction)) && ["pending", "cleared"].includes(String(item.status))); const validRecurring = value.recurringItems.every((item) => record(item) && text(item.id, 200) && accountIds.has(String(item.accountId)) && categoryIds.has(String(item.categoryId)) && integer(item.amountMinor, 0)); const validBudgets = value.budgets.every((item) => record(item) && text(item.id, 200) && categoryIds.has(String(item.categoryId)) && integer(item.monthlyLimitMinor, 0)); return validTransactions && validRecurring && validBudgets; }
export function validateGarageSync(value: unknown): value is GarageLocalData { if (!record(value) || value.version !== 1 || !Array.isArray(value.vehicles) || !Array.isArray(value.maintenance) || !Array.isArray(value.services) || !Array.isArray(value.issues) || !Array.isArray(value.modifications) || !Array.isArray(value.expenses) || !Array.isArray(value.reminders) || !Array.isArray(value.mileageHistory) || (value.fuelRecords !== undefined && !Array.isArray(value.fuelRecords)) || (value.documents !== undefined && !Array.isArray(value.documents)) || (value.collections !== undefined && !Array.isArray(value.collections)) || (value.connections !== undefined && !Array.isArray(value.connections)) || (value.diagnosticScans !== undefined && !Array.isArray(value.diagnosticScans)) || (value.telemetrySnapshots !== undefined && !Array.isArray(value.telemetrySnapshots)) || (value.repairEstimates !== undefined && !Array.isArray(value.repairEstimates)) || value.vehicles.length > 100 || !size(value, 10_000_000)) return false; const vehicleIds = new Set(value.vehicles.filter(validEntity).map((item) => item.id)); const fuelRecords = Array.isArray(value.fuelRecords) ? value.fuelRecords : []; const documents = Array.isArray(value.documents) ? value.documents : []; const collections = Array.isArray(value.collections) ? value.collections : []; const connections = Array.isArray(value.connections) ? value.connections : []; const scans = Array.isArray(value.diagnosticScans) ? value.diagnosticScans : []; const estimates = Array.isArray(value.repairEstimates) ? value.repairEstimates : []; const children = [...value.maintenance, ...value.services, ...value.issues, ...value.modifications, ...value.expenses, ...value.reminders, ...value.mileageHistory, ...fuelRecords, ...documents, ...connections, ...scans, ...estimates]; const fuelValid = fuelRecords.every((item) => record(item) && validEntity(item) && vehicleIds.has(String(item.vehicleId)) && text(item.date, 80) && typeof item.odometer === "number" && item.odometer >= 0 && typeof item.gallons === "number" && item.gallons > 0 && (item.totalCostMinor === undefined || integer(item.totalCostMinor, 0)) && (item.pricePerGallonMinor === undefined || integer(item.pricePerGallonMinor, 0)) && typeof item.fullTank === "boolean"); const documentsValid = documents.every((item) => record(item) && validEntity(item) && vehicleIds.has(String(item.vehicleId)) && text(item.title, 300) && text(item.storageFileId, 300)); const collectionsValid = collections.every((item) => record(item) && validEntity(item) && text(item.name, 200)); return value.vehicles.every(validEntity) && children.every((item) => validEntity(item) && record(item) && vehicleIds.has(String(item.vehicleId))) && fuelValid && documentsValid && collectionsValid; }
export function validateSchoolSync(value: unknown): value is LocalSchoolData { if (!record(value) || value.version !== 1 || !Array.isArray(value.terms) || !Array.isArray(value.courses) || !Array.isArray(value.assignments) || !Array.isArray(value.grades) || !Array.isArray(value.goals) || !Array.isArray(value.resources) || value.terms.length > 100 || value.courses.length > 1_000 || value.assignments.length > 20_000 || !size(value, 10_000_000)) return false; return [...value.terms, ...value.courses, ...value.assignments, ...value.grades, ...value.goals, ...value.resources].every(validEntity); }
