import Link from "next/link";
import { DONUT_STAGE_LABELS } from "@/services/donuts/config";
import { PRODUCTION_STAGES, type ProductionStage } from "@/services/donuts/domain";
import { DonutsFooter, DonutsNav } from "./DonutsNav";

export function DonutTracking({ token }: { token: string }) {
  const demo = token === "demo-order";
  const current: ProductionStage = demo ? "Frying" : "Accepted";
  const currentIndex = PRODUCTION_STAGES.indexOf(current);
  return <main className="donuts-shell"><DonutsNav /><section className="donuts-pagehead"><div className="donuts-kicker">Private order tracking</div><h1>Your donut orbit.</h1><p>This page only shows the scoped order represented by your secure tracking link. Order numbers alone are never enough to reveal customer details.</p></section>{demo ? <><div className="donuts-banner"><span><strong>Preview order</strong> · Saturday, July 18 · 9:00–11:00 a.m.</span><span className="donuts-status">Live updates when configured</span></div><section className="donuts-section"><div className="donuts-admin-grid"><div className="donuts-panel"><div className="donuts-kicker">Current stage</div><h2 style={{ fontSize:"clamp(2rem,5vw,4rem)", margin:".5rem 0" }}>{DONUT_STAGE_LABELS[current]}</h2><p className="donuts-lede">Your batch is moving through the kitchen. We show actual updates from the baker—never an invented countdown or ETA.</p><div className="donuts-help" style={{ marginTop:"1rem" }}>Delivery window: Saturday · 9:00–11:00 a.m.</div></div><div className="donuts-panel"><div className="donuts-kicker">Detailed production</div><div className="donuts-track" style={{ marginTop:"1rem" }}>{PRODUCTION_STAGES.map((stage, index) => <div key={stage}><div className={`donuts-track-stage ${index <= currentIndex ? "active" : ""}`}><span className="donuts-track-dot" aria-hidden="true" /><span>{DONUT_STAGE_LABELS[stage]}{index === currentIndex && <small style={{ display:"block", color:"#ffafd9", marginTop:".2rem" }}>Updated by the kitchen</small>}</span></div>{index < PRODUCTION_STAGES.length - 1 && <div className="donuts-track-line" aria-hidden="true" />}</div>)}</div></div></div></section></> : <section className="donuts-panel"><h2>Tracking link unavailable</h2><p className="donuts-lede">This link is not valid or has expired. Ask Cosmic Donuts for a fresh tracking link.</p></section>}<div className="donuts-actions"><Link href="/donuts" className="donuts-button secondary">Back to Cosmic Donuts</Link></div><DonutsFooter /></main>;
}
