import Link from "next/link";
import { DONUT_STAGE_LABELS } from "@/services/donuts/config";
import { PRODUCTION_STAGES, TRACKING_MILESTONES, type ProductionStage } from "@/services/donuts/domain";
import { DonutsFooter, DonutsNav } from "./DonutsNav";

type TrackedOrder = { publicOrderNumber: string; status: string; productionStage: ProductionStage | null; deliveryDate: string; deliveryWindow: string };
function stageIndex(stage: ProductionStage) { return PRODUCTION_STAGES.indexOf(stage); }

export function DonutTracking({ token, order }: { token: string; order?: TrackedOrder | null }) {
  const demo = token === "demo-order";
  const tracked = demo || order;
  const current: ProductionStage = order?.productionStage ?? (demo ? "Frying" : "Accepted");
  const currentIndex = stageIndex(current);
  return <main className="donuts-shell"><DonutsNav /><section className="donuts-pagehead"><div className="donuts-kicker">Private order tracking</div><h1>Your donut orbit.</h1><p>This page only shows the scoped order represented by your secure tracking link. Order numbers alone are never enough to reveal customer details.</p></section>{tracked ? <><div className="donuts-banner"><span><strong>{demo ? "Demo tracking only." : `Order ${order?.publicOrderNumber}`}</strong> {demo ? "This is sample stage data, not a customer order." : "This is a private, token-scoped order view."}</span><span className="donuts-status">No ETA or countdown</span></div><section className="donuts-section"><div className="donuts-panel"><div className="donuts-kicker">Current stage</div><h2 style={{ fontSize:"clamp(2rem,5vw,4rem)", margin:".5rem 0" }}>{DONUT_STAGE_LABELS[current]}</h2><p className="donuts-lede">A real order will reflect timestamps recorded by the kitchen. It will never invent a countdown or delivery estimate.</p><div className="donuts-help" style={{ marginTop:"1rem" }}>{demo ? "Demo delivery date/window: Saturday, July 18 · 9:00–11:00 a.m." : `Delivery date/window: ${order?.deliveryDate} · ${order?.deliveryWindow}`}</div></div><div className="donuts-panel" style={{ marginTop:"1rem" }}><div className="donuts-kicker">Four main milestones</div><div className="donuts-grid" style={{ marginTop:"1rem" }}>{TRACKING_MILESTONES.map((milestone, index) => <div className="donuts-admin-stat" key={milestone.id}><small>0{index + 1}</small><strong style={{ fontSize:"1.15rem" }}>{milestone.label}</strong><span className="donuts-help">{stageIndex(milestone.stage) <= currentIndex ? "Complete or in progress" : "Not started"}</span></div>)}</div></div><details className="donuts-panel" style={{ marginTop:"1rem" }} open><summary style={{ cursor:"pointer", fontWeight:800 }}>Detailed production stages</summary><div className="donuts-track" style={{ marginTop:"1rem" }}>{PRODUCTION_STAGES.map((stage, index) => <div key={stage}><div className={`donuts-track-stage ${index <= currentIndex ? "active" : ""}`}><span className="donuts-track-dot" aria-hidden="true" /><span>{DONUT_STAGE_LABELS[stage]}{index === currentIndex && <small style={{ display:"block", color:"#ffafd9", marginTop:".2rem" }}>{demo ? "Demo current stage" : "Current production stage"}</small>}</span></div>{index < PRODUCTION_STAGES.length - 1 && <div className="donuts-track-line" aria-hidden="true" />}</div>)}</div></details></section></> : <section className="donuts-panel"><h2>Tracking link unavailable</h2><p className="donuts-lede">This link is not valid or has expired. Real tracking links are scoped to a stored token hash and never expose an order from an order number alone.</p></section>}<div className="donuts-actions"><Link href="/donuts" className="donuts-button secondary">Back to Cosmic Donuts</Link></div><DonutsFooter /></main>;
}
