/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import LegalFooter from "@/components/legal/LegalFooter";

export const metadata: Metadata = { title: "Terms of Service", description: "Terms for using Cosmic OS and Cosmic+.", alternates: { canonical: "/terms" } };

export default function TermsPage() { return <main className="min-h-screen bg-[#030511] text-white"><article className="mx-auto max-w-4xl space-y-8 px-6 py-12 sm:px-10"><p className="text-xs font-semibold uppercase tracking-[.24em] text-cyan-100/55">Cosmic OS</p><h1 className="text-4xl font-black tracking-tight sm:text-5xl">Terms of Service</h1><p className="text-sm text-white/45">Last updated: August 23, 2026</p><p className="text-base leading-7 text-white/65">These terms describe the basic rules for using Cosmic OS, an evolving independent software project. By using Cosmic, you agree to use it responsibly and understand that the service may change.</p><TermsSection title="Service, accounts, and integrations"><p>Features, integrations, availability, storage limits, and pricing may change. You are responsible for your account activity. Connected providers remain governed by their own terms and policies; review permissions before connecting them.</p></TermsSection><TermsSection title="Connected Finance disclosure"><p>Cosmic is not a bank, does not hold customer funds, and does not guarantee that connected balances or transactions are current, complete, or error-free. Financial connectivity depends on third-party provider and institution availability; no provider covers every institution. Connected Finance data is informational and may be delayed or unavailable when an institution or provider is unavailable. Do not use Cosmic as a substitute for professional financial, medical, legal, academic, or safety advice.</p></TermsSection><TermsSection title="Advertising and Cosmic+"><p>Free-plan surfaces may include clearly labeled advertising when enabled and approved. Cosmic+ benefits may include ad-free use and other features described in the product. Cosmic does not guarantee advertising inventory or revenue.</p></TermsSection><TermsSection title="Billing, termination, and changes"><p>Cosmic+ billing is handled by Stripe when configured. Stripe's payment and billing terms also apply. We may suspend or terminate accounts that violate these terms or create security risk. Account deletion is handled through the Account page and may be irreversible. Cosmic is provided on an “as available” basis and is not responsible for third-party services or content.</p></TermsSection><TermsSection title="Support"><p>Questions, bug reports, and feedback can be submitted through the public <a className="text-cyan-100 underline" href="/support">Support</a> route.</p></TermsSection></article><LegalFooter /></main>; }

function TermsSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="space-y-3 border-t border-white/10 pt-6"><h2 className="text-xl font-semibold text-white/85">{title}</h2><div className="space-y-3 text-sm leading-7 text-white/58">{children}</div></section>; }
