import type { BaseballLiveData } from "./Baseball";
import type { FootballLiveData } from "./Football";
import type { F1LiveData } from "./F1";
import type { NascarLiveData } from "./Nascar";
import type { BasketballLiveData } from "./Basketball";

export type SportKind =
  | "mlb"
  | "nfl"
  | "nba"
  | "f1"
  | "nascar"
  | "college-football";

export type SportsEventStatus =
  | "scheduled"
  | "pregame"
  | "live"
  | "delayed"
  | "suspended"
  | "final"
  | "postponed"
  | "cancelled";

export type SportsProviderStatus =
  | "ok"
  | "degraded"
  | "unavailable";

export interface SportsProviderCapabilities {
  schedule?: boolean;
  liveScore?: boolean;
  liveState?: boolean;
  playByPlay?: boolean;
  standings?: boolean;
  results?: boolean;
  stats?: boolean;
  sessions?: boolean;
  timing?: boolean;
  telemetry?: boolean;
  weather?: boolean;
}

export interface SportsDataSource {
  /**
   * Stable Cosmic identifier for the provider.
   *
   * Examples:
   * "mlb-stats"
   * "espn-nfl"
   * "jolpica"
   * "nascar-live"
   */
  id: string;

  sport: SportKind;

  name: string;

  /**
   * True when the data is coming from the league/series itself.
   *
   * ESPN NFL data, for example, would be false.
   * MLB Stats API would be true.
   */
  official: boolean;

  status: SportsProviderStatus;

  capabilities: SportsProviderCapabilities;

  /**
   * How long Cosmic intends to cache this provider's data.
   */
  cacheSeconds: number;

  /**
   * When Cosmic most recently successfully fetched this source.
   */
  lastSuccessAt?: string;

  /**
   * When this particular data payload was fetched.
   */
  fetchedAt?: string;

  /**
   * Provider timestamp representing when the upstream data was current,
   * if the provider supplies one.
   */
  dataAsOf?: string;

  /**
   * True when Cosmic is serving an older last-known-good result.
   */
  stale?: boolean;

  /**
   * Human-readable provider error for diagnostics.
   * This should not normally be displayed directly to kiosk users.
   */
  error?: string;
}

export interface SportsProviderRef {
  provider: string;
  id: string;
}

export interface SportsTeamRef {
  id?: string;
  name: string;
  abbreviation?: string;
  logo?: string;
}

export interface SportsCompetitorRef {
  id?: string;
  name: string;

  /**
   * Used for racing competitors such as Max Verstappen
   * or Carson Hocevar.
   */
  number?: string;

  team?: string;
}

export interface SportsEventRef {
  /**
   * Cosmic's stable event ID.
   *
   * Do not assume this is identical to an upstream provider ID.
   */
  id: string;

  sport: SportKind;

  title: string;

  startTime: string;

  endTime?: string;

  status: SportsEventStatus;

  statusDetail?: string;

  venue?: string;

  broadcast?: string;

  homeTeam?: SportsTeamRef;

  awayTeam?: SportsTeamRef;

  competitors?: SportsCompetitorRef[];

  /**
   * IDs used to find this event in upstream systems.
   *
   * Example:
   *
   * [
   *   { provider: "espn", id: "401772934" }
   * ]
   */
  providerRefs: SportsProviderRef[];
}

/**
 * Information common to every detailed live-data response.
 */
export interface SportsLiveDataBase {
  eventId: string;

  sport: SportKind;

  /**
   * ISO timestamp generated by Cosmic when this normalized
   * live object was assembled.
   */
  generatedAt: string;

  /**
   * Every upstream source that contributed to this result.
   */
  sources: SportsDataSource[];

  /**
   * True when at least one important part of this live response
   * is using last-known-good data.
   */
  stale: boolean;
}

/**
 * Sport-specific detailed live state.
 *
 * Consumers can discriminate using `sport`.
 *
 * Example:
 *
 * if (live.sport === "nfl") {
 *   console.log(live.down);
 * }
 */
export type SportsLiveData =
  | BaseballLiveData
  | FootballLiveData
  | BasketballLiveData
  | F1LiveData
  | NascarLiveData;
