"use client";
import { useEffect, useId } from "react";
import Link from "next/link";
import Widget from "@/components/os/ui/widget/Widget";
import WidgetHeader from "@/components/os/ui/widget/WidgetHeader";
import WidgetBody from "@/components/os/ui/widget/WidgetBody";
import WidgetFooter from "@/components/os/ui/widget/WidgetFooter";
import { WidgetEmpty, WidgetError, WidgetLoading } from "@/components/os/ui/widget";
import { useWidgetContext } from "@/components/os/ui/widget/WidgetContext";
import { useMusic } from "@/hooks/os/useMusic";
import KioskMusicWidget from "./KioskMusicWidget";
export default function MusicWidget(){const {size,presentation,active}=useWidgetContext();const instanceId=useId();const m=useMusic({refreshMs:presentation==="kiosk"?1_000:undefined,enabled:presentation!=="kiosk"||active});const track=m.playback?.track;const mediaKind=track?.mediaType??m.playback?.mediaType??"unknown";const mediaLabel=mediaKind==="podcast"?"Podcast":mediaKind==="audiobook"?"Audiobook":mediaKind==="music"?"Song":"Now Playing";const mediaSubtitle=track?.subtitle??track?.artists.join(", ")??"";useEffect(()=>{if(process.env.NODE_ENV!=="production")console.info(`[music-widget] mount id=${instanceId} presentation=${presentation} active=${active}`);return()=>{if(process.env.NODE_ENV!=="production")console.info(`[music-widget] unmount id=${instanceId}`)}},[active,instanceId,presentation]);if(presentation==="kiosk")return active?<KioskMusicWidget music={m}/>:null;return <Widget accent="music" imageUrl={track?.artworkUrl} imageOpacity={.68} imageBlur={0}><WidgetHeader title={track?"Now Playing":"Music"} subtitle={track?mediaLabel:"Standby"}/><WidgetBody>{m.loading?<WidgetLoading compact label="Loading music"/>:m.error?<WidgetError compact title="Music unavailable" message={m.error}/>:!m.connected?<WidgetEmpty compact title="No music connected" description="Configure an official provider in Music."/>:!track?<WidgetEmpty compact title="Nothing playing" description="Cosmic Music is ready when media starts."/>:<div className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/5 p-3"><div className="h-16 w-16 shrink-0 overflow-hidden rounded-lg bg-black/25">{track.artworkUrl?<img src={track.artworkUrl} alt="" draggable={false} className="h-full w-full object-cover" onError={(event)=>{event.currentTarget.style.display="none";}}/>:<span className="grid h-full place-items-center text-2xl text-fuchsia-100/70">♫</span>}</div><div className="min-w-0"><p className="truncate font-medium">{track.title}</p><p className="truncate text-sm text-white/55">{mediaSubtitle}</p>{size!=="small"&&<p className="mt-2 text-xs text-white/45">{m.playback?.playing?"Playing":"Paused"}{track.album?` · ${track.album}`:""}{m.playback?.deviceName?` · ${m.playback.deviceName}`:""}</p>}</div></div>}</WidgetBody><WidgetFooter><Link className="text-xs text-cyan-100" href="/music">Open Music</Link></WidgetFooter></Widget>}
