"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { GarageLocalData, Vehicle, VehicleExpense, VehicleIssue, VehicleMaintenanceItem, VehicleMileageEntry, VehicleModification, VehicleReminder, VehicleServiceRecord } from "@/core/contracts/Garage";

export const GARAGE_STORAGE_KEY = "cosmic.garage.local-data";
export const GARAGE_UPDATE_EVENT = "cosmic:garage-local-data-updated";
export const emptyGarageData: GarageLocalData = { version: 1, vehicles: [], maintenance: [], services: [], issues: [], modifications: [], expenses: [], reminders: [], mileageHistory: [] };

function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function rows<T extends { id: string }>(value: unknown, isItem: (item: unknown) => item is T): T[] { return Array.isArray(value) ? value.filter(isItem) : []; }
function isVehicle(value: unknown): value is Vehicle { return isRecord(value) && typeof value.id === "string" && typeof value.nickname === "string" && typeof value.year === "number" && typeof value.make === "string" && typeof value.model === "string" && typeof value.currentMileage === "number" && typeof value.status === "string" && typeof value.createdAt === "string" && typeof value.updatedAt === "string"; }
function isVehicleEntry<T extends { id: string; vehicleId: string }>(value: unknown): value is T { return isRecord(value) && typeof value.id === "string" && typeof value.vehicleId === "string"; }
export function readGarageSnapshot(): GarageLocalData { try { const raw = window.localStorage.getItem(GARAGE_STORAGE_KEY); if (!raw) return emptyGarageData; const data: unknown = JSON.parse(raw); if (!isRecord(data) || data.version !== 1) return emptyGarageData; return { version: 1, ...(typeof data.selectedVehicleId === "string" ? { selectedVehicleId: data.selectedVehicleId } : {}), vehicles: rows(data.vehicles, isVehicle), maintenance: rows(data.maintenance, isVehicleEntry<VehicleMaintenanceItem>), services: rows(data.services, isVehicleEntry<VehicleServiceRecord>), issues: rows(data.issues, isVehicleEntry<VehicleIssue>), modifications: rows(data.modifications, isVehicleEntry<VehicleModification>), expenses: rows(data.expenses, isVehicleEntry<VehicleExpense>), reminders: rows(data.reminders, isVehicleEntry<VehicleReminder>), mileageHistory: rows(data.mileageHistory, isVehicleEntry<VehicleMileageEntry>) }; } catch { return emptyGarageData; } }
export function replaceGarageSnapshot(data: GarageLocalData) { if (data.version !== 1 || !Array.isArray(data.vehicles) || !Array.isArray(data.maintenance) || !Array.isArray(data.services) || !Array.isArray(data.issues) || !Array.isArray(data.modifications) || !Array.isArray(data.expenses) || !Array.isArray(data.reminders) || !Array.isArray(data.mileageHistory)) throw new Error("Invalid Garage data."); window.localStorage.setItem(GARAGE_STORAGE_KEY, JSON.stringify(data)); window.dispatchEvent(new CustomEvent(GARAGE_UPDATE_EVENT, { detail: data })); }
function upsert<T extends { id: string }>(items: T[], item: T): T[] { return items.some((entry) => entry.id === item.id) ? items.map((entry) => entry.id === item.id ? item : entry) : [...items, item]; }

export function useGarageRepository() {
  const [data, setData] = useState<GarageLocalData>(emptyGarageData);
  const [ready, setReady] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { setData(readGarageSnapshot()); setReady(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (!ready) return; window.localStorage.setItem(GARAGE_STORAGE_KEY, JSON.stringify(data)); window.dispatchEvent(new CustomEvent(GARAGE_UPDATE_EVENT, { detail: data })); }, [data, ready]);
  useEffect(() => { const sync = (event: StorageEvent) => { if (event.key === GARAGE_STORAGE_KEY) setData(readGarageSnapshot()); }; const local = (event: Event) => { if (event instanceof CustomEvent && isRecord(event.detail)) { const next = event.detail as unknown as GarageLocalData; setData((current) => JSON.stringify(current) === JSON.stringify(next) ? current : next); } }; window.addEventListener("storage", sync); window.addEventListener(GARAGE_UPDATE_EVENT, local); return () => { window.removeEventListener("storage", sync); window.removeEventListener(GARAGE_UPDATE_EVENT, local); }; }, []);
  const update = useCallback((recipe: (current: GarageLocalData) => GarageLocalData) => setData((current) => recipe(current)), []);
  const removeVehicle = useCallback((id: string) => update((current) => ({ ...current, selectedVehicleId: current.selectedVehicleId === id ? current.vehicles.find((vehicle) => vehicle.id !== id)?.id : current.selectedVehicleId, vehicles: current.vehicles.filter((item) => item.id !== id), maintenance: current.maintenance.filter((item) => item.vehicleId !== id), services: current.services.filter((item) => item.vehicleId !== id), issues: current.issues.filter((item) => item.vehicleId !== id), modifications: current.modifications.filter((item) => item.vehicleId !== id), expenses: current.expenses.filter((item) => item.vehicleId !== id), reminders: current.reminders.filter((item) => item.vehicleId !== id), mileageHistory: current.mileageHistory.filter((item) => item.vehicleId !== id) })), [update]);
  const selectedVehicle = useMemo(() => data.vehicles.find((vehicle) => vehicle.id === data.selectedVehicleId) ?? data.vehicles[0], [data]);
  return { data, ready, selectedVehicle, selectVehicle: (id: string) => update((current) => ({ ...current, selectedVehicleId: id })), saveVehicle: (vehicle: Vehicle) => update((current) => ({ ...current, selectedVehicleId: current.selectedVehicleId ?? vehicle.id, vehicles: upsert(current.vehicles, vehicle) })), removeVehicle, saveMaintenance: (item: VehicleMaintenanceItem) => update((current) => ({ ...current, maintenance: upsert(current.maintenance, item) })), removeMaintenance: (id: string) => update((current) => ({ ...current, maintenance: current.maintenance.filter((item) => item.id !== id) })), saveService: (item: VehicleServiceRecord) => update((current) => ({ ...current, services: upsert(current.services, item) })), removeService: (id: string) => update((current) => ({ ...current, services: current.services.filter((item) => item.id !== id) })), saveIssue: (item: VehicleIssue) => update((current) => ({ ...current, issues: upsert(current.issues, item) })), removeIssue: (id: string) => update((current) => ({ ...current, issues: current.issues.filter((item) => item.id !== id) })), saveModification: (item: VehicleModification) => update((current) => ({ ...current, modifications: upsert(current.modifications, item) })), removeModification: (id: string) => update((current) => ({ ...current, modifications: current.modifications.filter((item) => item.id !== id) })), saveExpense: (item: VehicleExpense) => update((current) => ({ ...current, expenses: upsert(current.expenses, item) })), removeExpense: (id: string) => update((current) => ({ ...current, expenses: current.expenses.filter((item) => item.id !== id) })), saveReminder: (item: VehicleReminder) => update((current) => ({ ...current, reminders: upsert(current.reminders, item) })), removeReminder: (id: string) => update((current) => ({ ...current, reminders: current.reminders.filter((item) => item.id !== id) })), updateMileage: (vehicleId: string, mileage: number, date: string) => update((current) => ({ ...current, vehicles: current.vehicles.map((vehicle) => vehicle.id === vehicleId ? { ...vehicle, currentMileage: mileage, updatedAt: new Date().toISOString() } : vehicle), mileageHistory: [...current.mileageHistory, { id: crypto.randomUUID(), vehicleId, mileage, date }] })) };
}
