"use client";
import Link from "next/link";
import { ArrowLeft, BookOpen, Clock3, MapPin } from "lucide-react";
import { use } from "react";
import { useSchool } from "@/components/school/context/SchoolDataContext";
import type { CoursePlan } from "@/services/school/coursePlan";

const panel = "rounded-[1.35rem] border border-white/[0.09] bg-[#101c35]/75 p-5";
export default function CourseDetailPage({ params }: { params: Promise<{ courseId: string }> }) { const { courseId } = use(params); const { local, snapshot, loading } = useSchool(); const course = local.data.courses.find((item) => item.id === decodeURIComponent(courseId)); if (loading) return <p className="py-16 text-sm text-white/50">Loading course…</p>; if (!course) return <div className={panel}><p className="text-white/60">Course not found.</p><Link href="/school/courses" className="mt-4 inline-block text-sky-100/80">← Back to courses</Link></div>;
  const plan = snapshot?.coursePlans?.find((item) => item.courseId === course.id); const assignments = (snapshot?.planningAssignments ?? []).filter((item) => item.courseId === course.id || item.courseName === course.name || item.courseName === course.code); const notes = (snapshot?.notes ?? []).filter((item) => item.courseId === course.id); const active = assignments.filter((item) => item.completionStatus !== "completed" && item.completionStatus !== "graded" && item.planningStatus !== "done");
  return <div className="space-y-5"><Link href="/school/courses" className="inline-flex items-center gap-2 text-sm text-white/45 hover:text-white"><ArrowLeft className="size-4" /> Courses</Link><header className={panel}><div className="flex items-start gap-4"><span className="grid size-11 place-items-center rounded-2xl bg-sky-300/10 text-sky-100"><BookOpen className="size-5" /></span><div><p className="text-xs uppercase tracking-[0.2em] text-sky-200/55">{course.code ?? "Course"}</p><h1 className="mt-1 text-3xl font-black tracking-[-0.04em] text-white">{course.name}</h1><p className="mt-2 text-sm text-white/45">{course.section ? `Section ${course.section} · ` : ""}{course.termId}</p></div></div><div className="mt-5 flex flex-wrap gap-3">{course.meetingTimes.map((meeting, index) => <span key={index} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-3 py-2 text-xs text-white/55"><Clock3 className="size-3.5" /> {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"][meeting.weekday]} {meeting.startTime}–{meeting.endTime}{meeting.location ? <><MapPin className="ml-1 size-3.5" />{meeting.location}</> : null}</span>)}</div></header><section className="grid gap-3 sm:grid-cols-3"><Stat label="Active assignments" value={active.length} /><Stat label="Completed" value={assignments.length - active.length} /><Stat label="Approved plan" value={plan ? "Ready" : "None"} /></section>{plan && <CoursePlanView plan={plan} /> }<section className={panel}><p className="text-[10px] uppercase tracking-[0.2em] text-sky-200/55">Assignments</p><div className="mt-3 space-y-2">{assignments.map((item) => <Link key={item.id} href={`/school/assignments/${encodeURIComponent(item.id)}`} className="flex items-center justify-between gap-3 rounded-xl border border-white/[0.07] px-3 py-3"><span className="truncate text-sm text-white/75">{item.title}</span><span className="text-xs text-white/40">{item.dueAt ? item.dueAt.toLocaleDateString() : "No due date"}</span></Link>)}</div></section><section className={panel}><p className="text-[10px] uppercase tracking-[0.2em] text-sky-200/55">Recent notes</p>{notes.slice(0, 5).map((note) => <Link key={note.id} href={`/school/notes/${note.id}`} className="mt-3 block rounded-xl border border-white/[0.07] p-3"><p className="text-sm text-white/75">{note.title}</p><p className="mt-1 line-clamp-2 text-xs text-white/45">{note.content}</p></Link>)}{!notes.length && <p className="mt-3 text-sm text-white/45">No approved study context for this course yet.</p>}</section></div>;
}
function CoursePlanView({ plan }: { plan: CoursePlan }) { const meetings = plan.meetingSchedule.map((item) => formatMeeting(item)); const office = plan.officeHours.map((item) => formatOffice(item)); const grades = plan.gradeScale.map((item) => formatGrade(item)); const books = plan.textbooks.map((item) => formatBook(item)); const weekly = plan.weeklySchedule.map((item) => `${item.week ? `Week ${item.week} · ` : ""}${item.value}`); const recurring = plan.recurringExpectations.map((item) => String(item.description ?? item.value ?? "")); return <><div className="grid gap-3 md:grid-cols-2"><PlanPanel title="Class" items={meetings} /><PlanPanel title="Office hours" items={office} /><PlanPanel title="Grade scale" items={grades} /><PlanPanel title="Textbooks" items={books} /><PlanPanel title="Materials" items={plan.materials} /><PlanPanel title="Policies" items={plan.policies.map((item) => `${item.subject}: ${item.value}`)} /></div><section className={`${panel} space-y-4`}><PlanList title="Weekly schedule" items={weekly} /><PlanList title="Recurring expectations" items={recurring} /><PlanList title="Semester timeline" items={[...plan.exams.map((item) => `${item.title}${item.date ? ` · ${new Date(item.date).toLocaleDateString()}` : ""}`), ...plan.majorAssignments.map((item) => `${item.title}${item.dueAt ? ` · ${new Date(item.dueAt).toLocaleDateString()}` : ""}`)]} /><p className="text-xs text-white/35">Source: approved CoursePlan knowledge · {plan.sourceIds.length} source{plan.sourceIds.length === 1 ? "" : "s"}</p></section></>; }
function formatMeeting(item: Record<string, unknown>) { const days = Array.isArray(item.daysOfWeek) ? item.daysOfWeek.join(" / ") : ""; return [days, item.startTime && item.endTime ? `${item.startTime}–${item.endTime}` : "", typeof item.location === "string" ? item.location : ""].filter(Boolean).join(" · "); }
function formatOffice(item: Record<string, unknown>) { return [Array.isArray(item.daysOfWeek) ? item.daysOfWeek.join(" / ") : "", item.startTime && item.endTime ? `${item.startTime}–${item.endTime}` : "", typeof item.location === "string" ? item.location : "", typeof item.notes === "string" ? item.notes : "", typeof item.virtualUrl === "string" ? item.virtualUrl : ""].filter(Boolean).join(" · "); }
function formatGrade(item: Record<string, unknown>) { return `${String(item.letter ?? "")}${item.minimumPercent !== undefined ? ` · ≥ ${item.minimumPercent}%` : ""}${item.maximumPercent !== undefined ? `–${item.maximumPercent}%` : ""}`; }
function formatBook(item: Record<string, unknown>) { return [typeof item.requirementLevel === "string" ? item.requirementLevel : "", typeof item.title === "string" ? item.title : "", typeof item.author === "string" ? item.author : "", typeof item.edition === "string" ? item.edition : "", typeof item.isbn === "string" ? `ISBN ${item.isbn}` : ""].filter(Boolean).join(" · "); }
function PlanPanel({ title, items }: { title: string; items: string[] }) { const visible = items.filter(Boolean).slice(0, 12); return <section className={panel}><p className="text-[10px] uppercase tracking-[0.2em] text-sky-200/55">{title}</p>{visible.length ? <ul className="mt-3 space-y-1 text-sm text-white/65">{visible.map((item) => <li key={item}>• {item}</li>)}</ul> : <p className="mt-3 text-sm text-white/35">Not specified</p>}</section>; }
function PlanList({ title, items }: { title: string; items: string[] }) { const visible = items.filter(Boolean).slice(0, 18); if (!visible.length) return null; return <div><p className="text-[10px] uppercase tracking-[0.2em] text-sky-200/55">{title}</p><div className="mt-2 divide-y divide-white/[0.07]">{visible.map((item) => <p key={item} className="py-2 text-sm text-white/65">{item}</p>)}</div></div>; }
function Stat({ label, value }: { label: string; value: number | string }) { return <div className={panel}><p className="text-[10px] uppercase tracking-[0.18em] text-white/40">{label}</p><p className="mt-2 text-2xl font-black text-white">{value}</p></div>; }
