"use client";

import Link from "next/link";
import { ArrowLeft, BookOpen, CalendarDays, CheckCircle2, Clock3, ExternalLink, FileText, FolderOpen, MapPin } from "lucide-react";
import { use, useState } from "react";
import { useSchool } from "@/components/school/context/SchoolDataContext";
import { AssignmentForm } from "@/components/school/SchoolCrudViews";
import type { SchoolPlanningAssignment } from "@/core/contracts/SchoolPlanning";
import type { CoursePlan } from "@/services/school/coursePlan";
import { buildSchoolCourseCatalog } from "@/services/school/courseIdentity";
import { assignmentBelongsToCourse, providerCourseLabel, timelineEntryBelongsToCourse } from "@/services/school/courseExperience";
import { dedupeSchoolAssignments } from "@/services/school/assignmentIdentity";
import { getOverdueAssignments, getUpcomingAssignments, localAssignmentToPlanning, projectCourseMeetings } from "@/services/school/semesterConsumers";
import { getLocalStudySetStats, getLocalStudySetsForCourse, studyCourseHref } from "@/services/school/localStudy";

const panel = "rounded-[1.35rem] border border-white/[0.09] bg-[#101c35]/75 p-5";
const days = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const clock = (date: Date) => date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });

export default function CourseDetailPage({ params }: { params: Promise<{ courseId: string }> }) {
  const { courseId } = use(params);
  const { local, snapshot, loading } = useSchool();
  const [editing, setEditing] = useState(false);
  const decodedId = decodeURIComponent(courseId);
  const term = local.data.terms.find((item) => item.active) ?? local.data.terms[0];
  const localCourses = local.data.courses.filter((course) => !term || course.termId === term.id);
  const catalog = buildSchoolCourseCatalog(localCourses, local.data.terms, snapshot?.canvasCourses ?? []);
  const identity = catalog.find((item) => item.id === decodedId);
  const course = identity?.localCourseId ? localCourses.find((item) => item.id === identity.localCourseId) : undefined;

  const courseMap = new Map(localCourses.map((item) => [item.id, item]));
  const planning = dedupeSchoolAssignments([
    ...(snapshot?.planningAssignments ?? []),
    ...local.data.assignments.map((item) => localAssignmentToPlanning(item, item.courseId ? courseMap.get(item.courseId) : undefined)),
  ]);
  const assignments = identity ? planning.filter((item) => assignmentBelongsToCourse(item, identity, course)) : [];
  const events = identity ? (snapshot?.events ?? []).filter((event) => timelineEntryBelongsToCourse({ courseName: event.course, sourceId: event.courseId }, identity)) : [];

  if (loading) return <p className="py-16 text-sm text-white/50">Loading course…</p>;
  if (!identity) return <div className={panel}><p className="text-white/60">Course not found in the current School catalog.</p><p className="mt-2 text-sm text-white/40">It may be unavailable or require a fresh provider sync.</p><Link href="/school/courses" className="mt-4 inline-block text-sky-100/80">← Back to courses</Link></div>;

  const upcoming = getUpcomingAssignments(assignments).slice(0, 5);
  const overdue = getOverdueAssignments(assignments).slice(0, 3);
  const otherAssignments = assignments.filter((item) => !upcoming.some((candidate) => candidate.id === item.id) && !overdue.some((candidate) => candidate.id === item.id)).slice(0, 5);
  const provider = identity.canvasCourse;
  const meetings = course ? projectCourseMeetings([course], term, new Date(), 7) : [];
  const nextMeeting = meetings.find((item) => item.start >= new Date());
  const plan = course ? snapshot?.coursePlans?.find((item) => item.courseId === course.id) : undefined;
  const notes = snapshot?.notes.filter((note) => course && note.courseId === course.id) ?? [];
  const resources = course ? local.data.resources.filter((item) => item.courseId === course.id) : [];
  const studySets = course ? getLocalStudySetsForCourse(local.data.studySets ?? [], course.id) : [];
  const studyCards = local.data.flashcards ?? [];
  const isProviderOnly = !course;

  return <div className="space-y-5">
    <Link href="/school/courses" className="inline-flex items-center gap-2 text-sm text-white/45 hover:text-white"><ArrowLeft className="size-4" /> Courses</Link>
    <header className={panel}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex items-start gap-4"><span className="grid size-11 place-items-center rounded-2xl bg-sky-300/10 text-sky-100"><BookOpen className="size-5" /></span><div><p className="text-xs uppercase tracking-[0.2em] text-sky-200/55">{identity.code ?? "Course"}</p><h1 className="mt-1 text-3xl font-black tracking-[-0.04em] text-white">{identity.name}</h1><p className="mt-2 text-sm text-white/45">{providerCourseLabel(identity, provider)}{identity.section ? ` · Section ${identity.section}` : ""}{term && course ? ` · ${term.name}` : ""}</p></div></div><div className="flex flex-wrap gap-2">{provider?.url && <a href={provider.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-sky-200/20 bg-sky-200/10 px-3 py-2 text-sm text-sky-50"><ExternalLink className="size-4" /> Open Canvas</a>}{course && <><Link href={`/school/notes/new?courseId=${encodeURIComponent(course.id)}`} className="rounded-xl bg-sky-200/15 px-3 py-2 text-sm font-semibold text-sky-50">Add Note</Link><button type="button" onClick={() => setEditing(true)} className="rounded-xl border border-white/10 px-3 py-2 text-sm text-white/70">Add Assignment</button></>}</div></div>{course && <div className="mt-5 flex flex-wrap gap-3">{course.meetingTimes.map((meeting, index) => <span key={index} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-3 py-2 text-xs text-white/55"><Clock3 className="size-3.5" /> {days[meeting.weekday]} {meeting.startTime}–{meeting.endTime}{(meeting.location ?? course.location) && <><MapPin className="ml-1 size-3.5" />{meeting.location ?? course.location}</>}</span>)}</div>}</header>
    <section className="grid gap-3 sm:grid-cols-3"><Stat label="Next meeting" value={nextMeeting ? `${days[nextMeeting.start.getDay()]} · ${clock(nextMeeting.start)}` : isProviderOnly ? "Not available" : "None this week"} /><Stat label="Upcoming work" value={upcoming.length} /><Stat label="Source" value={isProviderOnly ? "Canvas" : provider ? "Mixed" : "Manual"} /></section>
    <section className="grid gap-4 lg:grid-cols-2"><section className={panel}><SectionTitle icon={<CheckCircle2 className="size-4" />} title="Assignments" href="/school/assignments" />{overdue.map((item) => <AssignmentRow key={`overdue-${item.id}`} item={item} label="Overdue" />)}{upcoming.map((item) => <AssignmentRow key={item.id} item={item} label={item.dueAt && item.dueAt.toDateString() === new Date().toDateString() ? "Due today" : "Upcoming"} />)}{otherAssignments.map((item) => <AssignmentRow key={`other-${item.id}`} item={item} label={item.completionStatus === "completed" || item.completionStatus === "submitted" || item.completionStatus === "graded" ? "Completed" : "Available"} />)}{!assignments.length && <Empty>{isProviderOnly ? "No provider assignments are available for this course." : "No assignments for this course yet."}</Empty>}{assignments.length > overdue.length + upcoming.length + otherAssignments.length && <p className="mt-3 text-xs text-white/35">Additional assignment history is available in Assignments.</p>}</section><section className={panel}><SectionTitle icon={<CalendarDays className="size-4" />} title="Calendar" href={`/school/calendar?course=${encodeURIComponent(identity.id)}`} />{events.slice(0, 6).map((event) => <Link key={`${event.source}:${event.id}`} href={`/school/calendar?course=${encodeURIComponent(identity.id)}`} className="mt-3 block rounded-xl border border-white/[0.07] p-3"><p className="text-sm text-white/75">{event.title}</p><p className="mt-1 text-xs text-white/40">{event.start.toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}{event.location ? ` · ${event.location}` : ""}</p></Link>)}{!events.length && <Empty>{isProviderOnly ? "No provider calendar events are available for this course." : "No calendar events for this course yet."}</Empty>}</section></section>
    <section className="grid gap-4 lg:grid-cols-3"><CourseSection icon={<FileText className="size-4" />} title="Notes" href={course ? `/school/notes?course=${encodeURIComponent(course.id)}` : undefined}>{notes.slice(0, 5).map((note) => <Link key={note.id} href={`/school/notes/${note.id}`} className="mt-3 block rounded-xl border border-white/[0.07] p-3 text-sm text-white/75">{note.title}</Link>)}{!notes.length && <Empty>{isProviderOnly ? "Add a local course to associate notes." : "No notes for this course yet."}</Empty>}</CourseSection><CourseSection icon={<BookOpen className="size-4" />} title="Study" href={course ? studyCourseHref(course.id) : undefined}>{isProviderOnly ? <Empty>Study sets are available for local courses. Add this course locally to create course-linked study material.</Empty> : <>{studySets.slice(0, 3).map((set) => { const stats = getLocalStudySetStats(set.id, studyCards); return <Link key={set.id} href={`/school/study/sets/${encodeURIComponent(set.id)}`} className="mt-3 block rounded-xl border border-white/[0.07] p-3 hover:border-sky-200/20"><p className="text-sm text-white/80">{set.title}</p><p className="mt-1 text-xs text-white/40">{stats.total} cards · {stats.new} new · {stats.due} due</p></Link>; })}{!studySets.length && <Empty>No study sets for this course yet.</Empty>}<Link href={studyCourseHref(course.id)} className="mt-3 inline-block text-sm text-sky-100/75">{studySets.length ? "Open course Study →" : "Create a study set →"}</Link></>}</CourseSection><CourseSection icon={<FolderOpen className="size-4" />} title="Resources" href={course ? `/school/resources?course=${encodeURIComponent(course.id)}` : undefined}>{resources.slice(0, 5).map((resource) => resource.url ? <a key={resource.id} href={resource.url} target="_blank" rel="noopener noreferrer" className="mt-3 block rounded-xl border border-white/[0.07] p-3 text-sm text-white/75">{resource.title}</a> : <p key={resource.id} className="mt-3 rounded-xl border border-white/[0.07] p-3 text-sm text-white/75">{resource.title}</p>)}{!resources.length && <Empty>{isProviderOnly ? "Add a local course to associate resources." : "No resources for this course yet."}</Empty>}</CourseSection></section>
    {plan && <CoursePlanView plan={plan} />}
    {editing && course && <AssignmentForm assignment={null} courses={[course]} onClose={() => setEditing(false)} onSave={(assignment) => { local.saveAssignment(assignment); setEditing(false); }} />}
  </div>;
}

function SectionTitle({ icon, title, href }: { icon: React.ReactNode; title: string; href?: string }) { return <div className="flex items-center justify-between"><p className="flex items-center gap-2 text-[10px] uppercase tracking-[0.2em] text-sky-200/55">{icon}{title}</p>{href && <Link href={href} className="text-xs text-sky-100/70">Open</Link>}</div>; }
function CourseSection({ icon, title, href, children }: { icon: React.ReactNode; title: string; href?: string; children: React.ReactNode }) { return <section className={panel}><SectionTitle icon={icon} title={title} href={href} />{children}</section>; }
function AssignmentRow({ item, label }: { item: SchoolPlanningAssignment; label: string }) { return <Link href={`/school/assignments/${encodeURIComponent(item.id)}`} className="mt-3 block rounded-xl border border-white/[0.07] p-3"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm text-white/75">{item.title}</p><span className="shrink-0 text-xs text-white/40">{label}</span></div><p className="mt-1 text-xs text-white/40">{item.dueAt ? item.dueAt.toLocaleDateString("en-US", { month: "short", day: "numeric" }) : "No due date"}{item.sourceType !== "manual" ? ` · ${item.sourceType === "canvas-api" ? "Canvas" : "Provider"}` : " · Manual"}</p></Link>; }
function Empty({ children }: { children: string }) { return <p className="mt-3 text-sm text-white/40">{children}</p>; }
function Stat({ label, value }: { label: string; value: string | number }) { return <div className={panel}><p className="text-[10px] uppercase tracking-[0.18em] text-white/40">{label}</p><p className="mt-2 text-xl font-bold text-white">{value}</p></div>; }

function CoursePlanView({ plan }: { plan: CoursePlan }) { const meetings = plan.meetingSchedule.map(formatMeeting); const office = plan.officeHours.map(formatOffice); const grades = plan.gradeScale.map(formatGrade); const books = plan.textbooks.map(formatBook); return <section className="space-y-3"><div className="grid gap-3 md:grid-cols-2"><PlanPanel title="Course information" items={meetings} /><PlanPanel title="Office hours" items={office} /><PlanPanel title="Grading scale" items={grades} /><PlanPanel title="Materials & textbooks" items={[...books, ...plan.materials]} /></div><div className={panel}><p className="text-[10px] uppercase tracking-[0.2em] text-sky-200/55">Policies & important dates</p><div className="mt-3 grid gap-2 text-sm text-white/65">{[...plan.policies.map((item) => `${item.subject}: ${item.value}`), ...plan.exams.map((item) => `${item.title}${item.date ? ` · ${new Date(item.date).toLocaleDateString()}` : ""}`), ...plan.majorAssignments.map((item) => `${item.title}${item.dueAt ? ` · ${new Date(item.dueAt).toLocaleDateString()}` : ""}`)].filter(Boolean).slice(0, 18).map((item) => <p key={item}>{item}</p>)}</div><p className="mt-4 text-xs text-white/35">Approved course data · {plan.sourceIds.length} source{plan.sourceIds.length === 1 ? "" : "s"}</p></div></section>; }
function formatMeeting(item: Record<string, unknown>) { return [Array.isArray(item.daysOfWeek) ? item.daysOfWeek.join(" / ") : "", item.startTime && item.endTime ? `${item.startTime}–${item.endTime}` : "", typeof item.location === "string" ? item.location : ""].filter(Boolean).join(" · "); }
function formatOffice(item: Record<string, unknown>) { return [Array.isArray(item.daysOfWeek) ? item.daysOfWeek.join(" / ") : "", item.startTime && item.endTime ? `${item.startTime}–${item.endTime}` : "", typeof item.location === "string" ? item.location : "", typeof item.notes === "string" ? item.notes : ""].filter(Boolean).join(" · "); }
function formatGrade(item: Record<string, unknown>) { return `${String(item.letter ?? "")}${item.minimumPercent !== undefined ? ` · ≥ ${item.minimumPercent}%` : ""}${item.maximumPercent !== undefined ? `–${item.maximumPercent}%` : ""}`; }
function formatBook(item: Record<string, unknown>) { return [typeof item.requirementLevel === "string" ? item.requirementLevel : "", typeof item.title === "string" ? item.title : "", typeof item.author === "string" ? item.author : "", typeof item.edition === "string" ? item.edition : ""].filter(Boolean).join(" · "); }
function PlanPanel({ title, items }: { title: string; items: string[] }) { const visible = items.filter(Boolean).slice(0, 12); return <section className={`${panel} p-5`}><p className="text-[10px] uppercase tracking-[0.2em] text-sky-200/55">{title}</p>{visible.length ? <ul className="mt-3 space-y-1 text-sm text-white/65">{visible.map((item) => <li key={item}>• {item}</li>)}</ul> : <p className="mt-3 text-sm text-white/35">Not specified</p>}</section>; }
