"use client";

import { useEffect, useState } from "react";
import { useCosmicAccount } from "@/components/account/AccountProvider";
import { useEntitlements } from "@/hooks/os/useEntitlements";

type BillingDiagnostics = { configured: boolean; configuration?: { configured: boolean; checkoutConfigured: boolean; webhookConfigured: boolean; testMode: boolean; environment: "test" | "live" | "unknown"; modeMismatch: boolean; liveModeBlocked: boolean; priceConfigured: boolean; missing: string[] }; customerExists: boolean; billingPlan: "free" | "cosmic_plus"; plan: "free" | "cosmic_plus"; subscription: { status: string; currentPeriodEnd: string | null; cancelAtPeriodEnd: boolean } | null; lastWebhookEvent: { id: string; type: string; processedAt: string } | null };

export default function BillingInspector() {
  const { account } = useCosmicAccount();
  const { data: entitlements } = useEntitlements();
  const [mounted, setMounted] = useState(false); const [data, setData] = useState<BillingDiagnostics>();
  useEffect(() => { const timer = window.setTimeout(() => setMounted(true), 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (!mounted) return; const timer = window.setTimeout(() => { void fetch("/api/billing/status", { cache: "no-store" }).then((response) => response.json()).then(setData).catch(() => setData(undefined)); }, 0); return () => window.clearTimeout(timer); }, [mounted, account?.id]);
  if (!mounted) return <main className="mx-auto max-w-3xl p-6 text-white"><h1 className="text-3xl font-semibold">Billing Inspector</h1><p className="mt-2 text-sm text-white/50">Reading billing state…</p></main>;
  const subscription = data?.subscription;
  return <main className="mx-auto max-w-3xl space-y-6 p-6 text-white"><div><p className="text-xs uppercase tracking-[0.2em] text-fuchsia-100/60">Developer tools</p><h1 className="mt-2 text-3xl font-semibold">Billing Inspector</h1><p className="mt-2 text-sm text-white/50">Safe billing diagnostics. Secrets and payment details are never returned.</p></div><section className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-white/40">Account</dt><dd className="mt-1 break-all">{account?.id ?? "Guest"}</dd></div><div><dt className="text-white/40">Billing configured</dt><dd className="mt-1">{data?.configured ? "yes" : "no"} · {data?.configuration?.environment ?? "unknown"}</dd></div><div><dt className="text-white/40">Checkout / webhook</dt><dd className="mt-1">{data?.configuration?.checkoutConfigured ? "ready" : "off"} / {data?.configuration?.webhookConfigured ? "ready" : "off"}</dd></div><div><dt className="text-white/40">Mode safeguards</dt><dd className="mt-1">{data?.configuration?.modeMismatch ? "mode mismatch" : data?.configuration?.liveModeBlocked ? "live blocked outside production" : "ok"}</dd></div><div><dt className="text-white/40">Billing plan</dt><dd className="mt-1">{data?.billingPlan ?? "free"}</dd></div><div><dt className="text-white/40">Effective plan</dt><dd className="mt-1">{entitlements.plan}</dd></div><div><dt className="text-white/40">Entitlement source</dt><dd className="mt-1">{entitlements.source}</dd></div><div><dt className="text-white/40">Stripe customer</dt><dd className="mt-1">{data?.customerExists ? "exists" : "none"}</dd></div><div><dt className="text-white/40">Subscription status</dt><dd className="mt-1">{subscription?.status ?? "none"}</dd></div><div><dt className="text-white/40">Current period end</dt><dd className="mt-1">{subscription?.currentPeriodEnd ? new Date(subscription.currentPeriodEnd).toLocaleString() : "—"}</dd></div><div><dt className="text-white/40">Cancel at period end</dt><dd className="mt-1">{subscription?.cancelAtPeriodEnd ? "yes" : "no"}</dd></div></dl>{data?.configuration?.missing.length ? <p className="mt-4 text-sm text-amber-200/75">Missing configuration: {data.configuration.missing.join(", ")}</p> : null}</section><section className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><h2 className="font-semibold">Last webhook</h2><p className="mt-2 break-all text-sm text-white/60">{data?.lastWebhookEvent ? `${data.lastWebhookEvent.type} · ${data.lastWebhookEvent.id} · ${new Date(data.lastWebhookEvent.processedAt).toLocaleString()}` : "No processed webhook recorded."}</p></section></main>;
}
