"use client";

import { useEffect, useState } from "react";

type Diagnostics = { configured: boolean; providerConfigured: boolean; providerEnvironment?: string; encryptionConfigured: boolean; webhookConfigured?: boolean; effectivePlan?: string; activeConnectionCount?: number; connectionLimit?: number | null; canAddConnection?: boolean; accountCount?: number; transactionCount?: number; moneyInCount?: number; moneyOutCount?: number; transferCount?: number; syncStateCount?: number; overrideCount?: number; transferPairCount?: number; savingsGoalCount?: number; goalContributionCount?: number; syncJobCount?: number; syncJobs?: Array<{ status: string; count: number; oldestCreatedAt?: string | null }>; providers?: Array<{ id: string; displayName: string; health: string; environment: string }>; error?: string };

export default function FinanceInspector() {
  const [data, setData] = useState<Diagnostics>();
  useEffect(() => { void fetch("/api/finance/diagnostics", { cache: "no-store" }).then((response) => response.json()).then(setData).catch(() => setData({ configured: false, providerConfigured: false, encryptionConfigured: false, error: "Unavailable" })); }, []);
  const values = data ? [["Effective plan", data.effectivePlan ?? "—"], ["Active institutions", `${data.activeConnectionCount ?? 0} / ${data.connectionLimit ?? "—"}`], ["Can add institution", data.canAddConnection ?? false], ["Database configured", data.configured], ["Plaid configured", data.providerConfigured], ["Token encryption configured", data.encryptionConfigured], ["Webhook configured", data.webhookConfigured ?? false], ["Provider environment", data.providerEnvironment ?? "—"], ["External account count", data.accountCount ?? 0], ["External transaction count", data.transactionCount ?? 0], ["Money-in count", data.moneyInCount ?? 0], ["Money-out count", data.moneyOutCount ?? 0], ["Transfer count", data.transferCount ?? 0], ["Sync state count", data.syncStateCount ?? 0], ["Category override count", data.overrideCount ?? 0], ["Detected transfer pair count", data.transferPairCount ?? 0], ["Savings goal count", data.savingsGoalCount ?? 0], ["Goal contribution count", data.goalContributionCount ?? 0], ["Sync job count", data.syncJobCount ?? 0]] : [];
  return <main className="mx-auto max-w-3xl p-6"><p className="text-xs uppercase tracking-[0.2em] text-cyan-100/50">Developer tools</p><h1 className="mt-2 text-3xl font-bold">Finance diagnostics</h1><p className="mt-2 text-sm text-white/45">Safe metadata only. Provider credentials, balances, transactions, and opaque IDs are never shown here.</p>{data ? <><div className="mt-6 grid gap-3 sm:grid-cols-2">{values.map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4"><p className="text-xs uppercase tracking-wider text-white/35">{String(label)}</p><p className="mt-2 text-lg text-white/80">{String(value)}</p></div>)}</div><div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.04] p-4"><h2 className="font-semibold">Sync engine</h2><div className="mt-3 space-y-2">{data.syncJobs?.map((job) => <p key={job.status} className="text-sm text-white/60">{job.status}: {job.count} · oldest {job.oldestCreatedAt ? new Date(job.oldestCreatedAt).toLocaleString() : "—"}</p>)}</div></div><div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.04] p-4"><h2 className="font-semibold">Provider registry</h2><div className="mt-3 space-y-2">{data.providers?.map((provider) => <p key={provider.id} className="text-sm text-white/60">{provider.displayName} · {provider.health} · {provider.environment}</p>)}</div></div></> : <p className="mt-6 text-sm text-white/45">Loading diagnostics…</p>}</main>;
}
