"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Data = { report: { publicReference: string; title: string; module: string; type: string; description: string; diagnostics: unknown; status: string }; email?: string | null };
const statuses = ["submitted", "reviewing", "needs_info", "fixing", "fixed", "closed"];
export default function AdminReportDetail({ reportId }: { reportId: string }) {
  const [data, setData] = useState<Data | null>(null); const [status, setStatus] = useState(""); const [note, setNote] = useState(""); const [userMessage, setUserMessage] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { fetch(`/api/admin/reports/${reportId}`, { cache: "no-store" }).then(async response => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData(payload.report); setStatus(payload.report.report.status); }).catch(error => setMessage(error instanceof Error ? error.message : "Report unavailable.")); }, [reportId]);
  async function save() { const response = await fetch(`/api/admin/reports/${reportId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, internalNote: note, userMessage }) }); const payload = await response.json(); if (!response.ok) return setMessage(payload.error); setNote(""); setData(payload.report); setMessage("Saved."); }
  if (!data) return <main className="p-6 text-sm text-white/55">{message || "Loading report…"}</main>;
  const report = data.report;
  return <main className="mx-auto max-w-4xl space-y-5 p-6 text-white"><Link href="/admin/reports" className="text-sm text-cyan-100/70">← All reports</Link><header><p className="text-xs uppercase tracking-widest text-cyan-100/50">{report.publicReference}</p><h1 className="mt-2 text-3xl font-semibold">{report.title}</h1><p className="mt-1 text-sm text-white/50">{data.email ?? "Deleted account"} · {report.module} · {report.type}</p></header><section className="space-y-4 rounded-2xl border border-white/10 bg-white/[0.04] p-5 text-sm"><p className="whitespace-pre-wrap text-white/80">{report.description}</p><details><summary className="cursor-pointer text-white/75">Safe diagnostics</summary><pre className="mt-2 overflow-auto whitespace-pre-wrap text-xs text-white/45">{JSON.stringify(report.diagnostics, null, 2)}</pre></details></section><section className="space-y-3 rounded-2xl border border-white/10 bg-white/[0.04] p-5"><label className="block text-sm text-white/70">Status<select className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-3 py-2 text-sm text-white" value={status} onChange={event => setStatus(event.target.value)}>{statuses.map(item => <option key={item}>{item}</option>)}</select></label><label className="block text-sm text-white/70">Internal note<textarea className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-3 py-2 text-sm text-white" rows={3} value={note} onChange={event => setNote(event.target.value)} /></label><label className="block text-sm text-white/70">User-visible Needs Info message<textarea className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-3 py-2 text-sm text-white" rows={3} value={userMessage} onChange={event => setUserMessage(event.target.value)} /></label><button onClick={() => void save()} className="rounded-xl border border-cyan-200/20 bg-cyan-200/10 px-4 py-3 text-sm text-cyan-50">Save status / note</button>{message ? <p className="text-sm text-white/55">{message}</p> : null}</section></main>;
}
