"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowUpRight, Check, ChevronRight, Clipboard, Download, LoaderCircle, RefreshCw, RotateCcw, ShieldCheck, Upload, X } from "lucide-react";

import { settingsSections, type SettingsSectionId } from "@/config/settings";
import type { BackupPreview, CosmicBackupDomain } from "@/core/contracts/Settings";
import { useClockData } from "@/components/apps/clock/ClockProvider";
import { useSearchRuntime } from "@/components/apps/search/SearchProvider";
import { useSystem } from "@/components/os/system/SystemProvider";
import type { DeviceProfileOverride, PerformanceMode } from "@/core/contracts/System";
import { readSchoolSnapshot } from "@/components/school/data/localRepository";
import { sportsPreferences } from "@/services/sports/preferences";
import { COSMIC_APP_VERSION, backupDomains, downloadCosmicBackup, getLocalDataCounts, importCosmicBackup, parseCosmicBackup, resetAllCosmicLocalData, resetCosmicDomain } from "@/services/settings/dataTransfer";
import { useSettingsData } from "./SettingsProvider";

interface ConnectionStatus { configured: boolean; connected: boolean; provider: string; detail: string; status: "connected" | "disconnected" | "reconnect-required" | "configured" | "unavailable" }
interface ConnectionPayload { calendar: ConnectionStatus; spotify: ConnectionStatus; gmail: ConnectionStatus }
type DialogState = { type: "reset"; domain: CosmicBackupDomain } | { type: "reset-all" } | { type: "disconnect-spotify" } | { type: "import"; preview: BackupPreview };

const domainLabels: Record<CosmicBackupDomain, string> = {
  settings: "Settings preferences", school: "School local data", garage: "Garage local data", projects: "Projects local data", notes: "Notes local data", clock: "Clock local data", search: "Recent Search history", finance: "Finance local data",
};
const idleOptions = [1, 2, 5, 10, 15, 30] as const;
const controlClass = "min-h-10 rounded-xl border border-white/12 bg-[#0a1021]/80 px-3 text-sm text-white outline-none transition focus:border-cyan-200/45 focus:ring-4 focus:ring-cyan-300/10";
const buttonClass = (tone: "default" | "danger" = "default") => tone === "danger"
  ? "inline-flex min-h-10 items-center justify-center gap-2 rounded-xl border border-rose-300/20 bg-rose-400/10 px-4 text-sm font-semibold text-rose-100 transition hover:bg-rose-400/16 focus:outline-none focus:ring-4 focus:ring-rose-300/10"
  : "inline-flex min-h-10 items-center justify-center gap-2 rounded-xl border border-white/12 bg-white/[0.06] px-4 text-sm font-semibold text-white/80 transition hover:border-white/20 hover:bg-white/[0.1] hover:text-white focus:outline-none focus:ring-4 focus:ring-cyan-300/10";

function SettingsRow({ title, description, children }: { title: string; description: string; children: React.ReactNode }) {
  return <div className="flex flex-col gap-4 border-b border-white/[0.07] py-5 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0 sm:max-w-xl"><h3 className="text-sm font-semibold text-white/88 sm:text-[15px]">{title}</h3><p className="mt-1 text-sm leading-6 text-white/42">{description}</p></div><div className="shrink-0">{children}</div></div>;
}

function Switch({ checked, onChange, label }: { checked: boolean; onChange(value: boolean): void; label: string }) {
  return <button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={() => onChange(!checked)} className={`relative h-7 w-12 rounded-full border transition focus:outline-none focus:ring-4 focus:ring-cyan-300/10 ${checked ? "border-cyan-200/30 bg-cyan-300/30" : "border-white/14 bg-white/[0.07]"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition-transform ${checked ? "translate-x-6" : "translate-x-1"}`} /><span className="sr-only">{checked ? "On" : "Off"}</span></button>;
}

function SectionIntro({ title, description }: { title: string; description: string }) {
  return <header className="border-b border-white/[0.08] pb-6"><h2 className="text-2xl font-bold tracking-tight text-white sm:text-3xl">{title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/46 sm:text-[15px]">{description}</p></header>;
}

function StatusPill({ status }: { status: string }) {
  const positive = ["Connected", "Configured", "Active", "Available"].includes(status);
  return <span className={`rounded-full border px-2.5 py-1 text-[11px] font-semibold ${positive ? "border-emerald-300/18 bg-emerald-300/10 text-emerald-100" : "border-amber-300/18 bg-amber-300/10 text-amber-100"}`}>{status}</span>;
}

function SettingsDialog({ state, busy, phrase, setPhrase, onClose, onConfirm }: { state: DialogState; busy: boolean; phrase: string; setPhrase(value: string): void; onClose(): void; onConfirm(): void }) {
  const cancelRef = useRef<HTMLButtonElement>(null);
  const dialogRef = useRef<HTMLElement>(null);
  const closeRef = useRef(onClose);
  useEffect(() => {
    closeRef.current = onClose;
  }, [onClose]);
  useEffect(() => {
    cancelRef.current?.focus();
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape" && !busy) closeRef.current();
      if (event.key !== "Tab" || !dialogRef.current) return;
      const controls = [...dialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), [href]')];
      const first = controls[0];
      const last = controls.at(-1);
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [busy]);
  const title = state.type === "reset-all" ? "Reset all local Cosmic data?" : state.type === "reset" ? `Reset ${domainLabels[state.domain]}?` : state.type === "disconnect-spotify" ? "Disconnect Spotify?" : "Replace included local data?";
  const confirmDisabled = busy || (state.type === "reset-all" && phrase !== "RESET COSMIC");
  return <div className="fixed inset-0 z-[140] grid place-items-center bg-black/75 p-4 backdrop-blur-md" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) onClose(); }}><section ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="settings-dialog-title" className="w-full max-w-lg rounded-[1.75rem] border border-white/14 bg-[#080d1d] p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-rose-200/60">Confirmation required</p><h2 id="settings-dialog-title" className="mt-2 text-xl font-bold text-white">{title}</h2></div><button type="button" onClick={onClose} disabled={busy} className="grid h-9 w-9 place-items-center rounded-full text-white/50 hover:bg-white/10 hover:text-white" aria-label="Close confirmation"><X className="h-4 w-4" /></button></div>
    {state.type === "import" ? <div className="mt-5 space-y-3"><p className="text-sm leading-6 text-white/52">Importing uses replace semantics for included domains. Other local domains stay unchanged.</p><ul className="max-h-56 space-y-2 overflow-y-auto rounded-2xl border border-white/9 bg-white/[0.035] p-3" aria-label="Import preview">{state.preview.domains.map((domain) => <li key={domain} className="flex items-center justify-between gap-4 text-sm"><span className="text-white/72">{domainLabels[domain]}</span><span className="text-white/38">{state.preview.counts[domain]} records</span></li>)}</ul><p className="text-xs text-white/35">Backup from {new Date(state.preview.backup.exportedAt).toLocaleString()} · Cosmic {state.preview.backup.appVersion}</p></div>
      : state.type === "disconnect-spotify" ? <p className="mt-5 text-sm leading-6 text-white/52">This removes Cosmic&apos;s server-stored Spotify authorization. It does not delete or modify your Spotify account.</p>
        : state.type === "reset-all" ? <div className="mt-5"><p className="text-sm leading-6 text-white/52">This clears Settings, School, Garage, Projects, Notes, Clock, and Search data stored in this browser. Server connections and external provider records are not touched.</p><label className="mt-4 block text-sm font-medium text-white/72" htmlFor="reset-phrase">Type <strong>RESET COSMIC</strong> to continue</label><input id="reset-phrase" value={phrase} onChange={(event) => setPhrase(event.target.value)} autoComplete="off" className={`mt-2 w-full ${controlClass}`} /></div>
          : <p className="mt-5 text-sm leading-6 text-white/52">This replaces only {domainLabels[state.domain].toLocaleLowerCase()} with its default empty state. Provider accounts and other local app data stay intact.</p>}
    <div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button ref={cancelRef} type="button" onClick={onClose} disabled={busy} className={buttonClass()}>Cancel</button><button type="button" onClick={onConfirm} disabled={confirmDisabled} className={`${buttonClass("danger")} disabled:cursor-not-allowed disabled:opacity-40`}>{busy ? <LoaderCircle className="h-4 w-4 animate-spin" /> : state.type === "import" ? <Upload className="h-4 w-4" /> : <RotateCcw className="h-4 w-4" />}{state.type === "import" ? "Replace data" : state.type === "disconnect-spotify" ? "Disconnect" : "Reset"}</button></div>
  </section></div>;
}

function useLocalInventory() {
  const [revision, setRevision] = useState(0);
  useEffect(() => {
    const sync = () => setRevision((value) => value + 1);
    const events = ["cosmic:settings-local-data-updated", "cosmic:school-local-data-updated", "cosmic:garage-local-data-updated", "cosmic:projects-updated", "cosmic:notes-updated", "cosmic:clock-local-data-updated", "cosmic:search-recents-updated"];
    window.addEventListener("storage", sync); events.forEach((event) => window.addEventListener(event, sync));
    return () => { window.removeEventListener("storage", sync); events.forEach((event) => window.removeEventListener(event, sync)); };
  }, []);
  return useMemo(() => ({ counts: getLocalDataCounts(), school: readSchoolSnapshot(), revision }), [revision]);
}

export default function SettingsView({ compact = false }: { compact?: boolean }) {
  const settings = useSettingsData(); const clock = useClockData(); const search = useSearchRuntime();
  const system = useSystem(); const reducedMotion = system.snapshot.power.reducedMotion; const inventory = useLocalInventory();
  const weatherStatus = system.snapshot.permissions.geolocation === "granted" ? "Browser location allowed" : system.snapshot.permissions.geolocation === "denied" ? "Permission denied; fallback location is used" : system.snapshot.permissions.geolocation === "prompt" ? "Browser will ask when Weather needs location" : system.snapshot.capabilities.geolocation ? "Browser location available; permission unknown" : "Unavailable in this browser";
  const fileRef = useRef<HTMLInputElement>(null);
  const [activeSection, setActiveSection] = useState<SettingsSectionId>("general");
  const [connections, setConnections] = useState<ConnectionPayload | null>(null);
  const [connectionError, setConnectionError] = useState(false); const [connectionLoading, setConnectionLoading] = useState(true);
  const [dialog, setDialog] = useState<DialogState | null>(null); const [phrase, setPhrase] = useState(""); const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState<string | null>(null); const [importError, setImportError] = useState<string | null>(null);

  useEffect(() => { const syncHash = () => { const id = window.location.hash.slice(1) as SettingsSectionId; if (settingsSections.some((section) => section.id === id)) setActiveSection(id); }; syncHash(); window.addEventListener("hashchange", syncHash); return () => window.removeEventListener("hashchange", syncHash); }, []);
  const selectSection = (id: SettingsSectionId) => { setActiveSection(id); window.history.replaceState(null, "", `${window.location.pathname}${window.location.search}#${id}`); };
  const loadConnections = async () => { setConnectionLoading(true); setConnectionError(false); try { const response = await fetch("/api/settings/connections", { cache: "no-store" }); if (!response.ok) throw new Error(); setConnections(await response.json() as ConnectionPayload); } catch { setConnectionError(true); } finally { setConnectionLoading(false); } };
  useEffect(() => { void loadConnections(); }, []);

  const readImport = async (file?: File) => { if (!file) return; setImportError(null); try { setDialog({ type: "import", preview: parseCosmicBackup(await file.text()) }); } catch (error) { setImportError(error instanceof Error ? error.message : "Cosmic could not read this backup."); } finally { if (fileRef.current) fileRef.current.value = ""; } };
  const closeDialog = () => { if (!busy) { setDialog(null); setPhrase(""); } };
  const confirmDialog = async () => {
    if (!dialog) return; setBusy(true);
    try {
      if (dialog.type === "reset") { resetCosmicDomain(dialog.domain); setNotice(`${domainLabels[dialog.domain]} reset.`); }
      else if (dialog.type === "reset-all") { resetAllCosmicLocalData(); setNotice("All browser-local Cosmic data reset. Connections were left intact."); }
      else if (dialog.type === "import") { importCosmicBackup(dialog.preview); setNotice("Included local Cosmic data replaced successfully."); }
      else { const response = await fetch("/api/settings/connections", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider: "spotify" }) }); if (!response.ok) throw new Error("Spotify could not be disconnected."); setNotice("Spotify disconnected from Cosmic."); await loadConnections(); }
      setDialog(null); setPhrase("");
    } catch (error) { setNotice(error instanceof Error ? error.message : "That action could not be completed."); } finally { setBusy(false); }
  };

  const current = settingsSections.find((section) => section.id === activeSection) ?? settingsSections[0];
  const activeTerm = inventory.school.terms.find((term) => term.active);
  const localStorageAvailable = (() => { try { void window.localStorage.length; return true; } catch { return false; } })();
  const rendererCount = !settings.ready || typeof document === "undefined" ? 0 : document.querySelectorAll("[data-cosmic-global-background] canvas").length;
  const copyDiagnostics = async () => {
    const text = [`Cosmic OS ${COSMIC_APP_VERSION}`, `Route: ${window.location.pathname}${window.location.hash}`, `Renderer: ${rendererCount} celestial canvas`, `Search providers: ${search.engine.getProviders().length}`, `Local storage: ${localStorageAvailable ? "available" : "unavailable"}`, `Timezone: ${Intl.DateTimeFormat().resolvedOptions().timeZone}`, `System reduced motion: ${reducedMotion ? "enabled" : "disabled"}`, `Calendar: ${connections?.calendar.connected ? "connected" : connections?.calendar.configured ? "configured" : "unavailable"}`, `Spotify: ${connections?.spotify.connected ? "connected" : "disconnected"}`, `Gmail: ${connections?.gmail.connected ? "connected" : "disconnected"}`].join("\n");
    try { await navigator.clipboard.writeText(text); setNotice("Privacy-safe diagnostics copied."); } catch { setNotice("Clipboard access is unavailable."); }
  };

  const sectionContent = (() => {
    switch (activeSection) {
      case "general": return <><SectionIntro title="General" description="A concise overview of Cosmic’s real global preferences. Changes save immediately." /><SettingsRow title="Time format" description="This shortcut edits the canonical Clock preference used across Cosmic."><select aria-label="Time format" value={clock.data.preferences.hourFormat} onChange={(event) => clock.setHourFormat(event.target.value as "system" | "12" | "24")} className={controlClass}><option value="system">System</option><option value="12">12-hour</option><option value="24">24-hour</option></select></SettingsRow><SettingsRow title="Automatic Ambient" description={`Currently ${settings.data.ambient.enabled && settings.data.ambient.idleMinutes ? `after ${settings.data.ambient.idleMinutes} minutes` : "disabled"}. Manual Ambient always remains available.`}><Link href="/os/ambient" className={buttonClass()}>Open Ambient <ArrowUpRight className="h-4 w-4" /></Link></SettingsRow></>;
      case "appearance": return <><SectionIntro title="Appearance" description="Cosmic stays intentionally dark and celestial. This preference reduces decorative interface effects without inventing a second theme." /><SettingsRow title="Reduce interface effects" description="Shortens transitions and disables decorative animation. The celestial canvas also uses effective motion Off."><Switch checked={settings.data.appearance.reducedEffects} onChange={settings.setReducedEffects} label="Reduce interface effects" /></SettingsRow><SettingsRow title="System reduced motion" description="The browser preference always wins inside the renderer, even if Cosmic motion is set to Normal."><StatusPill status={reducedMotion ? "Enabled" : "Not requested"} /></SettingsRow></>;
      case "background": return <><SectionIntro title="Celestial Background" description="Tune the single global renderer behind Settings and every Cosmic app. The preview is the live background already on this page." /><SettingsRow title="Background intensity" description="Adjusts star, cloud, and nebula presence without changing celestial phase or time mapping."><select aria-label="Background intensity" value={settings.data.background.intensity} onChange={(event) => settings.setBackgroundIntensity(event.target.value as "low" | "normal" | "high")} className={controlClass}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></SettingsRow><SettingsRow title="Motion" description="Updates the active renderer immediately. System reduced motion and Reduce interface effects can lower the effective motion."><select aria-label="Background motion" value={settings.data.background.motion} onChange={(event) => settings.setBackgroundMotion(event.target.value as "off" | "subtle" | "normal")} className={controlClass}><option value="off">Off</option><option value="subtle">Subtle</option><option value="normal">Normal</option></select></SettingsRow><div className="mt-6 overflow-hidden rounded-[1.5rem] border border-white/12 bg-[radial-gradient(circle_at_72%_28%,rgba(111,206,255,.18),transparent_32%),radial-gradient(circle_at_22%_80%,rgba(177,112,255,.14),transparent_38%),rgba(4,8,22,.58)] p-6"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-cyan-100/50">Live global preview</p><p className="mt-8 max-w-sm text-sm leading-6 text-white/58">{settings.data.background.intensity} intensity · {settings.data.appearance.reducedEffects ? "off (reduced effects)" : settings.data.background.motion} motion · one celestial canvas</p></div></>;
      case "system": return <><SectionIntro title="System" description="Control real Cosmic adaptation without changing or misrepresenting the underlying hardware." /><SettingsRow title="Performance Mode" description={`Effective profile: ${system.snapshot.power.effective}. Automatic uses reduced motion, Reduce Effects, Data Saver, and conservative hardware hints.`}><select aria-label="Performance Mode" value={settings.data.system.performanceMode} onChange={(event) => settings.setPerformanceMode(event.target.value as PerformanceMode)} className={controlClass}><option value="automatic">Automatic</option><option value="full">Full</option><option value="balanced">Balanced</option><option value="reduced">Reduced</option></select></SettingsRow><SettingsRow title="Device Profile" description="A layout/testing override. It does not change or conceal reported browser metrics."><select aria-label="Device Profile" value={settings.data.system.deviceProfileOverride} onChange={(event) => settings.setDeviceProfileOverride(event.target.value as DeviceProfileOverride)} className={controlClass}><option value="automatic">Automatic</option><option value="desktop">Desktop</option><option value="tablet">Tablet</option><option value="phone">Phone</option><option value="display">Display / Kiosk</option></select></SettingsRow><SettingsRow title="Install status" description={system.snapshot.install.mode === "standalone" ? "Cosmic is running in standalone display mode." : system.snapshot.install.installable ? "This browser currently offers a real Cosmic install prompt." : "No install prompt is currently available."}><Link href="/system#install" className={buttonClass()}>Review Install <ArrowUpRight className="h-4 w-4" /></Link></SettingsRow><SettingsRow title="Notifications" description={`Browser permission: ${system.snapshot.permissions.notifications}. Cosmic never requests permission automatically.`}><Link href="/system#permissions" className={buttonClass()}>Review Permissions <ArrowUpRight className="h-4 w-4" /></Link></SettingsRow><SettingsRow title="System diagnostics" description="Review the full privacy-safe device, display, network, storage, and capability snapshot."><Link href="/system" className={buttonClass()}>Open System <ArrowUpRight className="h-4 w-4" /></Link></SettingsRow></>;
      case "dashboard": return <><SectionIntro title="Dashboard" description="The current dashboard widget registry and grid are packaged configuration, not browser-persisted user layout." /><SettingsRow title="Widget layout" description="Static canonical layout. There is no user layout record to reset, so Settings does not show a destructive control that would do nothing."><StatusPill status="Configured" /></SettingsRow><SettingsRow title="Dashboard" description="Open the canonical Cosmic dashboard and its current widgets."><Link href="/os" className={buttonClass()}>Open Dashboard <ArrowUpRight className="h-4 w-4" /></Link></SettingsRow></>;
      case "ambient": return <><SectionIntro title="Ambient" description="Control the existing dashboard-idle transition. Manual access remains available regardless of this preference." /><SettingsRow title="Automatically enter Ambient Mode" description="When off, idle activity on the dashboard will never navigate automatically."><Switch checked={settings.data.ambient.enabled && settings.data.ambient.idleMinutes !== null} onChange={settings.setAmbientEnabled} label="Automatically enter Ambient Mode" /></SettingsRow><SettingsRow title="Idle delay" description="The active dashboard timer updates immediately when this value changes."><select aria-label="Ambient idle delay" value={settings.data.ambient.enabled ? settings.data.ambient.idleMinutes ?? "never" : "never"} onChange={(event) => settings.setAmbientIdleMinutes(event.target.value === "never" ? null : Number(event.target.value) as 1 | 2 | 5 | 10 | 15 | 30)} className={controlClass}>{idleOptions.map((minutes) => <option key={minutes} value={minutes}>{minutes} minute{minutes === 1 ? "" : "s"}</option>)}<option value="never">Never</option></select></SettingsRow><SettingsRow title="Manual Ambient" description="Available even when automatic Ambient is Never."><Link href="/os/ambient" className={buttonClass()}>Open Ambient <ArrowUpRight className="h-4 w-4" /></Link></SettingsRow></>;
      case "clock": return <><SectionIntro title="Clock" description="Format uses the existing Clock repository; alarms, timers, and world-clock management remain in the Clock app." /><SettingsRow title="Time format" description="Immediately updates Clock consumers in this tab and other tabs."><select aria-label="Clock time format" value={clock.data.preferences.hourFormat} onChange={(event) => clock.setHourFormat(event.target.value as "system" | "12" | "24")} className={controlClass}><option value="system">System</option><option value="12">12-hour</option><option value="24">24-hour</option></select></SettingsRow><div className="grid gap-3 py-5 sm:grid-cols-3">{[{ label: "World clocks", value: clock.data.worldClocks.length }, { label: "Alarms", value: clock.data.alarms.length }, { label: "Timers", value: clock.data.timers.length }].map((item) => <div key={item.label} className="rounded-2xl border border-white/9 bg-white/[0.035] p-4"><p className="text-2xl font-bold">{item.value}</p><p className="mt-1 text-xs text-white/40">{item.label}</p></div>)}</div><Link href="/clock" className={buttonClass()}>Open Clock <ArrowUpRight className="h-4 w-4" /></Link></>;
      case "connections": return <><SectionIntro title="Connections" description="Safe status only. OAuth credentials, provider tokens, calendar passwords, and private URLs stay on the server." /><div className="mt-6 flex justify-end"><button type="button" onClick={() => void loadConnections()} disabled={connectionLoading} className={buttonClass()}><RefreshCw className={`h-4 w-4 ${connectionLoading ? "animate-spin" : ""}`} />Refresh status</button></div>{connectionError ? <div className="mt-4 rounded-2xl border border-amber-300/16 bg-amber-300/[0.07] p-4 text-sm text-amber-50/72">Connection status is temporarily unavailable. Local Settings remain fully usable.</div> : null}<div className="mt-4 grid gap-4 xl:grid-cols-2">{connections ? [connections.spotify, connections.calendar, connections.gmail].map((item) => { const key = item.provider.toLocaleLowerCase(); const status = item.status === "reconnect-required" ? "Reconnect required" : item.status.charAt(0).toUpperCase() + item.status.slice(1); return <article key={key} className="rounded-[1.4rem] border border-white/9 bg-white/[0.035] p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-white/88">{item.provider}</h3><p className="mt-1 text-sm leading-6 text-white/40">{item.detail}</p></div><StatusPill status={status} /></div><div className="mt-4 flex flex-wrap gap-2">{key === "spotify" && item.configured && !item.connected ? <a href="/api/auth/spotify" className={buttonClass()}>{item.status === "reconnect-required" ? "Reconnect Spotify" : "Connect Spotify"}</a> : null}{key === "spotify" && item.connected ? <button type="button" onClick={() => setDialog({ type: "disconnect-spotify" })} className={buttonClass("danger")}>Disconnect</button> : null}{key === "gmail" && item.configured && !item.connected ? <a href="/api/auth/google" className={buttonClass()}>{item.status === "reconnect-required" ? "Reconnect Gmail" : "Connect Gmail"}</a> : null}{key.includes("calendar") || key === "subscriptions" ? <Link href="/calendar" className={buttonClass()}>Open Calendar</Link> : null}</div></article>; }) : <div className="col-span-full rounded-2xl border border-white/9 bg-white/[0.03] p-5 text-sm text-white/38">Loading server-managed connection status…</div>}<article className="rounded-[1.4rem] border border-white/9 bg-white/[0.035] p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-white/88">Weather</h3><p className="mt-1 text-sm leading-6 text-white/40">{weatherStatus}</p></div><StatusPill status={weatherStatus.startsWith("Unavailable") ? "Unavailable" : "Available"} /></div><p className="mt-4 text-xs leading-5 text-white/32">Settings does not request location or bypass browser permission. Weather asks only when needed.</p></article></div></>;
      case "apps": { const cards = [{ name: "Calendar", href: "/calendar", summary: connections?.calendar.detail ?? "Status available under Connections" }, { name: "School", href: "/school/settings", summary: activeTerm ? `Active term · ${activeTerm.name}` : `${inventory.school.courses.length} courses · no active term` }, { name: "Sports", href: "/sports", summary: `${sportsPreferences.sportOrder.length} configured interests · read-only constants` }, { name: "Garage", href: "/garage", summary: `${inventory.counts.garage} local records` }, { name: "Projects", href: "/projects", summary: `${inventory.counts.projects} local records` }, { name: "Notes", href: "/notes", summary: `${inventory.counts.notes} local notes` }, { name: "Music", href: "/music", summary: connections?.spotify.connected ? "Spotify connected" : "Spotify status under Connections" }, { name: "Clock", href: "/clock", summary: `${clock.data.worldClocks.length} world clocks · ${clock.data.alarms.length} alarms` }]; return <><SectionIntro title="Apps" description="Concise status and safe shortcuts. Detailed configuration stays with each canonical app." /><div className="mt-6 grid gap-3 sm:grid-cols-2">{cards.map((card) => <Link key={card.name} href={card.href} className="group rounded-[1.35rem] border border-white/9 bg-white/[0.035] p-4 transition hover:border-cyan-200/20 hover:bg-white/[0.065]"><div className="flex items-center justify-between"><h3 className="font-semibold text-white/82">{card.name}</h3><ChevronRight className="h-4 w-4 text-white/28 transition group-hover:translate-x-0.5 group-hover:text-cyan-100/70" /></div><p className="mt-2 text-sm leading-5 text-white/38">{card.summary}</p></Link>)}</div><div className="mt-5 rounded-2xl border border-white/9 bg-white/[0.03] p-4 text-sm leading-6 text-white/42"><strong className="text-white/68">Sports preferences:</strong> the current provider uses non-persistent supported-interest constants, so Settings reports them but does not offer switches that would fail to persist.</div></>; }
      case "search": return <><SectionIntro title="Search" description="Cosmic Search searches local and configured Cosmic sources. It does not send queries to a web search engine." /><SettingsRow title="Recent searches" description={`${search.recentSearches.length} of 10 recent queries stored in this browser.`}><button type="button" disabled={!search.recentSearches.length} onClick={() => setDialog({ type: "reset", domain: "search" })} className={`${buttonClass("danger")} disabled:cursor-not-allowed disabled:opacity-40`}>Clear Recent Searches</button></SettingsRow><SettingsRow title="Settings destinations" description={`${settingsSections.length} Settings sections are indexed from the shared metadata registry with deep links.`}><button type="button" onClick={() => search.openSearch("background")} className={buttonClass()}>Search Settings</button></SettingsRow></>;
      case "privacy-data": return <><SectionIntro title="Privacy & Data" description="Export and replace only whitelisted browser-local Cosmic data. Server connections and provider records are separate." /><div className="mt-6 grid gap-3 sm:grid-cols-2"><button type="button" onClick={downloadCosmicBackup} className={`${buttonClass()} justify-start p-4 text-left`}><Download className="h-5 w-5 text-cyan-100/70" /><span><span className="block">Export Cosmic data</span><span className="mt-1 block text-xs font-normal text-white/36">Download a versioned JSON backup</span></span></button><button type="button" onClick={() => fileRef.current?.click()} className={`${buttonClass()} justify-start p-4 text-left`}><Upload className="h-5 w-5 text-cyan-100/70" /><span><span className="block">Import Cosmic data</span><span className="mt-1 block text-xs font-normal text-white/36">Validate and preview before replace</span></span></button><input ref={fileRef} type="file" accept="application/json,.json" className="sr-only" onChange={(event) => void readImport(event.target.files?.[0])} /></div>{importError ? <p role="alert" className="mt-3 rounded-xl border border-rose-300/16 bg-rose-300/[0.07] p-3 text-sm text-rose-100/80">{importError}</p> : null}<div className="mt-7"><h3 className="text-sm font-semibold text-white/72">Local data inventory</h3><div className="mt-3 overflow-hidden rounded-2xl border border-white/9">{backupDomains.map((domain) => <div key={domain} className="flex flex-col gap-3 border-b border-white/[0.07] bg-white/[0.025] p-4 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium text-white/72">{domainLabels[domain]}</p><p className="mt-1 text-xs text-white/34">{inventory.counts[domain]} safe local record{inventory.counts[domain] === 1 ? "" : "s"}</p></div><button type="button" onClick={() => setDialog({ type: "reset", domain })} className={buttonClass("danger")}>Reset</button></div>)}</div></div><div className="mt-7 rounded-[1.4rem] border border-rose-300/15 bg-rose-400/[0.055] p-5"><h3 className="font-semibold text-rose-50">Reset all local Cosmic data</h3><p className="mt-2 text-sm leading-6 text-rose-100/48">Clears all supported browser-local domains. It does not disconnect Spotify/Gmail, alter Apple Calendar, or delete external records.</p><button type="button" onClick={() => setDialog({ type: "reset-all" })} className={`mt-4 ${buttonClass("danger")}`}>Reset All Local Cosmic Data</button></div><div className="mt-5 flex gap-3 rounded-2xl border border-emerald-300/12 bg-emerald-300/[0.045] p-4"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-200/70" /><p className="text-sm leading-6 text-white/42"><strong className="text-white/70">Never exported:</strong> OAuth tokens, provider credentials, environment variables, mail content, Apple passwords, and server token files.</p></div></>;
      case "about": return <><SectionIntro title="About Cosmic" description="Build identity and restrained, privacy-safe runtime diagnostics." /><div className="mt-6 rounded-[1.6rem] border border-white/10 bg-white/[0.04] p-6"><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-cyan-100/48">Cosmic OS</p><h3 className="mt-2 text-3xl font-black tracking-tight">Version {COSMIC_APP_VERSION}</h3><p className="mt-2 text-sm text-white/38">{process.env.NODE_ENV === "production" ? "Production build" : "Development build"} · local-first app data with separate server/provider connections</p></div><div className="mt-6 overflow-hidden rounded-2xl border border-white/9">{[["Celestial renderer", `${rendererCount === 1 ? "Active" : "Check renderer"} · ${rendererCount} canvas`], ["Search providers", `${search.engine.getProviders().length} registered`], ["Local storage", localStorageAvailable ? "Available" : "Unavailable"], ["Browser timezone", Intl.DateTimeFormat().resolvedOptions().timeZone], ["System reduced motion", reducedMotion ? "Enabled" : "Disabled"], ["Calendar", connections?.calendar.connected ? "Connected" : connections?.calendar.configured ? "Configured" : "Unavailable"], ["Spotify", connections?.spotify.connected ? "Connected" : connections?.spotify.configured ? "Disconnected" : "Unavailable"], ["Gmail", connections?.gmail.connected ? "Connected" : connections?.gmail.configured ? "Disconnected" : "Unavailable"]].map(([label, value]) => <div key={label} className="flex items-center justify-between gap-5 border-b border-white/[0.07] bg-white/[0.025] px-4 py-3 last:border-0"><span className="text-sm text-white/46">{label}</span><span className="text-right text-sm font-medium text-white/72">{value}</span></div>)}</div><button type="button" onClick={() => void copyDiagnostics()} className={`mt-5 ${buttonClass()}`}><Clipboard className="h-4 w-4" />Copy Diagnostics</button></>;
    }
  })();

  if (compact) return <div className="space-y-4"><div><h1 className="text-2xl font-bold">Settings</h1><p className="mt-1 text-sm text-white/42">Canonical preferences and connection status.</p></div><div className="grid gap-2">{settingsSections.slice(0, 6).map((section) => <Link key={section.id} href={section.href} className="flex items-center justify-between rounded-xl border border-white/9 bg-white/[0.035] px-4 py-3 text-sm text-white/70 hover:bg-white/[0.07]"><span>{section.name}</span><ChevronRight className="h-4 w-4 text-white/30" /></Link>)}</div><Link href="/settings" className={buttonClass()}>Open Full Settings <ArrowUpRight className="h-4 w-4" /></Link></div>;

  return <div className="mx-auto max-w-[1440px]"><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-cyan-100/45">Cosmic control center</p><h1 className="mt-2 text-4xl font-black tracking-[-0.04em] sm:text-5xl">Settings</h1><p className="mt-2 text-sm text-white/42">Real preferences, honest status, local data under your control.</p></div><Link href="/os" className={buttonClass()}>Dashboard <ArrowUpRight className="h-4 w-4" /></Link></div>
    {notice ? <div role="status" className="mb-4 flex items-center justify-between gap-4 rounded-2xl border border-emerald-300/14 bg-emerald-300/[0.07] px-4 py-3 text-sm text-emerald-50/78"><span className="flex items-center gap-2"><Check className="h-4 w-4" />{notice}</span><button type="button" onClick={() => setNotice(null)} aria-label="Dismiss status"><X className="h-4 w-4" /></button></div> : null}
    <label className="mb-4 block lg:hidden"><span className="sr-only">Settings section</span><select value={activeSection} onChange={(event) => selectSection(event.target.value as SettingsSectionId)} className={`w-full ${controlClass}`}>{settingsSections.map((section) => <option key={section.id} value={section.id}>{section.name}</option>)}</select></label>
    <div className="grid min-h-[680px] overflow-hidden rounded-[2rem] border border-white/11 bg-[#071022]/68 shadow-[0_34px_100px_rgba(0,0,0,.28)] backdrop-blur-2xl lg:grid-cols-[270px_minmax(0,1fr)]"><nav className="hidden border-r border-white/[0.08] bg-black/10 p-4 lg:block" aria-label="Settings sections"><ul className="space-y-1">{settingsSections.map((section) => <li key={section.id}><button type="button" onClick={() => selectSection(section.id)} aria-current={activeSection === section.id ? "page" : undefined} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition focus:outline-none focus:ring-4 focus:ring-cyan-300/10 ${activeSection === section.id ? "bg-cyan-200/10 text-cyan-50" : "text-white/48 hover:bg-white/[0.055] hover:text-white/78"}`}><span className="w-5 text-center text-white/55" aria-hidden="true">{section.icon}</span><span>{section.name}</span></button></li>)}</ul></nav><section id={current.id} className="min-w-0 p-5 sm:p-8 lg:max-h-[calc(100svh-11rem)] lg:overflow-y-auto lg:p-10" aria-label={`${current.name} settings`}>{sectionContent}</section></div>
    {dialog ? <SettingsDialog state={dialog} busy={busy} phrase={phrase} setPhrase={setPhrase} onClose={closeDialog} onConfirm={() => void confirmDialog()} /> : null}
  </div>;
}
