"use client";

import { useMemo, useState } from "react";
import type { GarageCollection, VehicleStatus } from "@/core/contracts/Garage";
import { maintenanceStatus, useGarage } from "@/hooks/os/useGarage";

const input = "mt-1 w-full rounded-xl border border-white/15 bg-black/20 px-3 py-2 text-sm text-white";
const button = "rounded-xl bg-cyan-300/20 px-3 py-2 text-sm text-cyan-50 hover:bg-cyan-300/30 focus:outline-none focus:ring-2 focus:ring-cyan-200";

export default function GarageCollectionsPanel() {
  const garage = useGarage();
  const [name, setName] = useState("");
  const [selectedCollection, setSelectedCollection] = useState("all");
  const [deleteTarget, setDeleteTarget] = useState("my-garage");
  const collections = garage.data.collections.filter((item) => !item.archived);
  const vehicles = selectedCollection === "all" ? garage.data.vehicles : garage.data.vehicles.filter((item) => (item.collectionId ?? "my-garage") === selectedCollection);
  const summary = useMemo(() => { const attention = vehicles.filter((vehicle) => garage.data.maintenance.some((item) => item.vehicleId === vehicle.id && ["overdue", "dueSoon"].includes(maintenanceStatus(item, vehicle.currentMileage))) || garage.data.issues.some((item) => item.vehicleId === vehicle.id && item.status !== "resolved")); const expenses = garage.data.expenses.filter((item) => vehicles.some((vehicle) => vehicle.id === item.vehicleId)).reduce((sum, item) => sum + item.amount, 0); const fuel = garage.data.fuelRecords.filter((item) => vehicles.some((vehicle) => vehicle.id === item.vehicleId)).reduce((sum, item) => sum + (item.totalCostMinor ?? 0) / 100, 0); const statuses = new Map<VehicleStatus, number>(); for (const vehicle of vehicles) statuses.set(vehicle.status, (statuses.get(vehicle.status) ?? 0) + 1); return { attention: attention.length, expenses, fuel, statuses }; }, [garage.data, vehicles]);
  const create = () => { const value = name.trim(); if (!value) return; const now = new Date().toISOString(); garage.saveCollection({ id: crypto.randomUUID(), name: value, kind: "personal", sortOrder: collections.length, createdAt: now, updatedAt: now }); setName(""); };
  const rename = (collection: GarageCollection) => { const value = window.prompt("Collection name", collection.name)?.trim(); if (!value || value === collection.name) return; garage.saveCollection({ ...collection, name: value, updatedAt: new Date().toISOString() }); };
  const remove = (collection: GarageCollection) => { if (collection.id === "my-garage") return; const target = deleteTarget === collection.id ? "my-garage" : deleteTarget; if (!window.confirm(`Delete ${collection.name}? Vehicles will move to the selected destination.`)) return; garage.removeCollection(collection.id, target); };
  return <section className="rounded-3xl border border-white/15 bg-white/[0.07] p-5 backdrop-blur-xl"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-medium">Collections</h2><p className="mt-1 text-sm text-white/55">Organize personal, project, family, and work vehicles without orphaning records.</p></div><form className="flex w-full max-w-md gap-2 sm:w-auto" onSubmit={(event) => { event.preventDefault(); create(); }}><label className="sr-only" htmlFor="garage-collection-name">New collection name</label><input id="garage-collection-name" className={input.replace("mt-1 ", "")} value={name} onChange={(event) => setName(event.target.value)} placeholder="New collection" /><button className={button}>Create</button></form></div><div className="mt-4 grid gap-3 lg:grid-cols-[minmax(0,1fr)_minmax(16rem,24rem)]"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{collections.map((collection) => { const count = garage.data.vehicles.filter((vehicle) => (vehicle.collectionId ?? "my-garage") === collection.id).length; return <div key={collection.id} className={`rounded-2xl border p-3 ${selectedCollection === collection.id ? "border-cyan-200/40 bg-cyan-300/10" : "border-white/10 bg-black/10"}`}><button className="w-full text-left" onClick={() => setSelectedCollection(collection.id)}><p className="font-medium">{collection.name}</p><p className="mt-1 text-xs text-white/50">{count} vehicle{count === 1 ? "" : "s"}</p></button><div className="mt-3 flex gap-3 text-xs text-white/60"><button onClick={() => rename(collection)}>Rename</button>{collection.id !== "my-garage" && <button onClick={() => remove(collection)} className="text-amber-100">Delete</button>}</div></div>; })}</div><div className="rounded-2xl border border-white/10 bg-black/10 p-4"><label className="text-sm text-white/70">Collection dashboard<select className={input} value={selectedCollection} onChange={(event) => setSelectedCollection(event.target.value)}><option value="all">All vehicles</option>{collections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><Metric label="Vehicles" value={vehicles.length} /><Metric label="Needs attention" value={summary.attention} /><Metric label="Recorded expenses" value={`$${summary.expenses.toFixed(2)}`} /><Metric label="Fuel spend" value={`$${summary.fuel.toFixed(2)}`} /></div><p className="mt-3 text-xs text-white/45">Statuses: {[...summary.statuses.entries()].map(([status, count]) => `${status} ${count}`).join(" · ") || "No vehicles"}</p>{collections.some((item) => item.id !== "my-garage") && <label className="mt-4 block text-xs text-white/55">Delete destination<select className={input} value={deleteTarget} onChange={(event) => setDeleteTarget(event.target.value)}>{collections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}</div></div></section>;
}

function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl bg-white/[0.04] p-2"><p className="text-xs text-white/45">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
