"use client";

import { useState } from "react";
import type { DiagnosticCode, DiagnosticScan, VehicleTelemetrySnapshot } from "@/core/contracts/Garage";
import { localDateValue, useGarage } from "@/hooks/os/useGarage";

const button = "rounded-xl bg-cyan-300/20 px-3 py-2 text-sm text-cyan-50";
const input = "mt-1 w-full rounded-xl border border-white/15 bg-black/20 px-3 py-2 text-sm text-white";
const verifiedDescriptions: Record<string, string> = { P0300: "Random/Multiple Cylinder Misfire Detected", P0420: "Catalyst System Efficiency Below Threshold", P0455: "Evaporative Emission System Leak Detected" };

export default function GarageConnectedPanel({ vehicleId }: { vehicleId: string }) {
  const garage = useGarage();
  const [severity, setSeverity] = useState("medium");
  const [notes, setNotes] = useState("");
  const connection = garage.data.connections.find((item) => item.vehicleId === vehicleId);
  const scans = garage.data.diagnosticScans.filter((item) => item.vehicleId === vehicleId).sort((a, b) => b.timestamp.localeCompare(a.timestamp));
  const latestTelemetry = garage.data.telemetrySnapshots.filter((item) => item.vehicleId === vehicleId).sort((a, b) => b.timestamp.localeCompare(a.timestamp))[0];
  const latestScan = scans[0];
  const scan = () => { if (!connection) return; let codes: string[] = []; try { codes = connection.metadata?.codes ? JSON.parse(connection.metadata.codes) as string[] : []; } catch { codes = []; } const next: DiagnosticScan = { id: crypto.randomUUID(), vehicleId, timestamp: new Date().toISOString(), mileage: garage.data.vehicles.find((item) => item.id === vehicleId)?.currentMileage, milOn: codes.length > 0, codes: codes.map((code): DiagnosticCode => ({ code, description: verifiedDescriptions[code], status: "simulated" })), provider: connection.providerKind, connectionId: connection.id }; garage.saveDiagnosticScan(next); };
  const createIssue = (code: DiagnosticCode) => { const duplicate = garage.data.issues.find((item) => item.vehicleId === vehicleId && item.status !== "resolved" && item.title.includes(code.code)); if (duplicate) { window.alert(`An open Garage Issue already exists for ${code.code}: ${duplicate.title}`); return; } garage.saveIssue({ id: crypto.randomUUID(), vehicleId, title: `${code.code} diagnostic code`, description: `${code.description ?? "Diagnostic code reported by the connected vehicle."}\nSource: ${connection?.deviceLabel ?? connection?.providerKind ?? "connection"}.`, severity: severity as "low" | "medium" | "high" | "critical", status: "open", reportedAt: localDateValue(), notes: notes.trim() || undefined, createdAt: new Date().toISOString() }); setNotes(""); };
  const status = connection?.status === "connected" ? (connection.metadata?.simulated === "true" ? "Development simulation" : "Connected") : connection ? "Connection unavailable" : "Not connected";
  return <section className="rounded-3xl border border-white/15 bg-white/[.07] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-medium">Connected Vehicle</h2><p className="mt-1 text-sm text-white/55">{status}{connection?.deviceLabel ? ` · ${connection.deviceLabel}` : ""}</p></div>{connection?.status === "connected" && <button className={button} onClick={scan}>Scan for Codes</button>}</div>{connection?.status === "connected" && <div className="mt-4 grid gap-3 sm:grid-cols-2"><TelemetryCard snapshot={latestTelemetry} /><div className="rounded-2xl border border-white/10 bg-black/10 p-4"><p className="font-medium">Diagnostics</p>{latestScan ? <><p className="mt-1 text-sm text-white/55">Last scan {new Date(latestScan.timestamp).toLocaleString()}</p><p className="mt-2 text-sm">{latestScan.codes.length ? `${latestScan.codes.length} code${latestScan.codes.length === 1 ? "" : "s"} found` : "No diagnostic trouble codes found"}</p></> : <p className="mt-1 text-sm text-white/55">No scans yet.</p>}</div></div>}{latestScan?.codes.length ? <div className="mt-4 space-y-2"><h3 className="font-medium">Diagnostic Trouble Codes</h3>{latestScan.codes.map((code) => <div key={`${latestScan.id}:${code.code}`} className="rounded-xl border border-amber-200/15 bg-amber-300/5 p-3"><p className="font-medium">{code.code}</p><p className="text-sm text-white/65">{code.description ?? "Description unavailable from the verified local mapping."}</p><p className="mt-1 text-xs text-white/40">Reported by {latestScan.provider}{code.status === "simulated" ? " · simulated" : ""}</p><div className="mt-3 grid gap-2 sm:grid-cols-[10rem_1fr_auto]"><select aria-label={`${code.code} issue severity`} className={input} value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select><input aria-label={`${code.code} issue notes`} className={input} value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Issue notes (optional)" /><button className={button} onClick={() => createIssue(code)}>Create Garage Issue</button></div></div>)}</div> : null}<div className="mt-4"><h3 className="font-medium">Diagnostic history</h3><div className="mt-2 space-y-2">{scans.slice(0, 8).map((item) => <p key={item.id} className="text-sm text-white/55">{new Date(item.timestamp).toLocaleString()} · {item.provider} · {item.codes.length} code{item.codes.length === 1 ? "" : "s"}</p>)}{!scans.length && <p className="text-sm text-white/45">No diagnostic history yet.</p>}</div></div></section>;
}

function TelemetryCard({ snapshot }: { snapshot?: VehicleTelemetrySnapshot }) { return <div className="rounded-2xl border border-white/10 bg-black/10 p-4"><p className="font-medium">Telemetry</p>{snapshot ? <><p className="mt-1 text-xs text-white/45">{snapshot.source === "obd2" ? "Development simulation" : snapshot.source} · updated {new Date(snapshot.timestamp).toLocaleTimeString()}</p><div className="mt-3 grid grid-cols-2 gap-2 text-sm">{(["rpm", "speed", "coolantTemperature", "batteryVoltage", "engineLoad", "fuelLevel", "intakeTemperature"] as const).filter((key) => snapshot[key] !== undefined).map((key) => <div key={key}><span className="text-white/45">{key}</span><span className="ml-2">{snapshot[key]}</span></div>)}</div></> : <p className="mt-1 text-sm text-white/45">No telemetry received.</p>}</div>; }
