"use client";

import { FormEvent, type ReactNode, useMemo, useState } from "react";
import type { ExpenseCategory, IssueSeverity, IssueStatus, ModificationCategory, Vehicle, VehicleExpense, VehicleIssue, VehicleMaintenanceItem, VehicleModification, VehicleReminder, VehicleServiceRecord, VehicleStatus } from "@/core/contracts/Garage";
import { addCalendarMonths, localDateValue, reminderStatus, useGarage } from "@/hooks/os/useGarage";

const tabs = ["Overview", "Maintenance", "Service", "Issues", "Modifications", "Expenses", "Reminders"] as const;
type Tab = typeof tabs[number];
const input = "mt-1 w-full rounded-xl border border-white/15 bg-black/20 px-3 py-2 text-sm text-white outline-none focus:border-cyan-300/60";
const button = "rounded-xl bg-cyan-300/20 px-3 py-2 text-sm text-cyan-50 hover:bg-cyan-300/30 focus:outline-none focus:ring-2 focus:ring-cyan-200";
const field = (value: FormDataEntryValue | null) => typeof value === "string" ? value.trim() : "";
const optionalNumber = (value: FormDataEntryValue | null) => { const text = field(value); return text === "" ? undefined : Number(text); };
const makeId = () => crypto.randomUUID();
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });

export default function GarageView() {
  const garage = useGarage();
  const [tab, setTab] = useState<Tab>("Overview");
  const [editing, setEditing] = useState<string | null>(null);
  const vehicle = garage.selectedVehicle;
  const summary = garage.summary;
  const attention = useMemo(() => !vehicle || !summary ? [] : [
    ...summary.maintenance.filter((item) => ["overdue", "dueSoon"].includes(summary.statusById.get(item.id) ?? "")),
    ...summary.issues.filter((item) => item.status !== "resolved"),
    ...summary.reminders.filter((item) => ["overdue", "dueSoon"].includes(reminderStatus(item, vehicle.currentMileage))),
  ], [summary, vehicle]);
  const saveVehicle = (event: FormEvent<HTMLFormElement>, existing?: Vehicle) => { event.preventDefault(); const data = new FormData(event.currentTarget); const year = Number(data.get("year")); const mileage = Number(data.get("mileage")); if (!Number.isInteger(year) || year < 1886 || year > new Date().getFullYear() + 2 || !Number.isFinite(mileage) || mileage < 0) return; if (existing && mileage < existing.currentMileage && !window.confirm("This lowers the recorded odometer. Continue only if this is a deliberate correction.")) return; const stamp = new Date().toISOString(); garage.saveVehicle({ id: existing?.id ?? makeId(), nickname: field(data.get("nickname")), year, make: field(data.get("make")), model: field(data.get("model")), trim: field(data.get("trim")) || undefined, vin: field(data.get("vin")) || undefined, licensePlate: field(data.get("plate")) || undefined, currentMileage: mileage, status: field(data.get("status")) as VehicleStatus, notes: field(data.get("notes")) || undefined, createdAt: existing?.createdAt ?? stamp, updatedAt: stamp }); setEditing(null); event.currentTarget.reset(); };
  const saveMaintenance = (event: FormEvent<HTMLFormElement>, existing?: VehicleMaintenanceItem) => { event.preventDefault(); if (!vehicle) return; const data = new FormData(event.currentTarget); const intervalMiles = optionalNumber(data.get("intervalMiles")); const intervalMonths = optionalNumber(data.get("intervalMonths")); const lastMileage = optionalNumber(data.get("lastMileage")); const nextMileage = optionalNumber(data.get("nextMileage")); if ([intervalMiles, intervalMonths, lastMileage, nextMileage].some((value) => value !== undefined && (!Number.isFinite(value) || value < 0))) return; garage.saveMaintenance({ id: existing?.id ?? makeId(), vehicleId: vehicle.id, name: field(data.get("name")), intervalMiles, intervalMonths, lastServiceMileage: lastMileage, lastServiceDate: field(data.get("lastDate")) || undefined, nextDueMileage: nextMileage, nextDueDate: field(data.get("nextDate")) || undefined, priority: field(data.get("priority")) as VehicleMaintenanceItem["priority"], notes: field(data.get("notes")) || undefined, createdAt: existing?.createdAt ?? new Date().toISOString() }); setEditing(null); event.currentTarget.reset(); };
  const saveService = (event: FormEvent<HTMLFormElement>, existing?: VehicleServiceRecord) => { event.preventDefault(); if (!vehicle) return; const data = new FormData(event.currentTarget); const mileage = optionalNumber(data.get("mileage")); const cost = optionalNumber(data.get("cost")); if ((mileage !== undefined && mileage < 0) || (cost !== undefined && cost < 0)) return; garage.saveService({ id: existing?.id ?? makeId(), vehicleId: vehicle.id, title: field(data.get("title")), date: field(data.get("date")) || localDateValue(), mileage, description: field(data.get("description")) || undefined, cost, shop: field(data.get("shop")) || undefined, maintenanceItemId: field(data.get("maintenance")) || undefined, createdAt: existing?.createdAt ?? new Date().toISOString() }); setEditing(null); event.currentTarget.reset(); };
  const saveIssue = (event: FormEvent<HTMLFormElement>, existing?: VehicleIssue) => { event.preventDefault(); if (!vehicle) return; const data = new FormData(event.currentTarget); const mileage = optionalNumber(data.get("mileage")); if (mileage !== undefined && mileage < 0) return; const status = field(data.get("status")) as IssueStatus; garage.saveIssue({ id: existing?.id ?? makeId(), vehicleId: vehicle.id, title: field(data.get("title")), description: field(data.get("description")) || undefined, severity: field(data.get("severity")) as IssueSeverity, status, reportedAt: field(data.get("reportedAt")) || localDateValue(), resolvedAt: status === "resolved" ? existing?.resolvedAt ?? localDateValue() : undefined, mileage, notes: field(data.get("notes")) || undefined, createdAt: existing?.createdAt ?? new Date().toISOString() }); setEditing(null); event.currentTarget.reset(); };
  const saveModification = (event: FormEvent<HTMLFormElement>, existing?: VehicleModification) => { event.preventDefault(); if (!vehicle) return; const data = new FormData(event.currentTarget); const mileage = optionalNumber(data.get("mileage")); const cost = optionalNumber(data.get("cost")); if ((mileage !== undefined && mileage < 0) || (cost !== undefined && cost < 0)) return; garage.saveModification({ id: existing?.id ?? makeId(), vehicleId: vehicle.id, name: field(data.get("name")), category: field(data.get("category")) as ModificationCategory, installedAt: field(data.get("installedAt")) || undefined, mileage, cost, description: field(data.get("description")) || undefined, status: field(data.get("status")) || undefined, createdAt: existing?.createdAt ?? new Date().toISOString() }); setEditing(null); event.currentTarget.reset(); };
  const saveExpense = (event: FormEvent<HTMLFormElement>, existing?: VehicleExpense) => { event.preventDefault(); if (!vehicle) return; const data = new FormData(event.currentTarget); const amount = Number(data.get("amount")); const mileage = optionalNumber(data.get("mileage")); if (!Number.isFinite(amount) || amount < 0 || (mileage !== undefined && mileage < 0)) return; garage.saveExpense({ id: existing?.id ?? makeId(), vehicleId: vehicle.id, date: field(data.get("date")) || localDateValue(), category: field(data.get("category")) as ExpenseCategory, amount, description: field(data.get("description")) || undefined, mileage, createdAt: existing?.createdAt ?? new Date().toISOString() }); setEditing(null); event.currentTarget.reset(); };
  const saveReminder = (event: FormEvent<HTMLFormElement>, existing?: VehicleReminder) => { event.preventDefault(); if (!vehicle) return; const data = new FormData(event.currentTarget); const dueMileage = optionalNumber(data.get("dueMileage")); if (dueMileage !== undefined && dueMileage < 0) return; garage.saveReminder({ id: existing?.id ?? makeId(), vehicleId: vehicle.id, title: field(data.get("title")), dueDate: field(data.get("dueDate")) || undefined, dueMileage, completed: existing?.completed ?? false, createdAt: existing?.createdAt ?? new Date().toISOString() }); setEditing(null); event.currentTarget.reset(); };
  const markServiced = (item: VehicleMaintenanceItem) => { if (!vehicle) return; const serviceDate = window.prompt("Service date (YYYY-MM-DD)", localDateValue()); if (!serviceDate) return; const mileageValue = window.prompt("Service mileage", String(vehicle.currentMileage)); if (mileageValue === null || Number(mileageValue) < 0) return; const costValue = window.prompt("Cost (optional)", ""); const notes = window.prompt("Service notes (optional)", ""); const mileage = Number(mileageValue); const cost = costValue ? Number(costValue) : undefined; if (!Number.isFinite(mileage) || (cost !== undefined && (!Number.isFinite(cost) || cost < 0))) return; garage.saveService({ id: makeId(), vehicleId: vehicle.id, title: item.name, date: serviceDate, mileage, cost, description: notes || undefined, maintenanceItemId: item.id, createdAt: new Date().toISOString() }); garage.saveMaintenance({ ...item, lastServiceDate: serviceDate, lastServiceMileage: mileage, nextDueMileage: item.intervalMiles === undefined ? undefined : mileage + item.intervalMiles, nextDueDate: item.intervalMonths === undefined ? undefined : addCalendarMonths(serviceDate, item.intervalMonths) }); };
  const remove = (label: string, action: () => void) => { if (window.confirm(`Delete this ${label}? This only removes local Garage data.`)) action(); };

  if (garage.loading) return <p className="text-sm text-white/60">Loading your garage…</p>;
  return <div className="mx-auto max-w-6xl space-y-5 text-white"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-semibold">Garage</h1><p className="mt-1 text-sm text-white/55">Local vehicle records, maintenance, and costs.</p></div><select aria-label="Selected vehicle" className="rounded-xl border border-white/15 bg-slate-950/70 px-3 py-2 text-sm" value={vehicle?.id ?? ""} onChange={(event) => garage.selectVehicle(event.target.value)}><option value="">Select a vehicle</option>{garage.data.vehicles.map((item) => <option key={item.id} value={item.id}>{item.nickname} · {item.year} {item.make} {item.model}</option>)}</select></header>
    <nav aria-label="Garage sections" className="flex flex-wrap gap-2 border-b border-white/10 pb-3">{tabs.map((item) => <button key={item} onClick={() => { setTab(item); setEditing(null); }} className={`rounded-full px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-cyan-200 ${tab === item ? "bg-cyan-300/20 text-cyan-100" : "text-white/60 hover:bg-white/10"}`}>{item}</button>)}</nav>
    {!vehicle ? <Panel title="Add your first vehicle"><VehicleForm onSubmit={saveVehicle} /></Panel> : <>
      <section className="rounded-3xl border border-white/15 bg-white/[0.07] p-5 backdrop-blur-xl"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-cyan-100/60">{vehicle.status}</p><h2 className="mt-1 text-2xl font-semibold">{vehicle.nickname}</h2><p className="text-white/60">{vehicle.year} {vehicle.make} {vehicle.model}{vehicle.trim ? ` ${vehicle.trim}` : ""} · {vehicle.currentMileage.toLocaleString()} mi</p></div><div className="flex gap-2"><button className={button} onClick={() => setEditing(editing === "vehicle" ? null : "vehicle")}>Edit vehicle</button><button className="rounded-xl border border-red-300/25 px-3 py-2 text-sm text-red-100" onClick={() => window.confirm(`Delete ${vehicle.nickname}? Its local Garage maintenance, service, issue, modification, expense, reminder, and mileage records will also be removed.`) && garage.removeVehicle(vehicle.id)}>Delete</button></div></div>{editing === "vehicle" && <VehicleForm vehicle={vehicle} onSubmit={(event) => saveVehicle(event, vehicle)} />}</section>
      {tab === "Overview" && <Overview vehicle={vehicle} summary={summary} attention={attention.length} />}
      {tab === "Maintenance" && <Panel title="Maintenance" action={<button className={button} onClick={() => setEditing(editing === "maintenance:new" ? null : "maintenance:new")}>+ Add maintenance</button>}>{editing === "maintenance:new" && <MaintenanceForm onSubmit={saveMaintenance} vehicle={vehicle} />}{summary?.maintenance.map((item) => editing === `maintenance:${item.id}` ? <MaintenanceForm key={item.id} item={item} vehicle={vehicle} onSubmit={(event) => saveMaintenance(event, item)} /> : <Record key={item.id} title={item.name} detail={`${summary.statusById.get(item.id)?.replace(/([A-Z])/g, " $1")} · ${item.priority} priority`} actions={<><button onClick={() => setEditing(`maintenance:${item.id}`)}>Edit</button><button onClick={() => markServiced(item)} className="text-cyan-100">Mark serviced</button><button onClick={() => remove("maintenance item", () => garage.removeMaintenance(item.id))}>Delete</button></>} />) ?? <Empty label="No maintenance items." />}</Panel>}
      {tab === "Service" && <Panel title="Service history" action={<button className={button} onClick={() => setEditing(editing === "service:new" ? null : "service:new")}>+ Add service</button>}>{editing === "service:new" && <ServiceForm vehicle={vehicle} maintenance={summary?.maintenance ?? []} onSubmit={saveService} />}{summary?.services.map((item) => editing === `service:${item.id}` ? <ServiceForm key={item.id} item={item} vehicle={vehicle} maintenance={summary?.maintenance ?? []} onSubmit={(event) => saveService(event, item)} /> : <Record key={item.id} title={item.title} detail={`${item.date}${item.cost !== undefined ? ` · ${money.format(item.cost)}` : ""}`} actions={<><button onClick={() => setEditing(`service:${item.id}`)}>Edit</button><button onClick={() => remove("service record", () => garage.removeService(item.id))}>Delete</button></>} />) ?? <Empty label="No service history." />}</Panel>}
      {tab === "Issues" && <Panel title="Issues" action={<button className={button} onClick={() => setEditing(editing === "issue:new" ? null : "issue:new")}>+ Add issue</button>}>{editing === "issue:new" && <IssueForm onSubmit={saveIssue} vehicle={vehicle} />}{summary?.issues.map((item) => editing === `issue:${item.id}` ? <IssueForm key={item.id} item={item} vehicle={vehicle} onSubmit={(event) => saveIssue(event, item)} /> : <Record key={item.id} title={item.title} detail={`${item.severity} · ${item.status}`} urgent={item.status !== "resolved" && ["high", "critical"].includes(item.severity)} actions={<><button onClick={() => setEditing(`issue:${item.id}`)}>Edit</button><button onClick={() => garage.saveIssue({ ...item, status: item.status === "resolved" ? "open" : "resolved", resolvedAt: item.status === "resolved" ? undefined : localDateValue() })}>{item.status === "resolved" ? "Reopen" : "Resolve"}</button><button onClick={() => remove("issue", () => garage.removeIssue(item.id))}>Delete</button></>} />) ?? <Empty label="No issues." />}</Panel>}
      {tab === "Modifications" && <Panel title="Modifications" action={<button className={button} onClick={() => setEditing(editing === "mod:new" ? null : "mod:new")}>+ Add modification</button>}>{editing === "mod:new" && <ModificationForm vehicle={vehicle} onSubmit={saveModification} />}{summary?.modifications.map((item) => editing === `mod:${item.id}` ? <ModificationForm key={item.id} item={item} vehicle={vehicle} onSubmit={(event) => saveModification(event, item)} /> : <Record key={item.id} title={item.name} detail={item.category} actions={<><button onClick={() => setEditing(`mod:${item.id}`)}>Edit</button><button onClick={() => remove("modification", () => garage.removeModification(item.id))}>Delete</button></>} />) ?? <Empty label="No modifications." />}</Panel>}
      {tab === "Expenses" && <Expenses vehicle={vehicle} expenses={summary?.expenses ?? []} editing={editing} setEditing={setEditing} save={saveExpense} remove={(item) => remove("expense", () => garage.removeExpense(item.id))} />}
      {tab === "Reminders" && <Panel title="Reminders" action={<button className={button} onClick={() => setEditing(editing === "reminder:new" ? null : "reminder:new")}>+ Add reminder</button>}>{editing === "reminder:new" && <ReminderForm vehicle={vehicle} onSubmit={saveReminder} />}{summary?.reminders.map((item) => editing === `reminder:${item.id}` ? <ReminderForm key={item.id} item={item} vehicle={vehicle} onSubmit={(event) => saveReminder(event, item)} /> : <Record key={item.id} title={item.title} detail={reminderStatus(item, vehicle.currentMileage).replace(/([A-Z])/g, " $1")} actions={<><button onClick={() => setEditing(`reminder:${item.id}`)}>Edit</button><button onClick={() => garage.saveReminder({ ...item, completed: !item.completed })}>{item.completed ? "Uncomplete" : "Complete"}</button><button onClick={() => remove("reminder", () => garage.removeReminder(item.id))}>Delete</button></>} />) ?? <Empty label="No reminders." />}</Panel>}
    </>}</div>;
}

function Panel({ title, action, children }: { title: string; action?: ReactNode; children: ReactNode }) { return <section className="rounded-3xl border border-white/15 bg-white/[0.07] p-5 backdrop-blur-xl"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-medium">{title}</h2>{action}</div><div className="mt-4 space-y-3">{children}</div></section>; }
function Record({ title, detail, urgent, actions }: { title: string; detail: string; urgent?: boolean; actions: ReactNode }) { return <div className={`flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 ${urgent ? "border-red-300/35 bg-red-300/10" : "border-white/10 bg-black/10"}`}><div><p className="font-medium">{title}</p><p className="text-sm text-white/55">{detail}</p></div><div className="flex flex-wrap gap-3 text-xs text-white/65">{actions}</div></div>; }
function Empty({ label }: { label: string }) { return <p className="py-4 text-sm text-white/55">{label}</p>; }
function VehicleForm({ vehicle, onSubmit }: { vehicle?: Vehicle; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={onSubmit}><Text name="nickname" label="Nickname" value={vehicle?.nickname} required/><Text name="year" label="Year" value={vehicle?.year} type="number" required/><Text name="make" label="Make" value={vehicle?.make} required/><Text name="model" label="Model" value={vehicle?.model} required/><Text name="trim" label="Trim" value={vehicle?.trim}/><Text name="mileage" label="Current mileage" value={vehicle?.currentMileage} type="number" required/><Text name="plate" label="License plate" value={vehicle?.licensePlate}/><Text name="vin" label="VIN" value={vehicle?.vin}/><Select name="status" label="Status" value={vehicle?.status ?? "active"} values={["active", "maintenance", "stored", "sold", "retired"]}/><Text name="notes" label="Notes" value={vehicle?.notes}/><button className={button}>{vehicle ? "Save changes" : "Add vehicle"}</button><button type="button" className="text-sm text-white/55" onClick={(event) => event.currentTarget.form?.reset()}>Cancel</button></form>; }
function MaintenanceForm({ item, vehicle, onSubmit }: { item?: VehicleMaintenanceItem; vehicle: Vehicle; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="grid gap-3 rounded-xl border border-cyan-200/20 bg-cyan-300/5 p-3 sm:grid-cols-2" onSubmit={onSubmit}><Text name="name" label="Name" value={item?.name} required/><Select name="priority" label="Priority" value={item?.priority ?? "medium"} values={["low", "medium", "high"]}/><Text name="intervalMiles" label="Interval miles" value={item?.intervalMiles} type="number"/><Text name="intervalMonths" label="Interval months" value={item?.intervalMonths} type="number"/><Text name="lastMileage" label="Last service mileage" value={item?.lastServiceMileage ?? vehicle.currentMileage} type="number"/><Text name="lastDate" label="Last service date" value={item?.lastServiceDate} type="date"/><Text name="nextMileage" label="Next due mileage" value={item?.nextDueMileage} type="number"/><Text name="nextDate" label="Next due date" value={item?.nextDueDate} type="date"/><Text name="notes" label="Notes" value={item?.notes}/><button className={button}>{item ? "Save changes" : "Create maintenance"}</button></form>; }
function ServiceForm({ item, vehicle, maintenance, onSubmit }: { item?: VehicleServiceRecord; vehicle: Vehicle; maintenance: VehicleMaintenanceItem[]; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="grid gap-3 rounded-xl border border-cyan-200/20 bg-cyan-300/5 p-3 sm:grid-cols-2" onSubmit={onSubmit}><Text name="title" label="Title" value={item?.title} required/><Text name="date" label="Date" value={item?.date ?? localDateValue()} type="date" required/><Text name="mileage" label="Mileage" value={item?.mileage ?? vehicle.currentMileage} type="number"/><Text name="cost" label="Cost" value={item?.cost} type="number"/><Text name="shop" label="Shop/location" value={item?.shop}/><Select name="maintenance" label="Linked maintenance" value={item?.maintenanceItemId ?? ""} values={["", ...maintenance.map((entry) => entry.id)]} labels={Object.fromEntries(maintenance.map((entry) => [entry.id, entry.name]))}/><Text name="description" label="Description" value={item?.description}/><button className={button}>{item ? "Save changes" : "Add service"}</button></form>; }
function IssueForm({ item, vehicle, onSubmit }: { item?: VehicleIssue; vehicle: Vehicle; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="grid gap-3 rounded-xl border border-cyan-200/20 bg-cyan-300/5 p-3 sm:grid-cols-2" onSubmit={onSubmit}><Text name="title" label="Title" value={item?.title} required/><Select name="severity" label="Severity" value={item?.severity ?? "medium"} values={["low", "medium", "high", "critical"]}/><Select name="status" label="Status" value={item?.status ?? "open"} values={["open", "monitoring", "resolved"]}/><Text name="reportedAt" label="Reported date" value={item?.reportedAt ?? localDateValue()} type="date"/><Text name="mileage" label="Mileage" value={item?.mileage ?? vehicle.currentMileage} type="number"/><Text name="description" label="Description" value={item?.description}/><Text name="notes" label="Notes" value={item?.notes}/><button className={button}>{item ? "Save changes" : "Add issue"}</button></form>; }
function ModificationForm({ item, vehicle, onSubmit }: { item?: VehicleModification; vehicle: Vehicle; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="grid gap-3 rounded-xl border border-cyan-200/20 bg-cyan-300/5 p-3 sm:grid-cols-2" onSubmit={onSubmit}><Text name="name" label="Name" value={item?.name} required/><Select name="category" label="Category" value={item?.category ?? "Other"} values={["Performance", "Suspension", "Wheels/Tires", "Exterior", "Interior", "Audio", "Electrical", "Other"]}/><Text name="installedAt" label="Installed date" value={item?.installedAt} type="date"/><Text name="mileage" label="Mileage" value={item?.mileage ?? vehicle.currentMileage} type="number"/><Text name="cost" label="Cost" value={item?.cost} type="number"/><Text name="status" label="Status" value={item?.status}/><Text name="description" label="Description" value={item?.description}/><button className={button}>{item ? "Save changes" : "Add modification"}</button></form>; }
function ExpenseForm({ item, vehicle, onSubmit }: { item?: VehicleExpense; vehicle: Vehicle; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="grid gap-3 rounded-xl border border-cyan-200/20 bg-cyan-300/5 p-3 sm:grid-cols-2" onSubmit={onSubmit}><Text name="date" label="Date" value={item?.date ?? localDateValue()} type="date" required/><Select name="category" label="Category" value={item?.category ?? "Other"} values={["Fuel", "Maintenance", "Repair", "Modification", "Registration", "Insurance", "Other"]}/><Text name="amount" label="Amount" value={item?.amount} type="number" required/><Text name="mileage" label="Mileage" value={item?.mileage ?? vehicle.currentMileage} type="number"/><Text name="description" label="Description" value={item?.description}/><button className={button}>{item ? "Save changes" : "Add expense"}</button></form>; }
function ReminderForm({ item, vehicle, onSubmit }: { item?: VehicleReminder; vehicle: Vehicle; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="grid gap-3 rounded-xl border border-cyan-200/20 bg-cyan-300/5 p-3 sm:grid-cols-2" onSubmit={onSubmit}><Text name="title" label="Title" value={item?.title} required/><Text name="dueDate" label="Due date" value={item?.dueDate} type="date"/><Text name="dueMileage" label="Due mileage" value={item?.dueMileage ?? vehicle.currentMileage} type="number"/><button className={button}>{item ? "Save changes" : "Add reminder"}</button></form>; }
function Text({ name, label, value, type = "text", required }: { name: string; label: string; value?: string | number; type?: string; required?: boolean }) { return <label className="text-sm text-white/70">{label}<input className={input} name={name} type={type} defaultValue={value ?? ""} min={type === "number" ? 0 : undefined} required={required}/></label>; }
function Select({ name, label, value, values, labels }: { name: string; label: string; value: string; values: string[]; labels?: Record<string, string> }) { return <label className="text-sm text-white/70">{label}<select className={input} name={name} defaultValue={value}>{values.map((item) => <option key={item} value={item}>{(labels?.[item] ?? item) || "None"}</option>)}</select></label>; }
function Expenses({ vehicle, expenses, editing, setEditing, save, remove }: { vehicle: Vehicle; expenses: VehicleExpense[]; editing: string | null; setEditing: (value: string | null) => void; save: (event: FormEvent<HTMLFormElement>, existing?: VehicleExpense) => void; remove: (item: VehicleExpense) => void }) { const month = localDateValue().slice(0, 7); const year = localDateValue().slice(0, 4); const total = (filter: (item: VehicleExpense) => boolean) => expenses.filter(filter).reduce((sum, item) => sum + item.amount, 0); return <Panel title="Expenses" action={<button className={button} onClick={() => setEditing(editing === "expense:new" ? null : "expense:new")}>+ Add expense</button>}><div className="grid gap-2 sm:grid-cols-3">{[["This month", total((item) => item.date.startsWith(month))], ["This year", total((item) => item.date.startsWith(year))], ["All time", total(() => true)]].map(([label, amount]) => <div key={String(label)} className="rounded-xl bg-black/15 p-3"><p className="text-xs text-white/55">{label}</p><p className="text-lg font-semibold">{money.format(Number(amount))}</p></div>)}</div>{editing === "expense:new" && <ExpenseForm vehicle={vehicle} onSubmit={save} />}{expenses.length ? expenses.map((item) => editing === `expense:${item.id}` ? <ExpenseForm key={item.id} item={item} vehicle={vehicle} onSubmit={(event) => save(event, item)} /> : <Record key={item.id} title={item.category} detail={`${item.date} · ${money.format(item.amount)}`} actions={<><button onClick={() => setEditing(`expense:${item.id}`)}>Edit</button><button onClick={() => remove(item)}>Delete</button></>} />) : <Empty label="No expenses recorded." />}</Panel>; }
function Overview({ vehicle, summary, attention }: { vehicle: Vehicle; summary: ReturnType<typeof useGarage>["summary"]; attention: number }) { const nextMaintenance = summary?.maintenance[0]; const nextReminder = summary?.reminders.find((item) => !item.completed); return <div className="grid gap-3 md:grid-cols-2"><Panel title="Attention"><p className="text-3xl font-semibold">{attention}</p><p className="text-sm text-white/55">items need attention for {vehicle.nickname}</p></Panel><Panel title="Next maintenance"><p>{nextMaintenance?.name ?? "No maintenance scheduled"}</p><p className="text-sm text-white/55">{nextMaintenance ? summary?.statusById.get(nextMaintenance.id) : ""}</p></Panel><Panel title="Open issues"><p>{summary?.issues.filter((item) => item.status !== "resolved").length ?? 0} open</p></Panel><Panel title="Next reminder"><p>{nextReminder?.title ?? "No reminders"}</p></Panel><Panel title="Recent service"><p>{summary?.services[0]?.title ?? "No service history"}</p><p className="text-sm text-white/55">{summary?.services[0]?.date ?? ""}</p></Panel></div>; }
