import { NextResponse } from "next/server";
import { requireAdmin } from "@/services/admin/auth";
import { assertSameOrigin } from "@/services/security/origin";
import { addInternalNote, getAdminReport, updateSupportReport } from "@/services/support/repository";
import { recordAudit } from "@/services/admin/repository";
import type { SupportReportStatus } from "@/core/contracts/Support";
const statuses = ["submitted", "reviewing", "needs_info", "fixing", "fixed", "closed"];
export async function GET(request: Request, context: { params: Promise<{ reportId: string }> }) { try { await requireAdmin(request); const { reportId } = await context.params; const report = await getAdminReport(reportId); return report ? NextResponse.json({ report }, { headers: { "Cache-Control": "no-store" } }) : NextResponse.json({ error: "Report not found." }, { status: 404 }); } catch (error) { if (error instanceof Response) return error; return NextResponse.json({ error: "Report unavailable." }, { status: 503 }); } }
export async function PATCH(request: Request, context: { params: Promise<{ reportId: string }> }) { try { assertSameOrigin(request); const admin = await requireAdmin(request); const { reportId } = await context.params; const body = await request.json() as { status?: string; internalNote?: string; userMessage?: string }; if (body.status && !statuses.includes(body.status)) return NextResponse.json({ error: "Invalid status." }, { status: 400 }); if (body.internalNote?.trim()) await addInternalNote(reportId, admin.id, body.internalNote.trim().slice(0, 3000)); const report = await updateSupportReport(reportId, admin.id, body.status as SupportReportStatus | undefined, body.userMessage?.trim().slice(0, 1000)); if (!report) return NextResponse.json({ error: "Report not found." }, { status: 404 }); await recordAudit(admin.id, report.accountId ?? undefined, `support.${body.status ? "status" : "note"}`, { reportReference: report.publicReference, status: report.status }); return NextResponse.json({ report: await getAdminReport(reportId) }); } catch (error) { if (error instanceof Response) return error; return NextResponse.json({ error: "Report update failed." }, { status: 503 }); } }
