#!/bin/bash

#########################################
# CSS
#########################################

create_css() {

    FILE="$1"

    create_file "$FILE" || return

cat > "$FILE" <<EOF
/* $(basename "$FILE") */
/* Generated by Cosmic Builder */
EOF

    echo "✅ $FILE"

    ((CREATED++))
    ((STYLES++))
}

#########################################
# JSON
#########################################

create_json() {

    FILE="$1"

    create_file "$FILE" || return

cat > "$FILE" <<EOF
{}
EOF

    echo "✅ $FILE"

    ((CREATED++))
}

#########################################
# Markdown
#########################################

create_md() {

    FILE="$1"

    create_file "$FILE" || return

    TITLE=$(basename "$FILE" .md)

cat > "$FILE" <<EOF
# ${TITLE}

Generated by Cosmic Builder.
EOF

    echo "✅ $FILE"

    ((CREATED++))
}

#########################################
# Build Assets
#########################################

build_styles() {

#########################################
# CSS
#########################################

create_css styles/os/animations.css
create_css styles/os/background.css
create_css styles/os/glass.css
create_css styles/os/themes.css
create_css styles/os/typography.css
create_css styles/os/widgets.css
create_css styles/os/windows.css

#########################################
# JSON
#########################################

create_json data/memory.json

#########################################
# DOCS
#########################################

create_md docs/API.md
create_md docs/ARCHITECTURE.md
create_md docs/CHANGELOG.md
create_md docs/CONTRIBUTING.md
create_md docs/ROADMAP.md

}