import { getSchoolAssetById } from "./assetRepository";
import { getSchoolAssetStore } from "./sources/storage";
import { getSchoolAudioTranscript, updateSchoolAudioTranscript } from "./audioRepository";
import { getSchoolSource, updateSchoolSourceRecord } from "./sources/repository";
import { organizeSchoolTranscript } from "./audioOrganizer";
import { SchoolAudioValidationError, SchoolTranscriptionError, detectSchoolAudioSignature, normalizeSchoolAudioMime, validateSchoolAudio, type SchoolAudioMimeType } from "./audio";
import { transcribeWithSchoolRouter } from "./transcriptionRouter";

function safeError(error: unknown) { if (error instanceof SchoolTranscriptionError) return error.code === "transcription_quota" ? "OpenAI transcription limit reached." : ["transcription_rate_limit", "transcription_provider_unavailable", "transcription_timeout"].includes(error.code) ? "Transcription temporarily unavailable." : error.code === "transcription_invalid_audio" ? "The recording could not be validated as audio." : error.code === "transcription_unsupported_audio" ? "This recording format is not supported." : error.code === "transcription_too_large" ? "This recording is too large for the configured transcription providers." : error.code === "transcription_auth_configuration" ? "Transcription is not configured." : "Transcription could not be completed."; return error instanceof Error ? error.message.replace(/\s+/g, " ").slice(0, 240) : "Audio processing failed."; }
export async function processSchoolAudio(accountId: string, transcriptId: string) {
  const job = await getSchoolAudioTranscript(accountId, transcriptId); if (!job) return null;
  const source = await getSchoolSource(accountId, job.sourceId); const asset = await getSchoolAssetById(accountId, job.assetId);
  if (!source || !asset) throw new Error("Recording is unavailable.");
  if (!job.transcript) {
    await updateSchoolAudioTranscript(accountId, job.id, { status: "transcribing", processingError: null }); await updateSchoolSourceRecord(accountId, source.id, { processingStatus: "processing", processingError: null });
    let retrievedByteLength: number | null = null;
    try { const bytes = await getSchoolAssetStore().get({ accountId, key: asset.storageKey }); if (!bytes) throw new Error("Recording is unavailable."); retrievedByteLength = bytes.byteLength; const normalizedMime = normalizeSchoolAudioMime(asset.mimeType, asset.originalFileName); const signatureKind = detectSchoolAudioSignature(bytes); if (process.env.NODE_ENV === "production") console.info("voice_note_audio_validation", { operation: "voice_note_audio_validation", voiceNoteId: job.id, byteLength: retrievedByteLength, declaredMime: asset.mimeType, normalizedMime, signatureKind, validationResult: "pending" }); const mime = validateSchoolAudio({ type: asset.mimeType, name: asset.originalFileName, size: asset.size }, bytes) as SchoolAudioMimeType; if (process.env.NODE_ENV === "production") console.info("voice_note_audio_validation", { operation: "voice_note_audio_validation", voiceNoteId: job.id, byteLength: bytes.byteLength, declaredMime: asset.mimeType, normalizedMime, signatureKind, validationResult: "accepted" }); const routed = await transcribeWithSchoolRouter({ bytes, mimeType: mime, fileName: asset.safeFileName }); await updateSchoolAudioTranscript(accountId, job.id, { transcript: routed.result.text, segments: routed.result.segments ?? null, provider: routed.result.provider, model: routed.result.model, providerAttempts: routed.attempts, status: "transcribed", processingError: null });
    } catch (error) { if (process.env.NODE_ENV === "production" && error instanceof SchoolAudioValidationError) console.info("voice_note_audio_validation", { operation: "voice_note_audio_validation", voiceNoteId: job.id, byteLength: retrievedByteLength, declaredMime: asset.mimeType, normalizedMime: normalizeSchoolAudioMime(asset.mimeType, asset.originalFileName), signatureKind: retrievedByteLength === 0 ? "empty" : "unknown", validationResult: "rejected", validationReason: error.code }); const message = safeError(error); const attempts = error && typeof error === "object" && "attempts" in error ? (error as { attempts?: unknown }).attempts : undefined; await updateSchoolAudioTranscript(accountId, job.id, { ...(attempts ? { providerAttempts: attempts } : {}), status: "failed", processingError: message }); await updateSchoolSourceRecord(accountId, source.id, { processingStatus: "failed", processingError: "Recording saved; transcription failed. Retry Processing is available." }); return getSchoolAudioTranscript(accountId, job.id); }
  }
  const current = await getSchoolAudioTranscript(accountId, job.id); if (!current?.transcript) return current;
  if (!current.organizedContent) { await updateSchoolAudioTranscript(accountId, job.id, { status: "organizing", processingError: null }); try { const organized = await organizeSchoolTranscript({ transcript: current.transcript }); await updateSchoolAudioTranscript(accountId, job.id, { title: organized.title, organizedContent: organized.content, organizedTopics: organized.topics, status: "ready-for-review", processingError: null }); await updateSchoolSourceRecord(accountId, source.id, { processingStatus: "needs_review", processingError: null, extractedText: current.transcript }); } catch (error) { const message = safeError(error); await updateSchoolAudioTranscript(accountId, job.id, { status: "failed", processingError: message }); await updateSchoolSourceRecord(accountId, source.id, { processingStatus: "failed", processingError: "Recording saved; organization failed. Transcript retained for retry." }); } }
  return getSchoolAudioTranscript(accountId, job.id);
}
