import "server-only";
import { and, desc, eq } from "drizzle-orm";
import { getDatabase } from "@/services/database/client";
import { schoolEmailProposals, schoolSources } from "@/services/database/schema";
import type { SchoolEmailProposal } from "@/core/contracts/SchoolEmail";

function toProposal(row: typeof schoolEmailProposals.$inferSelect): SchoolEmailProposal { return { id: row.id, accountId: row.userId, sourceId: row.sourceId, type: row.type as SchoolEmailProposal["type"], title: row.title, description: row.description, evidence: row.evidence, confidence: row.confidence, status: row.status as SchoolEmailProposal["status"], ...(row.appliedAt ? { appliedAt: row.appliedAt } : {}), ...(row.error ? { error: row.error } : {}), createdAt: row.createdAt, updatedAt: row.updatedAt }; }
export async function listSchoolEmailProposals(accountId: string, status?: string) { const rows = await getDatabase().select().from(schoolEmailProposals).where(and(eq(schoolEmailProposals.userId, accountId), status ? eq(schoolEmailProposals.status, status) : undefined)).orderBy(desc(schoolEmailProposals.createdAt)); return rows.map(toProposal); }
export async function getSchoolEmailProposal(accountId: string, id: string) { const [row] = await getDatabase().select().from(schoolEmailProposals).where(and(eq(schoolEmailProposals.userId, accountId), eq(schoolEmailProposals.id, id))).limit(1); return row ? toProposal(row) : null; }
export async function upsertSchoolEmailProposal(input: typeof schoolEmailProposals.$inferInsert) { const [row] = await getDatabase().insert(schoolEmailProposals).values(input).onConflictDoNothing({ target: schoolEmailProposals.id }).returning(); return row ? toProposal(row) : null; }
export async function updateSchoolEmailProposal(accountId: string, id: string, status: "approved" | "dismissed") { const [row] = await getDatabase().update(schoolEmailProposals).set({ status, updatedAt: new Date() }).where(and(eq(schoolEmailProposals.userId, accountId), eq(schoolEmailProposals.id, id))).returning(); return row ? toProposal(row) : null; }
export async function markSchoolEmailProposal(accountId: string, id: string, status: "applied" | "failed" | "needs_target", error?: string) { const [row] = await getDatabase().update(schoolEmailProposals).set({ status, ...(status === "applied" ? { appliedAt: new Date(), error: null } : { error: error?.slice(0, 500) ?? null }), updatedAt: new Date() }).where(and(eq(schoolEmailProposals.userId, accountId), eq(schoolEmailProposals.id, id))).returning(); return row ? toProposal(row) : null; }
export async function createSchoolEmailSource(input: typeof schoolSources.$inferInsert) { const [row] = await getDatabase().insert(schoolSources).values(input).onConflictDoNothing({ target: schoolSources.id }).returning(); return row ?? null; }
