import "server-only";
import { and, asc, desc, eq } from "drizzle-orm";
import { getDatabase } from "@/services/database/client";
import { schoolFlashcards, schoolResources, schoolStudySets } from "@/services/database/schema";

export async function listStudySets(accountId: string, courseId?: string) { return getDatabase().select().from(schoolStudySets).where(courseId ? and(eq(schoolStudySets.accountId, accountId), eq(schoolStudySets.courseId, courseId)) : eq(schoolStudySets.accountId, accountId)).orderBy(desc(schoolStudySets.updatedAt)); }
export async function getStudySet(accountId: string, id: string) { return (await getDatabase().select().from(schoolStudySets).where(and(eq(schoolStudySets.accountId, accountId), eq(schoolStudySets.id, id))).limit(1))[0] ?? null; }
export async function createStudySet(input: typeof schoolStudySets.$inferInsert) { return (await getDatabase().insert(schoolStudySets).values(input).returning())[0] ?? null; }
export async function updateStudySet(accountId: string, id: string, input: Partial<typeof schoolStudySets.$inferInsert>) { return (await getDatabase().update(schoolStudySets).set({ ...input, updatedAt: new Date() }).where(and(eq(schoolStudySets.accountId, accountId), eq(schoolStudySets.id, id))).returning())[0] ?? null; }
export async function deleteStudySet(accountId: string, id: string) { return (await getDatabase().delete(schoolStudySets).where(and(eq(schoolStudySets.accountId, accountId), eq(schoolStudySets.id, id))).returning({ id: schoolStudySets.id }))[0] ?? null; }
export async function listStudyCards(accountId: string, setId?: string) { return getDatabase().select().from(schoolFlashcards).where(setId ? and(eq(schoolFlashcards.accountId, accountId), eq(schoolFlashcards.setId, setId)) : eq(schoolFlashcards.accountId, accountId)).orderBy(asc(schoolFlashcards.createdAt), asc(schoolFlashcards.id)); }
export async function getStudyCard(accountId: string, id: string) { return (await getDatabase().select().from(schoolFlashcards).where(and(eq(schoolFlashcards.accountId, accountId), eq(schoolFlashcards.id, id))).limit(1))[0] ?? null; }
export async function createStudyCard(input: typeof schoolFlashcards.$inferInsert) { return (await getDatabase().insert(schoolFlashcards).values(input).returning())[0] ?? null; }
export async function updateStudyCard(accountId: string, id: string, input: Partial<typeof schoolFlashcards.$inferInsert>) { return (await getDatabase().update(schoolFlashcards).set({ ...input, updatedAt: new Date() }).where(and(eq(schoolFlashcards.accountId, accountId), eq(schoolFlashcards.id, id))).returning())[0] ?? null; }
export async function deleteStudyCard(accountId: string, id: string) { return (await getDatabase().delete(schoolFlashcards).where(and(eq(schoolFlashcards.accountId, accountId), eq(schoolFlashcards.id, id))).returning({ id: schoolFlashcards.id }))[0] ?? null; }
export async function listSchoolResources(accountId: string, courseId?: string) { return getDatabase().select().from(schoolResources).where(courseId ? and(eq(schoolResources.accountId, accountId), eq(schoolResources.courseId, courseId)) : eq(schoolResources.accountId, accountId)).orderBy(desc(schoolResources.updatedAt)); }
export async function createSchoolResource(input: typeof schoolResources.$inferInsert) { return (await getDatabase().insert(schoolResources).values(input).returning())[0] ?? null; }
export async function updateSchoolResource(accountId: string, id: string, input: Partial<typeof schoolResources.$inferInsert>) { return (await getDatabase().update(schoolResources).set({ ...input, updatedAt: new Date() }).where(and(eq(schoolResources.accountId, accountId), eq(schoolResources.id, id))).returning())[0] ?? null; }
export async function deleteSchoolResource(accountId: string, id: string) { return (await getDatabase().delete(schoolResources).where(and(eq(schoolResources.accountId, accountId), eq(schoolResources.id, id))).returning({ id: schoolResources.id }))[0] ?? null; }
