export interface SyllabusStructuredFinding { kind: "meeting_schedule" | "office_hours" | "grade_scale" | "textbook" | "weekly_schedule" | "recurring_expectation"; subject: string; value: string; data: Record<string, unknown>; evidence: string; }
const dayMap: Record<string, string> = { m: "MO", mo: "MO", monday: "MO", t: "TU", tu: "TU", tue: "TU", tuesday: "TU", w: "WE", we: "WE", wed: "WE", wednesday: "WE", r: "TH", th: "TH", thu: "TH", thursday: "TH", f: "FR", fr: "FR", fri: "FR", friday: "FR" };
function days(value: string) { return [...new Set(value.toLowerCase().split(/\s*(?:and|,|\/|-)\s*/).flatMap((item) => item.match(/m|t|w|r|f|mo|tu|we|th|fr|mon(?:day)?|tue(?:sday)?|wed(?:nesday)?|thu(?:rsday)?|fri(?:day)?/g) ?? []).map((item) => dayMap[item]))].filter(Boolean); }
function times(value: string) { const match = value.match(/(\d{1,2}(?::\d{2})?\s*(?:AM|PM)?)\s*[–—-]\s*(\d{1,2}(?::\d{2})?\s*(?:AM|PM)?)/i); return match ? { startTime: match[1].replace(/\s+/g, " "), endTime: match[2].replace(/\s+/g, " ") } : {}; }
export function extractStructuredSyllabus(text: string): SyllabusStructuredFinding[] { const lines = text.split("\n").map((line) => line.trim()).filter(Boolean); const result: SyllabusStructuredFinding[] = []; let week: Record<string, unknown> | null = null;
  for (const [index, line] of lines.entries()) { const evidence = line; const lower = line.toLowerCase();
    if (/^(meeting|class)\s*(schedule|time)?\s*:/i.test(line) || (/\b(?:mwf|tr|tuesday\s+and\s+thursday)\b/i.test(line) && /\d/.test(line))) { const value = line.replace(/^[^:]+:\s*/i, ""); const parsed = times(value); result.push({ kind: "meeting_schedule", subject: "meeting_schedule", value, data: { daysOfWeek: days(value), ...parsed, location: value.match(/(?:,|\s)(?:room\s+)?([A-Z]{2,5}\s*\d{2,4})\s*$/i)?.[1] }, evidence }); }
    if (/^office\s*hours?/i.test(line)) { const value = line.replace(/^[^:]+:\s*/i, ""); result.push({ kind: "office_hours", subject: "office_hours", value, data: { daysOfWeek: days(value), ...times(value), ...(lower.includes("by appointment") ? { notes: "By appointment" } : {}), ...(value.match(/https?:\/\/\S+/)?.[0] ? { virtualUrl: value.match(/https?:\/\/\S+/)![0] } : {}) }, evidence }); }
    const grade = /^(A[+-]?|B[+-]?|C[+-]?|D[+-]?|F)\s*(?:=|:|>=?)\s*(\d+(?:\.\d+)?)(?:\s*[–—-]\s*(\d+(?:\.\d+)?))?/i.exec(line); if (grade) result.push({ kind: "grade_scale", subject: "grade_scale", value: line, data: { letter: grade[1].toUpperCase(), minimumPercent: Number(grade[2]), ...(grade[3] ? { maximumPercent: Number(grade[3]) } : {}) }, evidence });
    if (/^(required|recommended|optional)?\s*(text|book|textbook)/i.test(line)) { const value = line.replace(/^(required|recommended|optional)?\s*(text|book|textbook)\s*:??\s*/i, "").trim(); result.push({ kind: "textbook", subject: "textbook", value, data: { requirementLevel: lower.includes("recommended") ? "recommended" : lower.includes("optional") ? "optional" : "required", title: value.replace(/,?\s*\d+(?:st|nd|rd|th)\s+edition.*$/i, "").trim(), ...(value.match(/ISBN\s*[:#]?\s*([\d-]+)/i)?.[1] ? { isbn: value.match(/ISBN\s*[:#]?\s*([\d-]+)/i)![1] } : {}) }, evidence }); }
    const recurring = /\b(weekly|every\s+(?:monday|tuesday|wednesday|thursday|friday|lab|class)|each\s+week|before\s+each)\b/i.exec(line); if (recurring) result.push({ kind: "recurring_expectation", subject: "recurring_expectation", value: line, data: { description: line, frequency: recurring[1], ...(days(line).length ? { weekday: days(line)[0] } : {}), ...times(line) }, evidence });
    const weekMatch = /^week\s*(\d+)\s*(?:[—:-]\s*(.*))?$/i.exec(line); if (weekMatch) week = { weekNumber: Number(weekMatch[1]), label: weekMatch[2] ?? "" }; else if (week) { const row = /^(topics?|read|reading|assignment|exam)\s*:\s*(.+)$/i.exec(line); if (row) result.push({ kind: "weekly_schedule", subject: `week_${week.weekNumber}`, value: row[2], data: { ...week, [row[1].toLowerCase().startsWith("topic") ? "topics" : row[1].toLowerCase().startsWith("read") ? "readings" : row[1].toLowerCase().startsWith("assign") ? "assignments" : "events"]: [row[2]] }, evidence }); else if (index > 0 && !/^(week|instructor|office|grade|text|required|recommended|optional)/i.test(line)) week = null; }
  }
  return result;
}
